### ISSUE TITLE
Renaming proposal

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#10]
The `companies` repo has grown to a lot more than data on companies at this point. It currently also includes templates, lists of suggested companies and—most recently—supervisory authorities with possibly more things yet in the future. Thus, the name is not exactly appropriate anymore.

I propose to rename the repo from `companies` to `data` and the current `data` folder to `companies`. That should make it immediately clear what both the repo and folders are for.  
This will of course make some things with hardcoded paths break but I think the step is still necessary and it's best to do it early on while we don't have any external entities that use our data.

**Comment by zner0L** [comment]
I agree. One thing to keep in mind though, is user participation. They might not immediately know that the data repository is the correct repository to contribute to. But I trust the fraction of users wanting to contribute to be media competent enough to read our README. Feel free to rename :)
