### ISSUE TITLE
Keep outdated references in record sources?

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1042]
Sparked by https://github.com/datenanfragen/data/pull/995#r598057551:

Should we keep outdated references in the record sources?

In the example from above, the address we had in the record was based on a filing with the company register. The company then later changed their address, yielding a new filing as a source. Should we still keep the old, outdated filing as a source?

Personally, I think that's not necessary (or constructive). The outdated sources will probably just confuse people and don't add much value anyway. For anyone who is interested in the history of the record, we already list the PRs it was affected by as sources, anyway.  
But I am definitely open for discussion on this topic.

**Comment by mal-tee** [comment]
I think as long as we expose all sources on `website` we don't need to keep them all. Especially because some sources will be dead links in the future.

**Comment by baltpeter** [comment]
It seems like we agree. From now on, we will remove outdated sources.
