### ISSUE TITLE
Add missing German SVAs: Rundfunkdatenschutzbeauftragte

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1126]
Just when you thought the situation in Germany couldn't get any more complex…

We are missing all 'Rundfunkdatenschutzbeauftragte': https://www.baden-wuerttemberg.datenschutz.de/rundfunkdatenschutzbeauftragte/

**Comment by moriarty-jim** [comment]
[https://www.bfdi.bund.de/DE/Service/Anschriften/Rundfunk/Rundfunk-node.html](https://www.bfdi.bund.de/DE/Service/Anschriften/Rundfunk/Rundfunk-node.html) should list all of them. Can these be added to supervisory-authorities or are changes to website/backend required beforehand?

**Comment by baltpeter** [comment]
> bfdi.bund.de/DE/Service/Anschriften/Rundfunk/Rundfunk-node.html should list all of them.

Looks good. Where possible, I would prefer to use the authorities' own websites as the source, though.

> Can these be added to supervisory-authorities or are changes to website/backend required beforehand?

They can just be added, no prior changes are necessary. After they are added, we need to update the SVA finder but that is tracked in a separate issue (datenanfragen/website#532).
