### ISSUE TITLE
Add TOTAL Mineralöl GmbH

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/data#1164]
heizoel.totalenergies.de is ran by _TOTAL Mineralöl GmbH_ according to https://heizoel.totalenergies.de/datenschutzerklaerung/, that should go in a separate record.

_Originally posted by @mal-tee in https://github.com/datenanfragen/data/issues/1155#issuecomment-869167202_

**Comment by fm** [comment]
Even though it says at the very bottom that the record on #1155 also applies?

```
Für die Ausübung Ihrer Rechte wenden Sie sich zum Beispiel per Post an:

TOTAL Deutschland GmbH
Datenschutz
Jean-Monnet-Str. 2
10557 Berlin
```

**Comment by mal-tee** [comment]
Oh, thank you. I totally (haha) missed that.
