### ISSUE TITLE
Add the different companies running *Swapfiets* 

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/data#1174]
Swapfiets is run by different companies, depending on the country. In #1165 I've added the german one. 
There are still others that can be, added, such as: 
- [ ] Swapfiets B.V (https://swapfiets.com/nl-NL/privacy)
- [ ] Swapfiets Demark ApS (https://swapfiets.com/da-DK/privacy)
- [ ] Swapfiets België BVBA (https://swapfiets.com/nl-BE/privacy)
- [ ] Swapfiets Spain S.l (https://swapfiets.com/en-ES/privacy) 
- [ ] Swapfiets Italia S.r.l (https://swapfiets.com/it-IT/privacy)
- [ ] Swapfiets Limited and Swapservices B.V. (https://swapfiets.com/en-GB/privacy)
- [ ] Swapfiets Austria GmbH (https://swapfiets.com/de-AT/privacy)

**Comment by fm** [comment]
Would we not add them in a single entry, like we did for Lime or Deliveroo?

**Comment by mal-tee** [comment]
We would do that, if you could reach them all at the same contact details, i.e. `address`, `email`, .. or if one parent company is clearly responsible for the different legal entities, or as we say it in the `schema.json`: 

> A list of other services and companies the parent company is responsible (as defined in Article 4(7) GDPR) for.

I haven't checked if this applies here, I've just noticed that they all mention different companies.

**Comment by moriarty-jim** [comment]
I'll try to work on this issue in the next days.

**Comment by moriarty-jim** [comment]
> I haven't checked if this applies here, I've just noticed that they all mention different companies.

There are separate companies for each country. Just the email-address is sometimes identical.
