### ISSUE TITLE
Add remaining ProSiebenSat.1 brands

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1255]
In #1241, we added a record for the website of German TV station Sat.1. The same company also runs a lot of other websites that we also want to add. However unfortunately, they all have slightly different contact details, so they all need their own records. See the comments in #1241 for more details.

The records can be created by simply copying the existing one for the Sat.1 website and changing the relevant details.

**Comment by vikramadityasinghs** [comment]
hi, has this issue been closed? if not I would love to work on it!

**Comment by baltpeter** [comment]
@vikramadityasinghs No, it has not been closed. But I would recommend this issue only to people who know at least some German.

**Comment by vikramadityasinghs** [comment]
@baltpeter I studied a bit of German in my school as well as for a semester in College, would that suffice?

**Comment by baltpeter** [comment]
@vikramadityasinghs That should be enough. I'll assign you.

**Comment by vikramadityasinghs** [comment]
@baltpeter thanks! 
> The same company also runs a lot of other websites
where would i find the details of the other companies that need to be added?

**Comment by baltpeter** [comment]
@vikramadityasinghs The website (https://www.sat1.de/) lists the other brands, websites, and apps at the bottom. The rest should be explained by our README.
