### ISSUE TITLE
Tests: Disallow `web` field for records with `"nsfw": true`

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1369]
In our governing association's general assembly on September 15, 2021, we decided that records which are not safe for work (i.e. those with the `nsfw` field set to `true`) cannot have a website (field `web`) set.

This needs to be ensured through the tests.

**This can only be implemented after #1233 is merged.**

**Comment by GonzoJurezz** [comment]
I am planing to add a nsfw element to the CompanyRecords.ts to refere to it in the Test. 
Are you okay with that, or should use another solution? I am guessing, there could be a reason, why it is not already in the CompanyRecords.ts.
