### ISSUE TITLE
Merge 'ERGO Group AG' and 'ERGO Direkt Versicherungen'

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/data#1398]
Please merge the records "`ERGO Group AG`" and "`ERGO Direkt Versicherungen`" under the name "`ERGO Group AG`".

```
https://www.datenanfragen.de/company/ergo-group
https://www.datenanfragen.de/company/ergo-direkt
```

Justification:

1. In the event of a request as mentioned under #1396 a reply will be sent in the name of "`ERGO Group AG`".
2. `ergodirekt.de` forwards to `ergo.de`.
3. `ergodirekt.de/de/datenschutzunddatensicherheit.html` forwards to `https://www.ergo.de/de/Service/Datenschutz`.

**Comment by fm** [comment]
Will do. Thank you!

**Comment by baltpeter** [comment]
@fm This one isn't exactly straightforward but I still think we should merge them. I'll try to explain my justifications:

* According to [this](https://www.handelsblatt.com/finanzen/banken-versicherungen/versicherer/neue-vertriebsstrategie-der-kampf-der-systeme-versicherer-ergo-laesst-marke-ergo-direkt-sterben/24308238.html) (linked from the German Wikipedia page on ERGO), they are phasing out the brand "ERGO Direkt" and not offering services under that name anymore. That lines up with the website and source redirecting to ERGO proper now.
* As far as I can tell, ERGO Direkt AG is still offering insurance services, though: https://www.ergo.de/de/Service/Anbieter
* The [privacy policy](https://www.ergo.de/de/Service/Datenschutz) lists these two documents, which indicate that the different ERGO Group companies share databases and other data processing activities: https://www.ergo.de/bin/ergo/public/dam.download.inline./content/dam/ergo/pdf/public/ERGO-Direkt_Dienstleisterliste.pdf and https://www.ergo.de/bin/ergo/public/dam.download.inline./content/dam/ergo/pdf/public/ERGO_Dienstleisterliste.pdf
* While the privacy policy only talks about the processing on the website, it also links information sheets for the processing done by the different insurance companies (under "7. Informationen für Interessenten und Versicherungskunden, Dienstleisterliste"). From going through a few of those, the ERGO branded ones all tell you to contact datenschutz@ergo.de.
* So, from my understanding, while these are different companies with different addresses, they seem to have appointed the DPO of ERGO Group AG as their DPO as well. This lines up with what @WebworkrNet said as the ERGO Group AG DPO answers requests for the other companies as well.
