### ISSUE TITLE
Add Spanish Axel Springer properties

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1414]
The following Spanish Axel Springer properties are missing in our database:

* https://www.axelspringer.es/politica-privacidad/
* https://computerhoy.com/politica-privacidad-chn
* https://www.autobild.es/politica_privacidad
* https://www.hobbyconsolas.com/politica-de-privacidad
* https://www.businessinsider.es/politica-privacidad
* https://www.topgear.es/politica-privacidad

They can all be added in a single record.

**Comment by sabith-nadakkavil** [comment]
@baltpeter Can you please guide me to add these properties in DB?

**Comment by baltpeter** [comment]
@sabith-nadakkavil Have you looked at our README? That should explain everything. Feel free to ask if you have specific questions.
