### ISSUE TITLE
AdGear email doesn't work

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1470]
The mail listed in the `adgear` record and their [privacy policy](https://adgear.com/en/privacy/), privacy@adgear.com, doesn't work:

> <privacy@adgear.com>:
> 64.233.184.26 failed after I sent the message.
> Remote host said: 550-5.7.1 The user or domain that you are sending to (or from) has a policy that
> 550-5.7.1 prohibited the mail that you sent. Please contact your domain
> 550-5.7.1 administrator for further details. For more information, please visit
> 550 5.7.1  https://support.google.com/a/answer/172179 u18si2983366wri.151 - gsmtp

From a quick look over their website, I wasn't able to find any other email address either, so I wasn't able to ask them to fix this.

**Comment by fm** [comment]
Got an email back

**Comment by fm** [comment]
Got a reply back...

```
Hi Faisal

Thanks for your email.

I’ve relayed your observation internally to the team who maintain the email system.
```
