### ISSUE TITLE
"Nativo London Limited" email doesn't work

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1472]
Neither of the emails listed in their [privacy policy](https://www.nativo.com/privacy-policy), privacy@nativo.com and eurep@nativo.com, works:

> Your message to privacy@nativo.com couldn't be delivered.
> privacy wasn't found at nativo.com.
> [Long generic message by Office 365 on what a user might do in this situation. :D]

I have tried to contact the company they list as their EU representative and contact point for complaints (www.dpocentre.com) directly to get this fixed.

In the meantime, they do have a [web form for requests](https://submit-irm.trustarc.com/services/validation/e1b081d3-40df-4137-add0-7e34cf4d13b2).

**Comment by moriarty-jim** [comment]
🎉 

> **From: privacy@nativo.com**
>
> Hi,
>  
> Yes, this email is working. Apologies for any inconvenience – we worked to solve the problem immediately when it was brought to our attention.
>  
> If you have a data subject access request, please reply to this email with your request and our support team will handle it.
>  
> Best,
>  
> Nativo’s Privacy Team
>
