### ISSUE TITLE
Set `suggested-transport-medium` to `webform` for a few companies

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#1474]
Based on my requests to them. At the moment, our schema and `website` don't support that yet, so I am using this issue to track the changes for now.

**Comment by baltpeter** [comment]
Quantcast: https://www.quantcast.com/privacy/data-subject-rights/

> Hello,
> 
> Thank you for contacting us regarding your Data Subject Rights under GDPR.
> We do not have names, email addresses, or other directly identifiable
> information about consumers. Instead, we use a pseudonymous identifier (a
> cookie ID) to associate information with a consumer’s browser. In order to
> respond to your request, we need to confirm your cookie ID. Please visit
> the following website to make your request:
> https://www.quantcast.com/privacy/data-subject-rights/. (For your
> convenience, the website will automatically check your cookie ID for
> you.)
> 
> Sincerely,
> 
> Quantcast

**Comment by baltpeter** [comment]
Adform: https://site.adform.com/privacy-center/platform-privacy/rights-to-insights/

> Please keep in mind that the Cookie ID is located on your device. In order for Adform to verify your identity and associate it with pseudonymous data Adform collects, to respond to your data subject access request and to make sure that we respond to a correct person, and for you to rightfully claim information behind the Cookie ID, please fill out, sign and send us the Identity Verification Form according to procedure at https://site.adform.com/privacy-center/platform-privacy/rights-to-insights/.
> 
> Once we receive a completed ‘Right to information’ form, according to the instructions above, we will be able to collect the data that we have pertaining to the cookie ID of your device as well as the purposes for which your personal data is being processed and share our findings with you.

**Comment by baltpeter** [comment]
Cuebiq: https://www.cuebiq.com/privacy-request/

**Comment by fm** [comment]
Newfold Digital https://newfold.com/privacy-center/requests
