### ISSUE TITLE
New company suggestion `KSV1870 Holding AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#151]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "credit agency",
        "collection agency",
        "finance"
    ],
    "name": "KSV1870 Holding AG",
    "address": "Wagenseilgasse 7\n1120 Wien\nÖsterreich",
    "phone": "+43 50 1870-1000",
    "email": "ksv1870.datenschutzbeauftragter@ksv.at",
    "web": "https://www.ksv.at",
    "sources": [
        "https://www.ksv.at/datenschutzerklaerung",
        "https://github.com/datenanfragen/data/issues/151"
    ],
    "request-language": "DE",
    "needs-id-document": true,
    "comments": [
        "Hotline für Auskunftsansuchen:\n- Telefon: +43 50 1870-1101\n- Mail: ksv.sa@ksv.at"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22credit%20agency%22%2C%22collection%20agency%22%2C%22finance%22%5D%2C%22name%22%3A%22KSV1870%20Holding%20AG%22%2C%22address%22%3A%22Wagenseilgasse%207%5Cn1120%20Wien%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%2050%201870-1000%22%2C%22email%22%3A%22ksv1870.datenschutzbeauftragter%40ksv.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ksv.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ksv.at%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F151%22%5D%2C%22request-language%22%3A%22DE%22%2C%22needs-id-document%22%3Atrue%2C%22comments%22%3A%5B%22Hotline%20f%C3%BCr%20Auskunftsansuchen%3A%5Cn-%20Telefon%3A%20%2B43%2050%201870-1101%5Cn-%20Mail%3A%20ksv.sa%40ksv.at%22%5D%7D)**

**Comment by baltpeter** [comment]
Very helpful addition, thank you!
