### ISSUE TITLE
Add postident

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/data#1545]

**Comment by elias170105** [comment]
Die Deutsche Post ist bereits hinterlegt, für Postident gilt dieselbe Datenschutzmail. Dennoch habe ich den Begriff "Postident" hier vorgeschlagen, damit es in Zukunft einfacher zu finden ist. 

Link zur Post: https://www.datenanfragen.de/company/deutsche-post

**Comment by mal-tee** [comment]
danke! :D

**Comment by elias170105** [comment]
Mittlerweile ist es auch über die Webseite zu finden:)
