### ISSUE TITLE
New company suggestion `Ratsit`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#156]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "se"
    ],
    "name": "Ratsit",
    "web": "Ratsit.se",
    "request-language": "Swedish",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "sources": [
        "https://github.com/datenanfragen/data/issues/156"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22se%22%5D%2C%22name%22%3A%22Ratsit%22%2C%22web%22%3A%22Ratsit.se%22%2C%22request-language%22%3A%22Swedish%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F156%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
