### ISSUE TITLE
New company suggestion `Clark Germany GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#157]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Clark Germany GmbH",
    "address": "Goethestraße 10, 60313 Frankfurt",
    "sources": [
        "https://www.clark.de/de/impressum",
        "https://github.com/datenanfragen/data/issues/157"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Clark%20Germany%20GmbH%22%2C%22address%22%3A%22Goethestra%C3%9Fe%2010%2C%2060313%20Frankfurt%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.clark.de%2Fde%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F157%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
