### ISSUE TITLE
New company suggestion `Viant Technology`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#158]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "social media"
    ],
    "name": "Viant Technology",
    "runs": [
        "MySpace"
    ],
    "address": "News corp.\n407 North Maple Drive\nBeverly Hills, CA 90210",
    "email": "support@myspace.com",
    "web": "myspace.com",
    "sources": [
        "https://www.computerhope.com/comp/myspace.htm",
        "https://en.m.wikipedia.org/wiki/Myspace",
        "https://github.com/datenanfragen/data/issues/158"
    ],
    "request-language": "English",
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "comments": [
        "After the billions scale account hacking scandal, everyone will want to have their (often hijacked) accounts and all personal information erased."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Viant%20Technology%22%2C%22runs%22%3A%5B%22MySpace%22%5D%2C%22address%22%3A%22News%20corp.%5Cn407%20North%20Maple%20Drive%5CnBeverly%20Hills%2C%20CA%2090210%22%2C%22email%22%3A%22support%40myspace.com%22%2C%22web%22%3A%22myspace.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.computerhope.com%2Fcomp%2Fmyspace.htm%22%2C%22https%3A%2F%2Fen.m.wikipedia.org%2Fwiki%2FMyspace%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F158%22%5D%2C%22request-language%22%3A%22English%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22After%20the%20billions%20scale%20account%20hacking%20scandal%2C%20everyone%20will%20want%20to%20have%20their%20(often%20hijacked)%20accounts%20and%20all%20personal%20information%20erased.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
