### ISSUE TITLE
New company suggestion `MEDIA PUBLISHER & CO.AG LIMITED`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#160]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "MEDIA PUBLISHER & CO.AG LIMITED",
    "address": "Clifton House Office 70\nFitzwilliam Street Lower\nDublin 2\nIreland",
    "email": "info@mediapublisher-ag.com",
    "web": "mediapublisher-ag.com",
    "sources": [
        "http://mediapublisher-ag.com/imprint.html",
        "https://github.com/datenanfragen/data/issues/160"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22MEDIA%20PUBLISHER%20%26%20CO.AG%20LIMITED%22%2C%22address%22%3A%22Clifton%20House%20Office%2070%5CnFitzwilliam%20Street%20Lower%5CnDublin%202%5CnIreland%22%2C%22email%22%3A%22info%40mediapublisher-ag.com%22%2C%22web%22%3A%22mediapublisher-ag.com%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fmediapublisher-ag.com%2Fimprint.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F160%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
