### ISSUE TITLE
New company suggestion `marketmind GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#161]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "name": "marketmind GmbH",
    "address": "Porzellangasse 32\n1090 Wien\nÖsterreich",
    "phone": "+43-1-369 46 26-0",
    "fax": "+43-1-369 46 26-33",
    "email": "datenschutz@marketmind.at",
    "web": "https://www.marketmind.at",
    "sources": [
        "https://www.marketmind.at/html/de/index.aspx?page_url=Datenschutz&mid=335",
        "https://www.marketmind.at/html/de/index.aspx?page_url=Impressum&mid=270",
        "https://github.com/datenanfragen/data/issues/161"
    ],
    "required-elements": [
        {
            "desc": "Telefonnummer",
            "type": "input"
        }
    ],
    "request-language": "de",
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "comments": [
        "Datenschutzbeauftragter: Mag. Dietmar Huemer\n\nMacht Umfragen für verschiedene Firmen. "
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22name%22%3A%22marketmind%20GmbH%22%2C%22address%22%3A%22Porzellangasse%2032%5Cn1090%20Wien%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43-1-369%2046%2026-0%22%2C%22fax%22%3A%22%2B43-1-369%2046%2026-33%22%2C%22email%22%3A%22datenschutz%40marketmind.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.marketmind.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.marketmind.at%2Fhtml%2Fde%2Findex.aspx%3Fpage_url%3DDatenschutz%26mid%3D335%22%2C%22https%3A%2F%2Fwww.marketmind.at%2Fhtml%2Fde%2Findex.aspx%3Fpage_url%3DImpressum%26mid%3D270%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F161%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Telefonnummer%22%2C%22type%22%3A%22input%22%7D%5D%2C%22request-language%22%3A%22de%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22Datenschutzbeauftragter%3A%20Mag.%20Dietmar%20Huemer%5Cn%5CnMacht%20Umfragen%20f%C3%BCr%20verschiedene%20Firmen.%20%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
