### ISSUE TITLE
New company suggestion `EVN AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#162]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "utility"
    ],
    "name": "EVN AG",
    "address": "EVN Platz\n2344 Maria Enzersdorf\nÖsterreich",
    "phone": "+43 2236 200-0",
    "fax": "+43 2236 200-2030",
    "email": "datenschutz@evn.at",
    "web": "https://www.evn.at",
    "sources": [
        "https://www.evn.at/SpecialPages/FooterLinks/Datenschutzerklarung/EVN-AG.aspx",
        "https://www.evn.at/impressum.aspx",
        "https://github.com/datenanfragen/data/issues/162"
    ],
    "request-language": "de",
    "suggested-transport-medium": "letter",
    "comments": [
        "Aufsichtsbehörde: E-Control"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22EVN%20AG%22%2C%22address%22%3A%22EVN%20Platz%5Cn2344%20Maria%20Enzersdorf%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%202236%20200-0%22%2C%22fax%22%3A%22%2B43%202236%20200-2030%22%2C%22email%22%3A%22datenschutz%40evn.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.evn.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.evn.at%2FSpecialPages%2FFooterLinks%2FDatenschutzerklarung%2FEVN-AG.aspx%22%2C%22https%3A%2F%2Fwww.evn.at%2Fimpressum.aspx%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F162%22%5D%2C%22request-language%22%3A%22de%22%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22Aufsichtsbeh%C3%B6rde%3A%20E-Control%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
