### ISSUE TITLE
New company suggestion `Circuit Launderette Services Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#164]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "utility"
    ],
    "name": "Circuit Launderette Services Limited",
    "address": "Meadowcroft Lane,\nHalifax Lane,\nRipponden,\nWest Yorkshire,\nHX6 4AJ ",
    "email": "info@circuitcardtopup.com",
    "sources": [
        "https://www.circuit.co.uk/privacy-and-cookies/",
        "https://beta.companieshouse.gov.uk/company/02944540",
        "https://github.com/datenanfragen/data/issues/164"
    ],
    "request-language": "English",
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22Circuit%20Launderette%20Services%20Limited%22%2C%22address%22%3A%22Meadowcroft%20Lane%2C%5CnHalifax%20Lane%2C%5CnRipponden%2C%5CnWest%20Yorkshire%2C%5CnHX6%204AJ%20%22%2C%22email%22%3A%22info%40circuitcardtopup.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.circuit.co.uk%2Fprivacy-and-cookies%2F%22%2C%22https%3A%2F%2Fbeta.companieshouse.gov.uk%2Fcompany%2F02944540%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F164%22%5D%2C%22request-language%22%3A%22English%22%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
