### ISSUE TITLE
Suggested update for company `ratepay`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#165]
The following suggestion was submitted through the website:

```
{
    "slug": "ratepay",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "finance"
    ],
    "name": "RatePAY GmbH",
    "address": "Franklinstraße 28 – 29\n10587 Berlin\nDeutschland",
    "phone": "+49 30 339 88 56 0",
    "fax": "+49 30 339 88 56 10",
    "email": "datenschutz@ratepay.com",
    "web": "https://www.ratepay.com",
    "sources": [
        "https://www.ratepay.com/zusaetzliche-geschaeftsbedingungen-und-datenschutzhinweis-dach/#dse_de",
        "https://www.ratepay.com/impressum/",
        "https://github.com/datenanfragen/data/issues/165"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ratepay%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22RatePAY%20GmbH%22%2C%22address%22%3A%22Franklinstra%C3%9Fe%2028%20%E2%80%93%C2%A029%5Cn10587%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20339%2088%2056%200%22%2C%22fax%22%3A%22%2B49%2030%20339%2088%2056%2010%22%2C%22email%22%3A%22datenschutz%40ratepay.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ratepay.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ratepay.com%2Fzusaetzliche-geschaeftsbedingungen-und-datenschutzhinweis-dach%2F%23dse_de%22%2C%22https%3A%2F%2Fwww.ratepay.com%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F165%22%5D%7D)**

**Comment by baltpeter** [comment]
Great, thanks!
