### ISSUE TITLE
Suggested update for company `dlc-gb`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#166]
The following suggestion was submitted through the website:

```
{
    "slug": "dlc-gb",
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "Hillesden Securities Ltd.",
    "runs": [
        "dlc credit agency",
        "Cabot Credit Management Group Ltd."
    ],
    "address": "Buckingham Road\nBrackley\nNorthants\nNN13 7DN\nUnited Kingdom",
    "phone": "+44 20 7896 6300",
    "email": "data.protection@dlcuk.com",
    "web": "http://www.dlcuk.com/",
    "sources": [
        "http://www.dlcuk.com/privacy-policy/",
        "https://www.mydlc.co.uk/contact",
        "https://github.com/datenanfragen/data/issues/166"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22dlc-gb%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22Hillesden%20Securities%20Ltd.%22%2C%22runs%22%3A%5B%22dlc%20credit%20agency%22%2C%22Cabot%20Credit%20Management%20Group%20Ltd.%22%5D%2C%22address%22%3A%22Buckingham%20Road%5CnBrackley%5CnNorthants%5CnNN13%207DN%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%2020%207896%206300%22%2C%22email%22%3A%22data.protection%40dlcuk.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.dlcuk.com%2F%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.dlcuk.com%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fwww.mydlc.co.uk%2Fcontact%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F166%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you.
