### ISSUE TITLE
New company suggestion: `Skånetrafiken`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#168]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "se",
        "dk"
    ],
    "categories": [
        "travel"
    ],
    "name": "Skånetrafiken",
    "address": "Andra Avenyen 7\n281 31 Hässleholm",
    "phone": "+46 77 177 77 77",
    "email": "skkontrollavgifter@skanetrafiken.se",
    "web": "https://www.skanetrafiken.se/",
    "slug": "skanetrafikense",
    "sources": [
        "https://github.com/datenanfragen/data/issues/168"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22se%22%2C%22dk%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Sk%C3%A5netrafiken%22%2C%22address%22%3A%22Andra%20Avenyen%207%5Cn281%2031%20H%C3%A4ssleholm%22%2C%22phone%22%3A%22%2B46%2077%20177%2077%2077%22%2C%22email%22%3A%22skkontrollavgifter%40skanetrafiken.se%22%2C%22web%22%3A%22https%3A%2F%2Fwww.skanetrafiken.se%2F%22%2C%22slug%22%3A%22skanetrafikense%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F168%22%5D%7D)**

**Comment by webjay** [comment]
Sorry, the form gave me an error.
Dublicate of #167

**Comment by baltpeter** [comment]
Hi,

no problem at all. Thanks for the submission.

There does seem to be an issue with the form, I will look into that.
