### ISSUE TITLE
Check if the companies in company packs exist in the database

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/data#1759]
Check if all [suggested companies](https://github.com/datenanfragen/data/tree/master/suggested-companies) exist in this repo, i.e. is there one record for each slug in the suggested companies lists?

**Comment by baltpeter** [comment]
With #1786 and #1790, suggested companies will be deprecated and superseded by the new company packs. I'll implement the tests for them instead.

**Comment by baltpeter** [comment]
Haha, and it immediately caught an error I made. :D 

![image](https://user-images.githubusercontent.com/4048809/175345138-81182a3f-a4db-4435-bee5-9710ced628ae.png)

Our test infrastructure for `data` is really quite good. :D
