### ISSUE TITLE
Suggested update for company `ebay-de`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#178]
The following suggestion was submitted through the website:

```
{
    "slug": "ebay-de",
    "relevant-countries": [
        "de",
        "at",
        "ch",
        "be",
        "fr",
        "ie",
        "it",
        "nl",
        "pl",
        "es"
    ],
    "categories": [
        "commerce"
    ],
    "name": "eBay GmbH",
    "address": "Albert-Einstein-Ring 2 – 6\n14532 Kleinmachnow\nGermany",
    "phone": "+49 30 801950",
    "fax": "+49 30 80195444",
    "email": "Anna_DPO@ebay.com",
    "web": "https://www.ebay.de/",
    "sources": [
        "https://pages.ebay.de/help/policies/privacy-policy.html",
        "https://pages.ebay.de/help/policies/legal-imprint.html",
        "https://www.ebayinc.com/our-company/privacy-center/privacy-notice/data-protection-officer-contacts/",
        "https://github.com/datenanfragen/data/issues/178"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Geburtsdatum",
            "type": "birthdate"
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "eBay hat zum 1. Mai 2018 die verantworliche Stelle geändert: \"Ab dem ‌1‌.‌ ‌M‌a‌i‌ ‌2‌0‌1‌8‌ ist für eBay-Nutzer, die in der Europäischen Union (mit Ausnahme Großbritanniens und Nordirlands) ansässig sind, nicht mehr die eBay Europe S.à r.l. Vertragspartner für die Allgemeinen Geschäftsbedingungen, Zahlungsvereinbarungen oder andere Vereinbarungen. Neuer Vertragspartner ist dann die eBay GmbH, Albert-Einstein-Ring 2–6, 14532 Kleinmachnow, Deutschland. […] Infolge der Änderung Ihres eBay-Vertragspartners wird die eBay GmbH auch neue verantwortliche Stelle für Ihre Daten im Sinne unserer Datenschutzerklärung.\"",
        "Diensteanbieter laut Impressum ist die eBay Marketplaces GmbH, Helvetiastrasse 15/17, 3005 Bern, Schweiz.",
        "Nachrichten an die angegebene E-Mail-Adresse werden automatisch beantwortet mit dem Hinweis, dass das Postfach nicht überprüft werde und man die Anfrage über https://www.ebayinc.com/our-company/privacy-center/privacy-contact/ absenden solle."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ebay-de%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%2C%22be%22%2C%22fr%22%2C%22ie%22%2C%22it%22%2C%22nl%22%2C%22pl%22%2C%22es%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22eBay%20GmbH%22%2C%22address%22%3A%22Albert-Einstein-Ring%202%20%E2%80%93%206%5Cn14532%20Kleinmachnow%5CnGermany%22%2C%22phone%22%3A%22%2B49%2030%20801950%22%2C%22fax%22%3A%22%2B49%2030%2080195444%22%2C%22email%22%3A%22Anna_DPO%40ebay.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ebay.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpages.ebay.de%2Fhelp%2Fpolicies%2Fprivacy-policy.html%22%2C%22https%3A%2F%2Fpages.ebay.de%2Fhelp%2Fpolicies%2Flegal-imprint.html%22%2C%22https%3A%2F%2Fwww.ebayinc.com%2Four-company%2Fprivacy-center%2Fprivacy-notice%2Fdata-protection-officer-contacts%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F178%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Geburtsdatum%22%2C%22type%22%3A%22birthdate%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22eBay%20hat%20zum%201.%20Mai%202018%20die%20verantworliche%20Stelle%20ge%C3%A4ndert%3A%20%5C%22Ab%20dem%20%E2%80%8C1%E2%80%8C.%E2%80%8C%20%E2%80%8CM%E2%80%8Ca%E2%80%8Ci%E2%80%8C%20%E2%80%8C2%E2%80%8C0%E2%80%8C1%E2%80%8C8%E2%80%8C%20ist%20f%C3%BCr%20eBay-Nutzer%2C%20die%20in%20der%20Europ%C3%A4ischen%20Union%20(mit%20Ausnahme%20Gro%C3%9Fbritanniens%20und%20Nordirlands)%20ans%C3%A4ssig%20sind%2C%20nicht%20mehr%20die%20eBay%20Europe%20S.%C3%A0%20r.l.%20Vertragspartner%20f%C3%BCr%20die%20Allgemeinen%20Gesch%C3%A4ftsbedingungen%2C%20Zahlungsvereinbarungen%20oder%20andere%20Vereinbarungen.%20Neuer%20Vertragspartner%20ist%20dann%20die%20eBay%20GmbH%2C%20Albert-Einstein-Ring%202%E2%80%936%2C%2014532%20Kleinmachnow%2C%20Deutschland.%20%5B%E2%80%A6%5D%20Infolge%20der%20%C3%84nderung%20Ihres%20eBay-Vertragspartners%20wird%20die%20eBay%20GmbH%20auch%20neue%20verantwortliche%20Stelle%20f%C3%BCr%20Ihre%20Daten%20im%20Sinne%20unserer%20Datenschutzerkl%C3%A4rung.%5C%22%22%2C%22Diensteanbieter%20laut%20Impressum%20ist%20die%20eBay%20Marketplaces%20GmbH%2C%20Helvetiastrasse%2015%2F17%2C%203005%20Bern%2C%20Schweiz.%22%2C%22Nachrichten%20an%20die%20angegebene%20E-Mail-Adresse%20werden%20automatisch%20beantwortet%20mit%20dem%20Hinweis%2C%20dass%20das%20Postfach%20nicht%20%C3%BCberpr%C3%BCft%20werde%20und%20man%20die%20Anfrage%20%C3%BCber%20https%3A%2F%2Fwww.ebayinc.com%2Four-company%2Fprivacy-center%2Fprivacy-contact%2F%20absenden%20solle.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
