### ISSUE TITLE
Add "packs" of suggested companies

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/data#1786]
In our UX-Coaching with SimplySecure, we discussed having "packs" of companies to suggest for requests. These could be analogous to the categories, e.g. a "Scoring agencies pack". But packs could also by "cross-category", e.g. a "Car driver pack", which would include the "Kraftfahrbundesamt" and some typical insurance companies for example.

We want to use this to suggest companies to users in the search UI, if they didn't start searching yet.

**Comment by mal-tee** [comment]
Do you guys intend to implement this in the record, i.e. the scheme or in a separate list like the suggested companies?

**Comment by baltpeter** [comment]
In a separate file.
