### ISSUE TITLE
Suggested update for company `erasmusu`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#179]
The following suggestion was submitted through the website:

```
{
    "slug": "erasmusu",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "travel"
    ],
    "name": "COKIDOO STUDIOS S.L.U.",
    "runs": [
        "erasmusu.com"
    ],
    "address": "Calle Fernando Alonso Navarro 12, 1º\n30009 Murcia\nSpain",
    "phone": "+34 694 47 24 62",
    "email": "info@erasmusu.com",
    "web": "https://erasmusu.com",
    "sources": [
        "https://erasmusu.com/en/legal",
        "https://github.com/datenanfragen/data/issues/179"
    ],
    "required-elements": [
        {
            "desc": "Account email",
            "type": "input",
            "optional": true
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22erasmusu%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22COKIDOO%20STUDIOS%20S.L.U.%22%2C%22runs%22%3A%5B%22erasmusu.com%22%5D%2C%22address%22%3A%22Calle%20Fernando%20Alonso%20Navarro%2012%2C%201%C2%BA%5Cn30009%20Murcia%5CnSpain%22%2C%22phone%22%3A%22%2B34%20694%2047%2024%2062%22%2C%22email%22%3A%22info%40erasmusu.com%22%2C%22web%22%3A%22https%3A%2F%2Ferasmusu.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ferasmusu.com%2Fen%2Flegal%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F179%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Account%20email%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Atrue%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks for the phone number!

As for the email, the privacy policy still reads:

> The User may exercise these rights at any time by sending a notification, accompanied by a document confirming his identity, with the right to be exercised expressly stated. The notification shall be sent to the attention of ERASMUSU to the address hereinabove indicated or to the email address: legal@erasmusu.com.

Thus, I think leaving the current one is better.
