### ISSUE TITLE
New company suggestion: `IFPI`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#180]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "IFPI",
    "address": "IFPI Secretariat\n7 Air Street\nLondon\nW1B 5AD\nUnited Kingdom",
    "phone": "+44 20 7878 7900",
    "fax": "+44 20 7878 7950",
    "email": "info@ifpi.org",
    "web": "https://www.ifpi.org/",
    "sources": [
        "https://www.ifpi.org/contacts.php",
        "https://github.com/datenanfragen/data/issues/180"
    ],
    "comments": [
        "IFPI probably downloaded all videos ever uploaded to Twitter. Users have a right to know if their personal videos are processed by them and why. https://twitter.com/luca/status/1146873652874547201?s=20"
    ],
    "slug": "ifpiorg"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22IFPI%22%2C%22address%22%3A%22IFPI%20Secretariat%5Cn7%20Air%20Street%5CnLondon%5CnW1B%205AD%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%2020%207878%207900%22%2C%22fax%22%3A%22%2B44%2020%207878%207950%22%2C%22email%22%3A%22info%40ifpi.org%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ifpi.org%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ifpi.org%2Fcontacts.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F180%22%5D%2C%22comments%22%3A%5B%22IFPI%20probably%20downloaded%20all%20videos%20ever%20uploaded%20to%20Twitter.%20Users%20have%20a%20right%20to%20know%20if%20their%20personal%20videos%20are%20processed%20by%20them%20and%20why.%20https%3A%2F%2Ftwitter.com%2Fluca%2Fstatus%2F1146873652874547201%3Fs%3D20%22%5D%2C%22slug%22%3A%22ifpiorg%22%7D)**

**Comment by baltpeter** [comment]
Thank you.
