### ISSUE TITLE
New company suggestion: `pluralsight`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#181]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb",
        "all"
    ],
    "categories": [
        "school"
    ],
    "name": "pluralsight",
    "address": "Southpoint, Herbert House\n11 Harmony Row\nDublin DO2 H270\nDublin\nIRELAND ",
    "phone": "+1 801 784 9007",
    "email": "support@pluralsight.com",
    "sources": [
        "https://www.pluralsight.com",
        "https://github.com/datenanfragen/data/issues/181"
    ],
    "slug": "pluralsight"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%2C%22all%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22pluralsight%22%2C%22address%22%3A%22Southpoint%2C%20Herbert%20House%5Cn11%20Harmony%20Row%5CnDublin%20DO2%20H270%5CnDublin%5CnIRELAND%20%22%2C%22phone%22%3A%22%2B1%20801%20784%209007%22%2C%22email%22%3A%22support%40pluralsight.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.pluralsight.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F181%22%5D%2C%22slug%22%3A%22pluralsight%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
