### ISSUE TITLE
New company suggestion: `Save.TV GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#182]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Save.TV GmbH",
    "address": "Save.TV GmbH\nFriedrich-List-Platz 1\n04103 Leipzig ",
    "phone": "+49 341 30213021",
    "email": "info@save.tv",
    "sources": [
        "https://www.save.tv/stv/s/misc/policy.cfm",
        "https://www.save.tv/stv/s/misc/impressum.cfm",
        "https://github.com/datenanfragen/data/issues/182"
    ],
    "comments": [
        "No dedicated email address for GDPR related inquires, seems to be really shady"
    ],
    "slug": "savetv-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Save.TV%20GmbH%22%2C%22address%22%3A%22Save.TV%20GmbH%5CnFriedrich-List-Platz%201%5Cn04103%20Leipzig%20%22%2C%22phone%22%3A%22%2B49%20341%2030213021%22%2C%22email%22%3A%22info%40save.tv%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.save.tv%2Fstv%2Fs%2Fmisc%2Fpolicy.cfm%22%2C%22https%3A%2F%2Fwww.save.tv%2Fstv%2Fs%2Fmisc%2Fimpressum.cfm%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F182%22%5D%2C%22comments%22%3A%5B%22No%20dedicated%20email%20address%20for%20GDPR%20related%20inquires%2C%20seems%20to%20be%20really%20shady%22%5D%2C%22slug%22%3A%22savetv-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
