### ISSUE TITLE
New company suggestion: `Direkta Gesellschaft für Marketing mbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#185]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads"
    ],
    "name": "Direkta Gesellschaft für Marketing mbH",
    "address": "Hoyendonk 12\n47638\nStraelen",
    "phone": "02834/982614",
    "fax": "02834/7982617",
    "sources": [
        "Verweis durch anderes Unternehmen bei DSGVO Anfrage",
        "https://github.com/datenanfragen/data/issues/185"
    ],
    "required-elements": [
        {
            "type": "input"
        }
    ],
    "needs-id-document": false,
    "slug": "direkta-gesellschaft-fr-marketing-mbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Direkta%20Gesellschaft%20f%C3%BCr%20Marketing%20mbH%22%2C%22address%22%3A%22Hoyendonk%2012%5Cn47638%5CnStraelen%22%2C%22phone%22%3A%2202834%2F982614%22%2C%22fax%22%3A%2202834%2F7982617%22%2C%22sources%22%3A%5B%22Verweis%20durch%20anderes%20Unternehmen%20bei%20DSGVO%20Anfrage%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F185%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22slug%22%3A%22direkta-gesellschaft-fr-marketing-mbh%22%7D)**

**Comment by baltpeter** [comment]
Thank you.
