### ISSUE TITLE
Suggested update for company `thehut-com`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#186]
The following suggestion was submitted through the website:

```
{
    "slug": "thehut-com",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce"
    ],
    "name": "The Hut.com Ltd.",
    "address": "Meridian House\nGadbrook Park\nCheshire CW9 7RA\nUnited Kingdom",
    "phone": "+44 161 813 1481",
    "email": "customer.experience@thehutgroup.com",
    "web": "https://www.thehut.com/",
    "sources": [
        "https://www.thehut.com/articles/privacy-policy.list",
        "https://github.com/datenanfragen/data/issues/186"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22thehut-com%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22The%20Hut.com%20Ltd.%22%2C%22address%22%3A%22Meridian%20House%5CnGadbrook%20Park%5CnCheshire%20CW9%207RA%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%20161%20813%201481%22%2C%22email%22%3A%22customer.experience%40thehutgroup.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.thehut.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.thehut.com%2Farticles%2Fprivacy-policy.list%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F186%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
