### ISSUE TITLE
New company suggestion: `globalme.net`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#187]
The following suggestion was submitted through the website:

```
{
    "name": "globalme.net",
    "address": "Canada\n1008 Homer Street #310 \nVancouver, BC V6B 2X1",
    "slug": "globalmenet",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/187"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22globalme.net%22%2C%22address%22%3A%22Canada%5Cn1008%20Homer%20Street%20%23310%20%5CnVancouver%2C%20BC%20V6B%202X1%22%2C%22slug%22%3A%22globalmenet%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F187%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
