### ISSUE TITLE
New company suggestion: `SOS-Kinderdorf e.V.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#188]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "SOS-Kinderdorf e.V.",
    "address": "Renatastraße 77\n80639 München",
    "phone": "089/12 606 – 0",
    "fax": "089/12 606 – 404",
    "slug": "sos-kinderdorf-ev",
    "sources": [
        "https://github.com/datenanfragen/data/issues/188"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22SOS-Kinderdorf%20e.V.%22%2C%22address%22%3A%22Renatastra%C3%9Fe%2077%5Cn80639%20M%C3%BCnchen%22%2C%22phone%22%3A%22089%2F12%20606%20%E2%80%93%200%22%2C%22fax%22%3A%22089%2F12%20606%20%E2%80%93%20404%22%2C%22slug%22%3A%22sos-kinderdorf-ev%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F188%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
