### ISSUE TITLE
New company suggestion: `Energie SaarLorLux`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#189]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Energie SaarLorLux",
    "address": "Richard-Wagner-Straße 14-16\n66111 Saarbrücken\n",
    "phone": "(06 81) 5 87-47 77",
    "fax": "(06 81) 5 87-46 50",
    "email": "info@energie-saarlorlux.com",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/189"
    ],
    "slug": "energie-saarlorlux"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Energie%20SaarLorLux%22%2C%22address%22%3A%22Richard-Wagner-Stra%C3%9Fe%2014-16%5Cn66111%20Saarbr%C3%BCcken%5Cn%22%2C%22phone%22%3A%22(06%2081)%205%2087-47%2077%22%2C%22fax%22%3A%22(06%2081)%205%2087-46%2050%22%2C%22email%22%3A%22info%40energie-saarlorlux.com%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F189%22%5D%2C%22slug%22%3A%22energie-saarlorlux%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
