### ISSUE TITLE
New company suggestion: `Evolution Recruitment Solutions Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#191]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "name": "Evolution Recruitment Solutions Ltd",
    "address": "The Genesis Centre, \nBirchwood, \nWarrington, \nWA3 7BH\nUnited Kingdom",
    "email": "privacy@evolutionjobs.com",
    "web": "https://www.evolutionjobs.com/uk/",
    "sources": [
        "https://www.iubenda.com/privacy-policy/54951181",
        "https://github.com/datenanfragen/data/issues/191"
    ],
    "suggested-transport-medium": "email",
    "slug": "evolutionjobscom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22name%22%3A%22Evolution%20Recruitment%20Solutions%20Ltd%22%2C%22address%22%3A%22The%20Genesis%20Centre%2C%20%5CnBirchwood%2C%20%5CnWarrington%2C%20%5CnWA3%207BH%5CnUnited%20Kingdom%22%2C%22email%22%3A%22privacy%40evolutionjobs.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.evolutionjobs.com%2Fuk%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.iubenda.com%2Fprivacy-policy%2F54951181%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F191%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22evolutionjobscom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
