### ISSUE TITLE
New company suggestion: `UAB „Tavo mokykla“`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#192]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "lt"
    ],
    "name": "UAB „Tavo mokykla“",
    "address": "Kareivių g. 11B, LT-09108 Vilnius",
    "phone": "+370 5 279 0502",
    "email": "info@tamo.lt",
    "web": "https://www.tamo.lt/",
    "sources": [
        "https://www.tamo.lt/",
        "https://rekvizitai.vz.lt/imone/tavo_mokykla/",
        "https://github.com/datenanfragen/data/issues/192"
    ],
    "suggested-transport-medium": "email",
    "slug": "tamolt"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22lt%22%5D%2C%22name%22%3A%22UAB%20%E2%80%9ETavo%20mokykla%E2%80%9C%22%2C%22address%22%3A%22Kareivi%C5%B3%20g.%2011B%2C%20LT-09108%20Vilnius%22%2C%22phone%22%3A%22%2B370%205%20279%200502%22%2C%22email%22%3A%22info%40tamo.lt%22%2C%22web%22%3A%22https%3A%2F%2Fwww.tamo.lt%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.tamo.lt%2F%22%2C%22https%3A%2F%2Frekvizitai.vz.lt%2Fimone%2Ftavo_mokykla%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F192%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22tamolt%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
