### ISSUE TITLE
NRW LDI source URL is 404

### ISSUE THREAD

**Issue by Nothing4You** [datenanfragen/data#1923]
Hi,

https://github.com/datenanfragen/data/blob/master/supervisory-authorities/denrwldi.json links to https://www.ldi.nrw.de/metanavi_Kontakt/index.php as source, but this page is 404.
I think https://www.ldi.nrw.de/kontakt is probably the appropriate link now.

**Comment by baltpeter** [comment]
Thanks! I've fixed the sources and also updated the contact details.
