### ISSUE TITLE
New company suggestion: `Unsecured-Loans.de`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#193]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "finance"
    ],
    "name": "Unsecured-Loans.de",
    "address": "Mohrenstraße 65, 10117 Berlin, G96Q+VF, Germany",
    "email": "[REDACTED]",
    "web": "https://www.unsecured-loans.de/",
    "sources": [
        "I want to contribute",
        "https://github.com/datenanfragen/data/issues/193"
    ],
    "slug": "unsecured-loansde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Unsecured-Loans.de%22%2C%22address%22%3A%22Mohrenstra%C3%9Fe%2065%2C%2010117%20Berlin%2C%20G96Q%2BVF%2C%20Germany%22%2C%22email%22%3A%22REDACTED%22%2C%22web%22%3A%22https%3A%2F%2Fwww.unsecured-loans.de%2F%22%2C%22sources%22%3A%5B%22I%20want%20to%20contribute%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F193%22%5D%2C%22slug%22%3A%22unsecured-loansde%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
