### ISSUE TITLE
New company suggestion: `Trellis Research Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#195]
The following suggestion was submitted through the website:

```
{
    "name": "Trellis Research Inc.",
    "address": "251 LITTLE FALLS DRIVE\nWILMINGTON, DE 19808",
    "phone": "302-636-5440",
    "email": "info@trellis.law",
    "web": "https://trellis.law",
    "sources": [
        "https://trellis.law/privacy",
        "https://github.com/datenanfragen/data/issues/195"
    ],
    "suggested-transport-medium": "email",
    "slug": "trellislaw",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22Trellis%20Research%20Inc.%22%2C%22address%22%3A%22251%20LITTLE%20FALLS%20DRIVE%5CnWILMINGTON%2C%20DE%2019808%22%2C%22phone%22%3A%22302-636-5440%22%2C%22email%22%3A%22info%40trellis.law%22%2C%22web%22%3A%22https%3A%2F%2Ftrellis.law%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ftrellis.law%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F195%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22trellislaw%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
