### ISSUE TITLE
New company suggestion: `Aspirantic`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#196]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Aspirantic",
    "address": "Aspirantic\nc/o Dennis Stücken\nZeppelinstr. 4\n58313 Herdecke\nGermany",
    "email": "support@aspirantic.com",
    "web": "https://aspirantic.com",
    "sources": [
        "Company Website",
        "https://github.com/datenanfragen/data/issues/196"
    ],
    "suggested-transport-medium": "email",
    "slug": "aspiranticcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Aspirantic%22%2C%22address%22%3A%22Aspirantic%5Cnc%2Fo%20Dennis%20St%C3%BCcken%5CnZeppelinstr.%204%5Cn58313%20Herdecke%5CnGermany%22%2C%22email%22%3A%22support%40aspirantic.com%22%2C%22web%22%3A%22https%3A%2F%2Faspirantic.com%22%2C%22sources%22%3A%5B%22Company%20Website%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F196%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22aspiranticcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
