### ISSUE TITLE
New company suggestion: `Open Knowledge Foundation Deutschland e.V.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#197]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "nonprofit"
    ],
    "name": "Open Knowledge Foundation Deutschland e.V.",
    "address": "Singerstr. 109\n10179 Berlin",
    "phone": "+49 30 577036660",
    "email": "info@okfn.de ",
    "web": "okfn.de",
    "sources": [
        "Internet",
        "https://github.com/datenanfragen/data/issues/197"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "open-knowledge-foundation-deutschland-ev"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22Open%20Knowledge%20Foundation%20Deutschland%20e.V.%22%2C%22address%22%3A%22Singerstr.%20109%5Cn10179%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%20577036660%22%2C%22email%22%3A%22info%40okfn.de%20%22%2C%22web%22%3A%22okfn.de%22%2C%22sources%22%3A%5B%22Internet%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F197%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22open-knowledge-foundation-deutschland-ev%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
