### ISSUE TITLE
New company suggestion: `DATAPART Factoring`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#199]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "collection agency",
        "finance"
    ],
    "name": "DATAPART Factoring",
    "address": "DATAPART Factoring GmbH\nSchwieberdinger Straße 60\n71636 Ludwigsburg",
    "phone": "07141934610",
    "fax": "07141934609",
    "email": "datenschutz@datapart-factoring.de",
    "web": "https://www.datapart-factoring.de/",
    "sources": [
        "https://www.datapart-factoring.de/transparenz-info/",
        "https://github.com/datenanfragen/data/issues/199"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Die DATAPART Factoring GmbH erwirbt auf der Grundlage eines Factoringvertrages von Fahrschulen Forderungen aus bestehenden und künftigen Ausbildungsverträgen mit Fahrschülern sowie aus der Verauslagung von Gebühren und Kosten."
    ],
    "slug": "datapart-factoringde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%2C%22finance%22%5D%2C%22name%22%3A%22DATAPART%20Factoring%22%2C%22address%22%3A%22DATAPART%20Factoring%20GmbH%5CnSchwieberdinger%20Stra%C3%9Fe%2060%5Cn71636%20Ludwigsburg%22%2C%22phone%22%3A%2207141934610%22%2C%22fax%22%3A%2207141934609%22%2C%22email%22%3A%22datenschutz%40datapart-factoring.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.datapart-factoring.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.datapart-factoring.de%2Ftransparenz-info%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F199%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Die%20DATAPART%20Factoring%20GmbH%20erwirbt%20auf%20der%20Grundlage%20eines%20Factoringvertrages%20von%20Fahrschulen%20Forderungen%20aus%20bestehenden%20und%20k%C3%BCnftigen%20Ausbildungsvertr%C3%A4gen%20mit%20Fahrsch%C3%BClern%20sowie%20aus%20der%20Verauslagung%20von%20Geb%C3%BChren%20und%20Kosten.%22%5D%2C%22slug%22%3A%22datapart-factoringde%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
