### ISSUE TITLE
New company suggestion: `Better Mail Media GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#200]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads"
    ],
    "name": "Better Mail Media GmbH",
    "address": "Better Mail Media GmbH c/o WeWork\nAxel-Springer-Platz 3\n20355 Hamburg",
    "email": "mailto:info@better-mail-media.de",
    "web": "https://better-mail-media.de",
    "sources": [
        "https://better-mail-media.de/impressum/",
        "https://github.com/datenanfragen/data/issues/200"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "better-mail-mediade"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Better%20Mail%20Media%20GmbH%22%2C%22address%22%3A%22Better%20Mail%20Media%20GmbH%20c%2Fo%20WeWork%5CnAxel-Springer-Platz%203%5Cn20355%20Hamburg%22%2C%22email%22%3A%22mailto%3Ainfo%40better-mail-media.de%22%2C%22web%22%3A%22https%3A%2F%2Fbetter-mail-media.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbetter-mail-media.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F200%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22better-mail-mediade%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
