### ISSUE TITLE
New company suggestion: `mhplus`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#201]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health",
        "insurance"
    ],
    "name": "mhplus",
    "address": "mhplus Betriebskrankenkasse\nFranckstraße 8\n71636 Ludwigsburg",
    "phone": "0 71 41 / 97 90 - 0",
    "fax": "0 71 41 / 97 90 - 113",
    "email": "info@mhplus.de",
    "web": "https://www.mhplus-krankenkasse.de/",
    "slug": "mhplus-krankenkassede",
    "sources": [
        "https://github.com/datenanfragen/data/issues/201"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%2C%22insurance%22%5D%2C%22name%22%3A%22mhplus%22%2C%22address%22%3A%22mhplus%20Betriebskrankenkasse%5CnFranckstra%C3%9Fe%208%5Cn71636%20Ludwigsburg%22%2C%22phone%22%3A%220%2071%2041%20%2F%2097%2090%20-%200%22%2C%22fax%22%3A%220%2071%2041%20%2F%2097%2090%20-%20113%22%2C%22email%22%3A%22info%40mhplus.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mhplus-krankenkasse.de%2F%22%2C%22slug%22%3A%22mhplus-krankenkassede%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F201%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
