### ISSUE TITLE
New company suggestion: `Momentum Studio Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#202]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Momentum Studio Ltd",
    "address": "326 Kenilworth Road,\nBalsall Common,\nCoventry,\nCV7 7ER\nUnited Kingdom",
    "phone": "03302290013",
    "email": "gdpr@momentum.studio",
    "web": "https://momentum.studio",
    "required-elements": [
        {
            "desc": "Email Address",
            "type": "input",
            "optional": false
        }
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "momentumstudio",
    "sources": [
        "https://github.com/datenanfragen/data/issues/202"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Momentum%20Studio%20Ltd%22%2C%22address%22%3A%22326%20Kenilworth%20Road%2C%5CnBalsall%20Common%2C%5CnCoventry%2C%5CnCV7%207ER%5CnUnited%20Kingdom%22%2C%22phone%22%3A%2203302290013%22%2C%22email%22%3A%22gdpr%40momentum.studio%22%2C%22web%22%3A%22https%3A%2F%2Fmomentum.studio%22%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%20Address%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22momentumstudio%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F202%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
