### ISSUE TITLE
New company suggestion: `AZ Direct Österreich GmbH `

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#203]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "name": "AZ Direct Österreich GmbH ",
    "runs": [
        null
    ],
    "address": "Donau-City-Straße 6 \nAndromeda Tower \n1220 Wien",
    "phone": "+43 1 25965050",
    "fax": "+43 1 2591885",
    "email": "office@bertelsmann.at",
    "sources": [
        "https://www.az-direct.com/site/unternehmen/standorte/",
        "Art. 15 Auskunft der Österreichische Post AG",
        "https://github.com/datenanfragen/data/issues/203"
    ],
    "suggested-transport-medium": "letter",
    "slug": "az-direct-sterreich-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22name%22%3A%22AZ%20Direct%20%C3%96sterreich%20GmbH%20%22%2C%22runs%22%3A%5Bnull%5D%2C%22address%22%3A%22Donau-City-Stra%C3%9Fe%206%20%5CnAndromeda%20Tower%20%5Cn1220%20Wien%22%2C%22phone%22%3A%22%2B43%201%2025965050%22%2C%22fax%22%3A%22%2B43%201%202591885%22%2C%22email%22%3A%22office%40bertelsmann.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.az-direct.com%2Fsite%2Funternehmen%2Fstandorte%2F%22%2C%22Art.%2015%20Auskunft%20der%20%C3%96sterreichische%20Post%20AG%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F203%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22az-direct-sterreich-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
