### ISSUE TITLE
New company suggestion: `ProfileAddress Direktmarketing GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#204]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "ads"
    ],
    "name": "ProfileAddress Direktmarketing GmbH",
    "address": "Altmannsdorfer Strasse 311\n1230 Wien\nAustria",
    "phone": "+43 720 115229",
    "email": "auskunft@profileaddress.com",
    "web": "https://profileaddress.com/",
    "sources": [
        "https://profileaddress.com/impressum/",
        "https://github.com/datenanfragen/data/issues/204"
    ],
    "comments": [
        "Auskunft auch über https://profileaddress.com/auskunft/ möglich."
    ],
    "slug": "profileaddresscom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22ProfileAddress%20Direktmarketing%20GmbH%22%2C%22address%22%3A%22Altmannsdorfer%20Strasse%20311%5Cn1230%20Wien%5CnAustria%22%2C%22phone%22%3A%22%2B43%20720%20115229%22%2C%22email%22%3A%22auskunft%40profileaddress.com%22%2C%22web%22%3A%22https%3A%2F%2Fprofileaddress.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fprofileaddress.com%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F204%22%5D%2C%22comments%22%3A%5B%22Auskunft%20auch%20%C3%BCber%20https%3A%2F%2Fprofileaddress.com%2Fauskunft%2F%20m%C3%B6glich.%22%5D%2C%22slug%22%3A%22profileaddresscom%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
