### ISSUE TITLE
New company suggestion: `Moshbit GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#206]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "school"
    ],
    "name": "Moshbit GmbH",
    "runs": [
        "Studo",
        "Talto"
    ],
    "address": "Joanneumring 3 \n8010 Graz\nAustria ",
    "phone": "+43 664 8351081",
    "email": "datenschutz@moshbit.com",
    "web": "https://moshbit.com",
    "sources": [
        "https://moshbit.com/legalnotice.html",
        "https://studo.co/impressum",
        "https://studo.co/datenschutzerklaerung-website",
        "https://talto.com/impressum",
        "https://github.com/datenanfragen/data/issues/206"
    ],
    "slug": "moshbitcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22Moshbit%20GmbH%22%2C%22runs%22%3A%5B%22Studo%22%2C%22Talto%22%5D%2C%22address%22%3A%22Joanneumring%203%20%5Cn8010%20Graz%5CnAustria%20%22%2C%22phone%22%3A%22%2B43%20664%208351081%22%2C%22email%22%3A%22datenschutz%40moshbit.com%22%2C%22web%22%3A%22https%3A%2F%2Fmoshbit.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmoshbit.com%2Flegalnotice.html%22%2C%22https%3A%2F%2Fstudo.co%2Fimpressum%22%2C%22https%3A%2F%2Fstudo.co%2Fdatenschutzerklaerung-website%22%2C%22https%3A%2F%2Ftalto.com%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F206%22%5D%2C%22slug%22%3A%22moshbitcom%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
