### ISSUE TITLE
New company suggestion: `Bierwirth & Kluth Hotel Management GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#207]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Bierwirth & Kluth Hotel Management GmbH",
    "runs": [
        "Moxy Frankfurt East Frankfurt",
        "Courtyard by Marriott Wiesbaden-Nordenstadt Wiesbaden-Nordenstadt",
        "Gästeresidenz PelikanViertel Hannover",
        "Holiday Inn Hamburg City Nord Hamburg",
        "My4walls Serviced Apartments Hamburg",
        "München Airport Marriott Hotel München",
        "Courtyard by Marriott Oberpfaffenhofen Munich South",
        "Renaissance Wien Hotel Wien",
        "Courtyard by Marriott Wien Prater/Messe Wien",
        "Moxy Vienna Airport Wien"
    ],
    "address": "Bahnhofstraße 67\n65185 Wiesbaden\nGermany",
    "phone": "+49 611 4476000",
    "fax": "+49 611 44760044",
    "email": "datenschutz@bierwirth-kluth.de",
    "sources": [
        "http://www.bierwirth-kluth.de/de/datenschutz",
        "http://www.bierwirth-kluth.de/de/unsere-hotels",
        "https://www.hi-city-nord.de/de/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/207"
    ],
    "slug": "bierwirth-kluth-hotel-management-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Bierwirth%20%26%20Kluth%20Hotel%20Management%20GmbH%22%2C%22runs%22%3A%5B%22Moxy%20Frankfurt%20East%20Frankfurt%22%2C%22Courtyard%20by%20Marriott%20Wiesbaden-Nordenstadt%20Wiesbaden-Nordenstadt%22%2C%22G%C3%A4steresidenz%20PelikanViertel%20Hannover%22%2C%22Holiday%20Inn%20Hamburg%20City%20Nord%20Hamburg%22%2C%22My4walls%20Serviced%20Apartments%20Hamburg%22%2C%22M%C3%BCnchen%20Airport%20Marriott%20Hotel%20M%C3%BCnchen%22%2C%22Courtyard%20by%20Marriott%20Oberpfaffenhofen%20Munich%20South%22%2C%22Renaissance%20Wien%20Hotel%20Wien%22%2C%22Courtyard%20by%20Marriott%20Wien%20Prater%2FMesse%20Wien%22%2C%22Moxy%20Vienna%20Airport%20Wien%22%5D%2C%22address%22%3A%22Bahnhofstra%C3%9Fe%2067%5Cn65185%20Wiesbaden%5CnGermany%22%2C%22phone%22%3A%22%2B49%20611%204476000%22%2C%22fax%22%3A%22%2B49%20611%2044760044%22%2C%22email%22%3A%22datenschutz%40bierwirth-kluth.de%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.bierwirth-kluth.de%2Fde%2Fdatenschutz%22%2C%22http%3A%2F%2Fwww.bierwirth-kluth.de%2Fde%2Funsere-hotels%22%2C%22https%3A%2F%2Fwww.hi-city-nord.de%2Fde%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F207%22%5D%2C%22slug%22%3A%22bierwirth-kluth-hotel-management-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
