### ISSUE TITLE
New company suggestion: `Hamburger Hochbahn AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#208]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Hamburger Hochbahn AG",
    "address": "Steinstraße 20\n20095 Hamburg\nGermany",
    "phone": "+49 40 32880",
    "fax": "+49 40 326406",
    "email": "Datenschutzbeauftragter@hochbahn.de",
    "web": "https://www.hochbahn.de",
    "sources": [
        "https://www.hochbahn.de/hochbahn/hamburg/de/Home/Startseite/Datenschutz",
        "https://www.hochbahn.de/hochbahn/hamburg/de/Home/Startseite/Impressum",
        "https://github.com/datenanfragen/data/issues/208"
    ],
    "slug": "hochbahnde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Hamburger%20Hochbahn%20AG%22%2C%22address%22%3A%22Steinstra%C3%9Fe%2020%5Cn20095%20Hamburg%5CnGermany%22%2C%22phone%22%3A%22%2B49%2040%2032880%22%2C%22fax%22%3A%22%2B49%2040%20326406%22%2C%22email%22%3A%22Datenschutzbeauftragter%40hochbahn.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hochbahn.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hochbahn.de%2Fhochbahn%2Fhamburg%2Fde%2FHome%2FStartseite%2FDatenschutz%22%2C%22https%3A%2F%2Fwww.hochbahn.de%2Fhochbahn%2Fhamburg%2Fde%2FHome%2FStartseite%2FImpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F208%22%5D%2C%22slug%22%3A%22hochbahnde%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
