### ISSUE TITLE
New company suggestion: `BookMyShow`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#209]
The following suggestion was submitted through the website:

```
{
    "categories": [
        "entertainment"
    ],
    "name": "BookMyShow",
    "address": "Customer Grievance Officer\nBigtree Entertainment Private Limited.\nGround Floor, Wajeda House, Gulmohar Cross Road,\nAndheri West, Mumbai 400049",
    "email": "allears@bookmyshow.com",
    "web": "https://bookmyshow.com",
    "sources": [
        "https://bookmyshow.com/privacy",
        "https://github.com/datenanfragen/data/issues/209"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "For the purposes of the GDPR, our Customer Grievance Officer is also our Data Protection Officer (DPO).\nWe will respond to all requests, inquiries or concerns within a reasonable period.\nIf you are in the European Union, you can choose to instead lodge a complaint with your local Data Protection Authority (DPA). "
    ],
    "slug": "bookmyshowcom",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22BookMyShow%22%2C%22address%22%3A%22Customer%20Grievance%20Officer%5CnBigtree%20Entertainment%20Private%20Limited.%5CnGround%20Floor%2C%20Wajeda%20House%2C%20Gulmohar%20Cross%20Road%2C%5CnAndheri%20West%2C%20Mumbai%20400049%22%2C%22email%22%3A%22allears%40bookmyshow.com%22%2C%22web%22%3A%22https%3A%2F%2Fbookmyshow.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbookmyshow.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F209%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22For%20the%20purposes%20of%20the%20GDPR%2C%20our%20Customer%20Grievance%20Officer%20is%20also%20our%20Data%20Protection%20Officer%20(DPO).%5CnWe%20will%20respond%20to%20all%20requests%2C%20inquiries%20or%20concerns%20within%20a%20reasonable%20period.%5CnIf%20you%20are%20in%20the%20European%20Union%2C%20you%20can%20choose%20to%20instead%20lodge%20a%20complaint%20with%20your%20local%20Data%20Protection%20Authority%20(DPA).%20%22%5D%2C%22slug%22%3A%22bookmyshowcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
