### ISSUE TITLE
Suggested update for company `adobe`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#210]
The following suggestion was submitted through the website:

```
{
    "slug": "adobe",
    "relevant-countries": [
        "all"
    ],
    "name": "Adobe Systems Software Ireland Ltd.",
    "runs": [
        "Adobe Systems Inc.",
        "Behance (www.behance.net)",
        "Creative Cloud",
        "Document Cloud",
        "Adobe-ID"
    ],
    "address": "4–6 Riverwalk\nCity West Business Campus\nDublin 24\nIreland",
    "phone": "+353 1 242 6700",
    "fax": "+353 1 242 6711",
    "email": "privacy@adobe.com",
    "web": "https://www.adobe.com",
    "sources": [
        "https://www.adobe.com/privacy/policy.html",
        "https://www.adobe.com/legal/terms.html",
        "https://www.adobe.com/de/about-adobe/impressum.html",
        "https://github.com/datenanfragen/data/issues/210"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail",
            "type": "input"
        }
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Sending email to privacy@adobe.com results in this response:\n\nWe’re happy to help with your questions or concerns, and have a number of online resources to help answer and resolve common questions and issues below:\n\n \n\n    Find answers to most of your privacy questions in the Adobe Privacy Center.   \n    View and update your communications and marketing preferences.   \n    Learn about Adobe's student privacy practices.  \n\n \n\nIf you have other privacy questions or concerns not answered in the Privacy Center, you can complete our privacy inquiry form and we’ll follow up with you.\n\n \n\n \n\nThank you,\n\n \n\nThe Adobe Privacy Team\n\n \n\nNote: Please do not respond to this e-mail as this account is not monitored.\n\n \n\nimage002.jpg"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22adobe%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Adobe%20Systems%20Software%20Ireland%20Ltd.%22%2C%22runs%22%3A%5B%22Adobe%20Systems%20Inc.%22%2C%22Behance%20(www.behance.net)%22%2C%22Creative%20Cloud%22%2C%22Document%20Cloud%22%2C%22Adobe-ID%22%5D%2C%22address%22%3A%224%E2%80%936%20Riverwalk%5CnCity%20West%20Business%20Campus%5CnDublin%2024%5CnIreland%22%2C%22phone%22%3A%22%2B353%201%20242%206700%22%2C%22fax%22%3A%22%2B353%201%20242%206711%22%2C%22email%22%3A%22privacy%40adobe.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.adobe.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.adobe.com%2Fprivacy%2Fpolicy.html%22%2C%22https%3A%2F%2Fwww.adobe.com%2Flegal%2Fterms.html%22%2C%22https%3A%2F%2Fwww.adobe.com%2Fde%2Fabout-adobe%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F210%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22input%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Sending%20email%20to%20privacy%40adobe.com%20results%20in%20this%20response%3A%5Cn%5CnWe%E2%80%99re%20happy%20to%20help%20with%20your%20questions%20or%20concerns%2C%20and%20have%20a%20number%20of%20online%20resources%20to%20help%20answer%20and%20resolve%20common%20questions%20and%20issues%20below%3A%5Cn%5Cn%20%5Cn%5Cn%20%20%20%20Find%20answers%20to%20most%20of%20your%20privacy%20questions%20in%20the%20Adobe%20Privacy%20Center.%20%20%20%5Cn%20%20%20%20View%20and%20update%20your%20communications%20and%20marketing%20preferences.%20%20%20%5Cn%20%20%20%20Learn%20about%20Adobe's%20student%20privacy%20practices.%20%20%5Cn%5Cn%20%5Cn%5CnIf%20you%20have%20other%20privacy%20questions%20or%20concerns%20not%20answered%20in%20the%20Privacy%20Center%2C%20you%20can%20complete%20our%20privacy%20inquiry%20form%20and%20we%E2%80%99ll%20follow%20up%20with%20you.%5Cn%5Cn%20%5Cn%5Cn%20%5Cn%5CnThank%20you%2C%5Cn%5Cn%20%5Cn%5CnThe%20Adobe%20Privacy%20Team%5Cn%5Cn%20%5Cn%5CnNote%3A%20Please%20do%20not%20respond%20to%20this%20e-mail%20as%20this%20account%20is%20not%20monitored.%5Cn%5Cn%20%5Cn%5Cnimage002.jpg%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks for the note. I will update the email to `dsar@adobe.com` where the reply to my request came from.

**Comment by baltpeter** [comment]
But I will also add your note as a comment to the English record.
