### ISSUE TITLE
New company suggestion: `dirtlej GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#211]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "dirtlej GmbH",
    "address": "Am Kesselhaus 5\n79576 Weil am Rhein\nDeutschland",
    "sources": [
        "https://www.dirtlej.de",
        "https://github.com/datenanfragen/data/issues/211"
    ],
    "suggested-transport-medium": "email",
    "slug": "dirtlej-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22dirtlej%20GmbH%22%2C%22address%22%3A%22Am%20Kesselhaus%205%5Cn79576%20Weil%20am%20Rhein%5CnDeutschland%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dirtlej.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F211%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22dirtlej-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
