### ISSUE TITLE
New company suggestion: `IFTTT, Inc`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#212]
The following suggestion was submitted through the website:

```
{
    "categories": [
        "utility"
    ],
    "name": "IFTTT, Inc",
    "address": "923 Market Street, Suite #400, San Francisco, CA 94103",
    "phone": "+49 40 999993430",
    "fax": "+49 40 999993332",
    "email": "IFTTT@gdpr-rep.com",
    "web": "https://ifttt.com/",
    "sources": [
        "https://ifttt.com/terms",
        "https://github.com/datenanfragen/data/issues/212"
    ],
    "suggested-transport-medium": "email",
    "slug": "iftttcom",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22IFTTT%2C%20Inc%22%2C%22address%22%3A%22923%20Market%20Street%2C%20Suite%20%23400%2C%20San%20Francisco%2C%20CA%2094103%22%2C%22phone%22%3A%22%2B49%2040%20999993430%22%2C%22fax%22%3A%22%2B49%2040%20999993332%22%2C%22email%22%3A%22IFTTT%40gdpr-rep.com%22%2C%22web%22%3A%22https%3A%2F%2Fifttt.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fifttt.com%2Fterms%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F212%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22iftttcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
