### ISSUE TITLE
Suggested update for company `bookmyshow`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#213]
The following suggestion was submitted through the website:

```
{
    "slug": "bookmyshow",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "BookmyShow.com",
    "runs": [
        "Bigtree Entertainment Private Limited (\"Bigtree\")"
    ],
    "address": "c/o Bigtree Entertainment Private Limited\nGround Floor, Wajeda House\nGulmohar Cross Road\nAndheri West\nMumbai 400049\nIndia",
    "email": "allears@bookmyshow.com",
    "web": "https://bookmyshow.com",
    "sources": [
        "https://bookmyshow.com/privacy",
        "https://github.com/datenanfragen/data/issues/209",
        "https://bookmyshow.com/terms-and-conditions",
        "https://github.com/datenanfragen/data/issues/213"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bookmyshow%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22BookmyShow.com%22%2C%22runs%22%3A%5B%22Bigtree%20Entertainment%20Private%20Limited%20(%5C%22Bigtree%5C%22)%22%5D%2C%22address%22%3A%22c%2Fo%20Bigtree%20Entertainment%20Private%20Limited%5CnGround%20Floor%2C%20Wajeda%20House%5CnGulmohar%20Cross%20Road%5CnAndheri%20West%5CnMumbai%20400049%5CnIndia%22%2C%22email%22%3A%22allears%40bookmyshow.com%22%2C%22web%22%3A%22https%3A%2F%2Fbookmyshow.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbookmyshow.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F209%22%2C%22https%3A%2F%2Fbookmyshow.com%2Fterms-and-conditions%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F213%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
