### ISSUE TITLE
Add Adresskontor GmbH websites

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/data#2131]
Seems like they have a separate GDPR phone no for firmenliste. I updated the firmenliste record. The other companies would have to go in a new record.

_Originally posted by @mal-tee in https://github.com/datenanfragen/data/issues/2041#issuecomment-1445459060_

**Comment by baltpeter** [comment]
According to the privacy policies, they seem to share the same DPO. Can't we use that instead of having separate records?

Relevant for: https://github.com/datenanfragen/data/pull/2169

**Comment by mal-tee** [comment]
sure!
