### ISSUE TITLE
New company suggestion: `KlexHub UG (haftungsbeschränkt)`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#214]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "telecommunication",
        "commerce",
        "utility"
    ],
    "name": "KlexHub UG (haftungsbeschränkt)",
    "address": "Kurt-Schumacher-Str. 2\n89343 Jettingen-Scheppach",
    "phone": "08225 7989000",
    "fax": "08225 7989001",
    "email": "datenschutz@klexhub.com",
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "klexhub-ug-haftungsbeschrnkt",
    "sources": [
        "https://github.com/datenanfragen/data/issues/214"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22commerce%22%2C%22utility%22%5D%2C%22name%22%3A%22KlexHub%20UG%20(haftungsbeschr%C3%A4nkt)%22%2C%22address%22%3A%22Kurt-Schumacher-Str.%202%5Cn89343%20Jettingen-Scheppach%22%2C%22phone%22%3A%2208225%207989000%22%2C%22fax%22%3A%2208225%207989001%22%2C%22email%22%3A%22datenschutz%40klexhub.com%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22klexhub-ug-haftungsbeschrnkt%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F214%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
