### ISSUE TITLE
New company suggestion: `Greater Manchester Police`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#215]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "public body"
    ],
    "name": "Greater Manchester Police",
    "address": "GMP Headquarters \nCentral Park \nNorthampton Road \nManchester \nM40 5BP",
    "phone": "0121 559 6699 ",
    "email": "dataprotection@gmp.pnn.police.uk ",
    "web": "https://gmp.police.uk",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "gmppoliceuk",
    "sources": [
        "https://github.com/datenanfragen/data/issues/215"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Greater%20Manchester%20Police%22%2C%22address%22%3A%22GMP%20Headquarters%20%5CnCentral%20Park%20%5CnNorthampton%20Road%20%5CnManchester%20%5CnM40%205BP%22%2C%22phone%22%3A%220121%20559%206699%20%22%2C%22email%22%3A%22dataprotection%40gmp.pnn.police.uk%20%22%2C%22web%22%3A%22https%3A%2F%2Fgmp.police.uk%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22gmppoliceuk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F215%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
