### ISSUE TITLE
Suggested update for company `deliveroo-de`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#216]
The following suggestion was submitted through the website:

```
{
    "slug": "deliveroo-de",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Deliveroo Germany GmbH",
    "runs": [
        "Roofoods Limited"
    ],
    "address": "Unter den Linden 26-30\n10117 Berlin\nDeutschland",
    "email": "dpo@deliveroo.com",
    "web": "https://deliveroo.de",
    "sources": [
        "https://deliveroo.de/en/privacy",
        "https://github.com/datenanfragen/data/issues/216"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22deliveroo-de%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Deliveroo%20Germany%20GmbH%22%2C%22runs%22%3A%5B%22Roofoods%20Limited%22%5D%2C%22address%22%3A%22Unter%20den%20Linden%2026-30%5Cn10117%20Berlin%5CnDeutschland%22%2C%22email%22%3A%22dpo%40deliveroo.com%22%2C%22web%22%3A%22https%3A%2F%2Fdeliveroo.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdeliveroo.de%2Fen%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F216%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
