### ISSUE TITLE
New company suggestion: `Payback`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#217]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Payback",
    "address": "PAYBACK GmbH, Theresienhöhe 12, 80339 München",
    "phone": "089 / 540 20 80 20",
    "fax": "0180 / 50 55 108",
    "email": "datenschutz@payback.de",
    "web": "https://www.payback.de/",
    "required-elements": [
        {
            "desc": "Kundenummer",
            "type": "textarea",
            "optional": false
        },
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "paybackde",
    "sources": [
        "https://github.com/datenanfragen/data/issues/217"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Payback%22%2C%22address%22%3A%22PAYBACK%20GmbH%2C%20Theresienh%C3%B6he%2012%2C%2080339%20M%C3%BCnchen%22%2C%22phone%22%3A%22089%20%2F%20540%2020%2080%2020%22%2C%22fax%22%3A%220180%20%2F%2050%2055%20108%22%2C%22email%22%3A%22datenschutz%40payback.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.payback.de%2F%22%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Kundenummer%22%2C%22type%22%3A%22textarea%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22paybackde%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F217%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
