### ISSUE TITLE
New company suggestion: `HEROLD Business Data GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#218]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "name": "HEROLD Business Data GmbH",
    "address": "Guntramsdorfer Straße 105\n2340 Mödling\nÖsterreich",
    "phone": "+43 2236 4010",
    "fax": "+43 2236 4018",
    "email": "office@herold.at",
    "web": "https://www.herold.at",
    "sources": [
        "https://www.ichbinderherold.at/impressum",
        "UID ATU 57270679",
        "Firmenbuchnummer  FN 233171z",
        "https://github.com/datenanfragen/data/issues/218"
    ],
    "slug": "heroldat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22name%22%3A%22HEROLD%20Business%20Data%20GmbH%22%2C%22address%22%3A%22Guntramsdorfer%20Stra%C3%9Fe%20105%5Cn2340%20M%C3%B6dling%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%202236%204010%22%2C%22fax%22%3A%22%2B43%202236%204018%22%2C%22email%22%3A%22office%40herold.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.herold.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ichbinderherold.at%2Fimpressum%22%2C%22UID%20ATU%2057270679%22%2C%22Firmenbuchnummer%20%20FN%20233171z%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F218%22%5D%2C%22slug%22%3A%22heroldat%22%7D)**

**Comment by Ramblurr** [comment]
I submitted this, hah. I was quite surprised when I found it it opened a PR.

Anyways, Herold is/was a phone book company, but now mainly deals with selling business and personal data to marketers for unsolicited direct mailings.

**Comment by baltpeter** [comment]
Thanks for the submission and background info! Should be live on the site soon.
