### ISSUE TITLE
New company suggestion: `David Lloyd Leisure Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#219]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "health"
    ],
    "name": "David Lloyd Leisure Limited",
    "address": "The Hangar, Mosquito Way, Hatfield Business Park, Hatfield, Hertfordshire, AL10 9AX",
    "web": "www.davidlloyd.co.uk",
    "sources": [
        "https://www.davidlloyd.co.uk/policy/privacy-policy",
        "https://github.com/datenanfragen/data/issues/219"
    ],
    "slug": "david-lloyd-leisure-limited"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22David%20Lloyd%20Leisure%20Limited%22%2C%22address%22%3A%22The%20Hangar%2C%20Mosquito%20Way%2C%20Hatfield%20Business%20Park%2C%20Hatfield%2C%20Hertfordshire%2C%20AL10%209AX%22%2C%22web%22%3A%22www.davidlloyd.co.uk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.davidlloyd.co.uk%2Fpolicy%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F219%22%5D%2C%22slug%22%3A%22david-lloyd-leisure-limited%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
