### ISSUE TITLE
New company suggestion: `Morele.net Sp. z o.o.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#221]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "pl"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Morele.net Sp. z o.o.",
    "address": "ul. Fabryczna 20A\n31-553 Kraków",
    "email": "biuroodr@morele.net",
    "web": "www.morele.net",
    "sources": [
        "www.morele.net",
        "https://github.com/datenanfragen/data/issues/221"
    ],
    "slug": "morelenet-sp-z-oo"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22pl%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Morele.net%20Sp.%20z%20o.o.%22%2C%22address%22%3A%22ul.%20Fabryczna%2020A%5Cn31-553%20Krak%C3%B3w%22%2C%22email%22%3A%22biuroodr%40morele.net%22%2C%22web%22%3A%22www.morele.net%22%2C%22sources%22%3A%5B%22www.morele.net%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F221%22%5D%2C%22slug%22%3A%22morelenet-sp-z-oo%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
