### ISSUE TITLE
New company suggestion: `PVZ Pressevertriebszentrale GmbH & Co. KG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#222]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de",
        null
    ],
    "name": "PVZ Pressevertriebszentrale GmbH & Co. KG",
    "address": "z. Hd. Datenschutzbeauftragter\nBahndamm 9\n23617 Stockelsdorf",
    "phone": "0451 / 49 06 600",
    "fax": "0451 / 49 06 670",
    "email": "info@pvz.de",
    "web": "www.pvz.de",
    "sources": [
        "http://www.pvz.de/impressum.html",
        "http://www.pvz.de/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/222"
    ],
    "needs-id-document": false,
    "slug": "pvz-pressevertriebszentrale-gmbh-co-kg"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%2Cnull%5D%2C%22name%22%3A%22PVZ%20Pressevertriebszentrale%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22z.%20Hd.%20Datenschutzbeauftragter%5CnBahndamm%209%5Cn23617%20Stockelsdorf%22%2C%22phone%22%3A%220451%20%2F%2049%2006%20600%22%2C%22fax%22%3A%220451%20%2F%2049%2006%20670%22%2C%22email%22%3A%22info%40pvz.de%22%2C%22web%22%3A%22www.pvz.de%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.pvz.de%2Fimpressum.html%22%2C%22http%3A%2F%2Fwww.pvz.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F222%22%5D%2C%22needs-id-document%22%3Afalse%2C%22slug%22%3A%22pvz-pressevertriebszentrale-gmbh-co-kg%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
