### ISSUE TITLE
New company suggestion: `VIACTIV Krankenkasse`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#223]
The following suggestion was submitted through the website:

```
{
    "name": "VIACTIV Krankenkasse",
    "address": "Universitätsstr. 43\n44789 Bochum",
    "phone": "0800-2221211 (VIACTIV Krankenkasse) 0234-479 2799 (Datenschutzbeauftragter)",
    "email": "service@viactiv.de, datenschutz@viactiv.de",
    "web": "https://www.viactiv.de/",
    "sources": [
        "https://www.viactiv.de/datenschutz, https://de.wikipedia.org/wiki/Viactiv_BKK",
        "https://github.com/datenanfragen/data/issues/223"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "input"
        },
        {
            "desc": "Vorname",
            "type": "input"
        },
        {
            "desc": "Straße",
            "type": "input"
        },
        {
            "desc": "PLZ",
            "type": "input"
        },
        {
            "desc": "Ort",
            "type": "input"
        },
        {
            "type": "input"
        }
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "letter",
    "slug": "viactivde",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22VIACTIV%20Krankenkasse%22%2C%22address%22%3A%22Universit%C3%A4tsstr.%2043%5Cn44789%20Bochum%22%2C%22phone%22%3A%220800-2221211%20(VIACTIV%20Krankenkasse)%200234-479%202799%20(Datenschutzbeauftragter)%22%2C%22email%22%3A%22service%40viactiv.de%2C%20datenschutz%40viactiv.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.viactiv.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.viactiv.de%2Fdatenschutz%2C%20https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FViactiv_BKK%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F223%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22input%22%7D%2C%7B%22desc%22%3A%22Vorname%22%2C%22type%22%3A%22input%22%7D%2C%7B%22desc%22%3A%22Stra%C3%9Fe%22%2C%22type%22%3A%22input%22%7D%2C%7B%22desc%22%3A%22PLZ%22%2C%22type%22%3A%22input%22%7D%2C%7B%22desc%22%3A%22Ort%22%2C%22type%22%3A%22input%22%7D%2C%7B%22type%22%3A%22input%22%7D%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22viactivde%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
