### ISSUE TITLE
Suggested update for company `welt-de`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#224]
The following suggestion was submitted through the website:

```
{
    "slug": "welt-de",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "WELT",
    "runs": [
        "WELT Digital",
        "FOODBARN (www.foodbarn.com)",
        "WELT Kompakt",
        "WELT am Sonntag",
        "PS WELT",
        "WELT-bietet.de (www.welt-bietet.de)",
        "ICONIST"
    ],
    "address": "c/o Axel Springer SE\nAxel-Springer-Straße 65\n10888 Berlin\nDeutschland",
    "phone": "+49 30 25910",
    "fax": "+49 30 259171606",
    "email": "datenschutz@welt.de",
    "web": "https://www.welt.de/",
    "sources": [
        "https://www.welt.de/services/article157550705/Datenschutzerklaerung-WELT-DIGITAL.html",
        "https://www.welt.de/services/article7893735/Impressum.html",
        "https://github.com/datenanfragen/data/issues/224"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22welt-de%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22WELT%22%2C%22runs%22%3A%5B%22WELT%20Digital%22%2C%22FOODBARN%20(www.foodbarn.com)%22%2C%22WELT%20Kompakt%22%2C%22WELT%20am%20Sonntag%22%2C%22PS%20WELT%22%2C%22WELT-bietet.de%20(www.welt-bietet.de)%22%2C%22ICONIST%22%5D%2C%22address%22%3A%22c%2Fo%20Axel%20Springer%20SE%5CnAxel-Springer-Stra%C3%9Fe%2065%5Cn10888%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2025910%22%2C%22fax%22%3A%22%2B49%2030%20259171606%22%2C%22email%22%3A%22datenschutz%40welt.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.welt.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.welt.de%2Fservices%2Farticle157550705%2FDatenschutzerklaerung-WELT-DIGITAL.html%22%2C%22https%3A%2F%2Fwww.welt.de%2Fservices%2Farticle7893735%2FImpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F224%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you but I don't see any changes to the current record.
