### ISSUE TITLE
New company suggestion: `Alternative für Deutschland Mecklenburg-Vorpommern`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#225]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "political party"
    ],
    "name": "Alternative für Deutschland Mecklenburg-Vorpommern",
    "address": "Woldegker Straße 27\n17033 Neubrandenburg",
    "phone": "0395 36967312",
    "fax": "0395 36967313",
    "email": "info@afd-mv.de",
    "web": "afd-mv.de",
    "sources": [
        "https://afd-mv.de/partei/geschaeftsstelle/",
        "https://github.com/datenanfragen/data/issues/225"
    ],
    "slug": "alternative-fr-deutschland-mecklenburg-vorpommern"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22political%20party%22%5D%2C%22name%22%3A%22Alternative%20f%C3%BCr%20Deutschland%20Mecklenburg-Vorpommern%22%2C%22address%22%3A%22Woldegker%20Stra%C3%9Fe%2027%5Cn17033%20Neubrandenburg%22%2C%22phone%22%3A%220395%2036967312%22%2C%22fax%22%3A%220395%2036967313%22%2C%22email%22%3A%22info%40afd-mv.de%22%2C%22web%22%3A%22afd-mv.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fafd-mv.de%2Fpartei%2Fgeschaeftsstelle%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F225%22%5D%2C%22slug%22%3A%22alternative-fr-deutschland-mecklenburg-vorpommern%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
