### ISSUE TITLE
New company suggestion: `ERGO Direkt AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#226]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "insurance"
    ],
    "name": "ERGO Direkt AG",
    "runs": [
        "ERGO Vorsorge Lebensversicherung AG",
        "ERGO Direkt Versicherung AG",
        "ERGO Krankenversicherung AG",
        "MEAG Munich ERGO AssetManagement GmbH",
        "ERGO Versicherung AG",
        "Victoria Lebensversicherung AG",
        "DKV Deutsche Krankenversicherung AG",
        "ERGO Reiseversicherung AG",
        "ERGO Lebensversicherung AG"
    ],
    "address": "ERGO Direkt AG\nKarl-Martell-Str. 60\n90344 Nürnberg",
    "email": "datenschutz.beauftragter@ergo.de",
    "web": "https://www.ergo.de/",
    "sources": [
        "https://www.ergo.de/de/Service/Datenschutz",
        "https://github.com/datenanfragen/data/issues/226"
    ],
    "slug": "ergode"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22ERGO%20Direkt%20AG%22%2C%22runs%22%3A%5B%22ERGO%20Vorsorge%20Lebensversicherung%20AG%22%2C%22ERGO%20Direkt%20Versicherung%20AG%22%2C%22ERGO%20Krankenversicherung%20AG%22%2C%22MEAG%20Munich%20ERGO%20AssetManagement%20GmbH%22%2C%22ERGO%20Versicherung%20AG%22%2C%22Victoria%20Lebensversicherung%20AG%22%2C%22DKV%20Deutsche%20Krankenversicherung%20AG%22%2C%22ERGO%20Reiseversicherung%20AG%22%2C%22ERGO%20Lebensversicherung%20AG%22%5D%2C%22address%22%3A%22ERGO%20Direkt%20AG%5CnKarl-Martell-Str.%2060%5Cn90344%20N%C3%BCrnberg%22%2C%22email%22%3A%22datenschutz.beauftragter%40ergo.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ergo.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ergo.de%2Fde%2FService%2FDatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F226%22%5D%2C%22slug%22%3A%22ergode%22%7D)**

**Comment by baltpeter** [comment]
Thanks, I will merge this into our existing ERGO record.
