### ISSUE TITLE
New company suggestion: `VGN Verkehrsbund Groß­raum Nürn­berg GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#227]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "VGN Verkehrsbund Groß­raum Nürn­berg GmbH",
    "runs": [
        "VAG Verkehrs-Aktiengesellschaft"
    ],
    "address": "Rothen­burger Straße 9\n90443 Nürn­berg\nDeutschland",
    "phone": "+49 911 270750",
    "fax": "+49 911 2707550",
    "email": "info@vgn.de",
    "web": "https://www.vgn.de",
    "sources": [
        "https://www.vgn.de/datenschutz/",
        "https://www.vag.de/datenschutz/",
        "https://github.com/datenanfragen/data/issues/227"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Geburtsdatum",
            "type": "birthdate"
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ],
    "slug": "vgnde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22VGN%20Verkehrsbund%20Gro%C3%9F%C2%ADraum%20N%C3%BCrn%C2%ADberg%20GmbH%22%2C%22runs%22%3A%5B%22VAG%20Verkehrs-Aktiengesellschaft%22%5D%2C%22address%22%3A%22Rothen%C2%ADburger%20Stra%C3%9Fe%209%5Cn90443%20N%C3%BCrn%C2%ADberg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20911%20270750%22%2C%22fax%22%3A%22%2B49%20911%202707550%22%2C%22email%22%3A%22info%40vgn.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vgn.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.vgn.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.vag.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F227%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Geburtsdatum%22%2C%22type%22%3A%22birthdate%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%5D%2C%22slug%22%3A%22vgnde%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
