### ISSUE TITLE
Implement all_fields_empty flag in all request templates

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#238]
Over in datenanfragen/website#94, @ggangix helpfully implemented only adding fields with actual content to the letters.

If it turns out that the user hasn't added any fields, we also want to remove the `I am including the following information necessary to identify me:` line.  
To do so, we are using the `all_fields_empty` flag. This flag needs to be added to all templates.

Essentially, this means that the templates will now have the following line instead:

```
[all_fields_empty>
I am including the following information necessary to identify me:
{id_data}]
```

…or similarly for different languages…

**Comment by yonash2** [comment]
hi, picking this up

**Comment by baltpeter** [comment]
Great, thank you.

**Comment by molnarjani** [comment]
Raised a PR:
https://github.com/datenanfragen/data/pull/239/commits/32a71ec34f6586505916dd15113a6d2d6bbf0347
