### ISSUE TITLE
New company suggestion: `Breuninger GmbH & Co`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#241]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Breuninger GmbH & Co",
    "address": "E.Breuninger GmbH & Co\nMarktstrasse 1-3\n70173 Stuttgart",
    "phone": "0711 / 211 – 0",
    "fax": "0711 / 211 - 3053",
    "email": "datenschutz@breuninger.de",
    "web": "https://www.breuninger.com/de/",
    "sources": [
        "https://www.breuninger.com/de/service/datenschutz/",
        "https://github.com/datenanfragen/data/issues/241"
    ],
    "slug": "breuningercom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Breuninger%20GmbH%20%26%20Co%22%2C%22address%22%3A%22E.Breuninger%20GmbH%20%26%20Co%5CnMarktstrasse%201-3%5Cn70173%20Stuttgart%22%2C%22phone%22%3A%220711%20%2F%20211%20%E2%80%93%200%22%2C%22fax%22%3A%220711%20%2F%20211%20-%203053%22%2C%22email%22%3A%22datenschutz%40breuninger.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.breuninger.com%2Fde%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.breuninger.com%2Fde%2Fservice%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F241%22%5D%2C%22slug%22%3A%22breuningercom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
