### ISSUE TITLE
Remove `.txt` from the custom access templates in all records

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#244]
Our schema allows declaring a custom access template using the `custom-access-template` property.

Previously, this had to include the `.txt` file extension. That is not the case anymore. To simplify our code, we should remove the `.txt` from all records.

For example, this means that in [this file](https://github.com/datenanfragen/data/blob/master/companies/adara.json#L19) the line

```
"custom-access-template": "access-tracking.txt",
```

has to become

```
"custom-access-template": "access-tracking",
```

This has to be done for all records in the `companies` folder.

**Comment by Ananthavijay** [comment]
I will take this

**Comment by baltpeter** [comment]
Thank you!

**Comment by PaulEvans8669** [comment]
Can send a PR, but will leave the work to @Ananthavijay

**Comment by baltpeter** [comment]
Thanks for the offer, @PaulEvans8669. I'll get back to you if needed.

**Comment by PaulEvans8669** [comment]
By the way, I found a non UTF-8 char in file `data/companies/1plusx.json`

`"address": "Eichenstrasse 2\n8808 Pfäffikon\nSwitzerland",` (line 10)

`ä` should be `\u00e4`
I only came accross that problem once, but I didn't go through every file.

**Comment by baltpeter** [comment]
Thanks for the note, I do think that is OK though.

As per the JSON RFC (see [here](https://stackoverflow.com/a/4908960)), apart from a few exceptions (quotation mark, reverse solidus, and the control characters (U+0000 through U+001F)), Unicode characters don't need to be escaped and `ä` is a Unicode char.

This also works fine with both Hugo (see the [company detail pages](https://www.datarequests.org/company/1plusx)) and JS (see the [generator](https://www.datarequests.org/generator?company=1plusx)). Or do you know of a case where this would fail?

**Comment by Ananthavijay** [comment]
What is this @baltpeter
