### ISSUE TITLE
New company suggestion: `Unser Ö-Bonus Club GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#254]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "ads",
        "commerce"
    ],
    "name": "Unser Ö-Bonus Club GmbH",
    "address": "IZ NÖ-Süd Straße 3, Objekt 16\n2355 Wiener Neudorf \nÖsterreich",
    "phone": "+43 1 3865000",
    "email": " datenschutz@joe-club.at",
    "web": "https://www.joe-club.at/",
    "sources": [
        "https://www.joe-club.at/datenschutz",
        "https://www.joe-club.at/datenschutzerklärungweb",
        "https://www.joe-club.at/impressum",
        "https://github.com/datenanfragen/data/issues/254"
    ],
    "suggested-transport-medium": "letter",
    "comments": [
        "Beteiligungsverhältnisse: 100% REWE International Dienstleistungsgesellschaft m.b.H., Gesellschafterin der REWE International Dienstleistungsgesellschaft m.b.H.: REWE International AG"
    ],
    "slug": "joe-clubat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22commerce%22%5D%2C%22name%22%3A%22Unser%20%C3%96-Bonus%20Club%20GmbH%22%2C%22address%22%3A%22IZ%20N%C3%96-S%C3%BCd%20Stra%C3%9Fe%203%2C%20Objekt%2016%5Cn2355%20Wiener%20Neudorf%20%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%201%203865000%22%2C%22email%22%3A%22%20datenschutz%40joe-club.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.joe-club.at%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.joe-club.at%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.joe-club.at%2Fdatenschutzerkl%C3%A4rungweb%22%2C%22https%3A%2F%2Fwww.joe-club.at%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F254%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22Beteiligungsverh%C3%A4ltnisse%3A%20100%25%20REWE%20International%20Dienstleistungsgesellschaft%20m.b.H.%2C%20Gesellschafterin%20der%20REWE%20International%20Dienstleistungsgesellschaft%20m.b.H.%3A%20REWE%20International%20AG%22%5D%2C%22slug%22%3A%22joe-clubat%22%7D)**

**Comment by baltpeter** [comment]
Thank you!

The comment seems more suited to the comments on the website rather than the notes on the record (the terminology is confusing, I know), so I'll move that there once merged.
