### ISSUE TITLE
New company suggestion: `Austrian Airlines AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#255]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at",
        "de",
        "ch"
    ],
    "categories": [
        "travel"
    ],
    "name": "Austrian Airlines AG",
    "address": "Rechtsbüro - Datenschutz\nOffice Park 2\nPostbox 100\n1300 Wien-Flughafen\nÖsterreich",
    "web": "https://www.austrian.com",
    "sources": [
        "https://www.austrian.com/Info/LegalRegulations/dataprotection_overview.aspx?sc_lang=de&cc=DE",
        "https://www.austrian.com/Info/LegalRegulations/DataProtection.aspx?sc_lang=de&cc=DE",
        "https://www.austrian.com/Info/LegalRegulations/profilelegal_dataprotection.aspx?sc_lang=de&cc=DE",
        "https://github.com/datenanfragen/data/issues/255"
    ],
    "needs-id-document": true,
    "comments": [
        "Bietet auch ein Formular für Betroffenenrechte an: https://www.austrian.com/Info/LegalRegulations/dataprotection_contact_form.aspx?sc_lang=de&cc=DE "
    ],
    "slug": "austriancom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%2C%22de%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Austrian%20Airlines%20AG%22%2C%22address%22%3A%22Rechtsb%C3%BCro%20-%20Datenschutz%5CnOffice%20Park%202%5CnPostbox%20100%5Cn1300%20Wien-Flughafen%5Cn%C3%96sterreich%22%2C%22web%22%3A%22https%3A%2F%2Fwww.austrian.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.austrian.com%2FInfo%2FLegalRegulations%2Fdataprotection_overview.aspx%3Fsc_lang%3Dde%26cc%3DDE%22%2C%22https%3A%2F%2Fwww.austrian.com%2FInfo%2FLegalRegulations%2FDataProtection.aspx%3Fsc_lang%3Dde%26cc%3DDE%22%2C%22https%3A%2F%2Fwww.austrian.com%2FInfo%2FLegalRegulations%2Fprofilelegal_dataprotection.aspx%3Fsc_lang%3Dde%26cc%3DDE%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F255%22%5D%2C%22needs-id-document%22%3Atrue%2C%22comments%22%3A%5B%22Bietet%20auch%20ein%20Formular%20f%C3%BCr%20Betroffenenrechte%20an%3A%20https%3A%2F%2Fwww.austrian.com%2FInfo%2FLegalRegulations%2Fdataprotection_contact_form.aspx%3Fsc_lang%3Dde%26cc%3DDE%20%22%5D%2C%22slug%22%3A%22austriancom%22%7D)**

**Comment by baltpeter** [comment]
Thank you!

Just a quick note: We automatically add an 'Attn:' line on the website, so the "Rechtsbüro - Datenschutz" doesn't need to be included in the record, see #73.
