### ISSUE TITLE
New company suggestion: `Miles & More GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#256]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "travel",
        "ads",
        "finance"
    ],
    "name": "Miles & More GmbH",
    "address": "MAC Main Airport Center, Unterschweinstiege 8\n60549 Frankfurt/Main\nDeutschland",
    "email": " datenschutz@dlh.de",
    "web": "https://www.miles-and-more.com",
    "sources": [
        "https://www.miles-and-more.com/de/de/general-information/privacy-statement.html",
        "https://www.miles-and-more.com/de/de/general-information/privacy-statement/privacy-statement-of-the-miles-and-more-programme.html",
        "https://www.miles-and-more.com/de/de/general-information/privacy-statement/data-protection-policy-of-the-miles-and-more-website-app-communication-media.html",
        "https://www.miles-and-more.com/de/de/general-information/imprint.html",
        "https://www.miles-and-more.com/de/de/general-information/co-editor-miles-and-more.html",
        "https://github.com/datenanfragen/data/issues/256"
    ],
    "comments": [
        "Als Kontaktmöglichkeit wird nur das Online Kontaktformular erwähnt. Die E-Mail Adresse ist der Konzernweite Datenschutzbeauftragter"
    ],
    "slug": "miles-and-morecom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22travel%22%2C%22ads%22%2C%22finance%22%5D%2C%22name%22%3A%22Miles%20%26%20More%20GmbH%22%2C%22address%22%3A%22MAC%20Main%20Airport%20Center%2C%20Unterschweinstiege%208%5Cn60549%20Frankfurt%2FMain%5CnDeutschland%22%2C%22email%22%3A%22%20datenschutz%40dlh.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.miles-and-more.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.miles-and-more.com%2Fde%2Fde%2Fgeneral-information%2Fprivacy-statement.html%22%2C%22https%3A%2F%2Fwww.miles-and-more.com%2Fde%2Fde%2Fgeneral-information%2Fprivacy-statement%2Fprivacy-statement-of-the-miles-and-more-programme.html%22%2C%22https%3A%2F%2Fwww.miles-and-more.com%2Fde%2Fde%2Fgeneral-information%2Fprivacy-statement%2Fdata-protection-policy-of-the-miles-and-more-website-app-communication-media.html%22%2C%22https%3A%2F%2Fwww.miles-and-more.com%2Fde%2Fde%2Fgeneral-information%2Fimprint.html%22%2C%22https%3A%2F%2Fwww.miles-and-more.com%2Fde%2Fde%2Fgeneral-information%2Fco-editor-miles-and-more.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F256%22%5D%2C%22comments%22%3A%5B%22Als%20Kontaktm%C3%B6glichkeit%20wird%20nur%20das%20Online%20Kontaktformular%20erw%C3%A4hnt.%20Die%20E-Mail%20Adresse%20ist%20der%20Konzernweite%20Datenschutzbeauftragter%22%5D%2C%22slug%22%3A%22miles-and-morecom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
