### ISSUE TITLE
New company suggestion: `Schalke 04`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#257]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Schalke 04",
    "runs": [
        "https://store.schalke04.de/"
    ],
    "address": "FC Gelsenkirchen-Schalke 04 e.V.\nErnst-Kuzorra-Weg 1\n45891 Gelsenkirchen\n",
    "sources": [
        "https://store.schalke04.de/impressum",
        "https://store.schalke04.de/datenschutzerklaerung",
        "https://github.com/datenanfragen/data/issues/257"
    ],
    "slug": "schalke-04"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Schalke%2004%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fstore.schalke04.de%2F%22%5D%2C%22address%22%3A%22FC%20Gelsenkirchen-Schalke%2004%20e.V.%5CnErnst-Kuzorra-Weg%201%5Cn45891%20Gelsenkirchen%5Cn%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fstore.schalke04.de%2Fimpressum%22%2C%22https%3A%2F%2Fstore.schalke04.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F257%22%5D%2C%22slug%22%3A%22schalke-04%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
