### ISSUE TITLE
New company suggestion: `Weingarten`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#258]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Weingarten",
    "address": "Weingarten GmbH & Co. KG\nFriesenplatz 19\n50672 Köln\nDeutschland",
    "web": "https://www.weingarten-grosse-groessen.de/",
    "sources": [
        "https://www.weingarten-grosse-groessen.de/Datenschutz/",
        "https://www.weingarten-grosse-groessen.de/Impressum/",
        "https://github.com/datenanfragen/data/issues/258"
    ],
    "slug": "weingarten-grosse-groessende"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Weingarten%22%2C%22address%22%3A%22Weingarten%20GmbH%20%26%20Co.%20KG%5CnFriesenplatz%2019%5Cn50672%20K%C3%B6ln%5CnDeutschland%22%2C%22web%22%3A%22https%3A%2F%2Fwww.weingarten-grosse-groessen.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.weingarten-grosse-groessen.de%2FDatenschutz%2F%22%2C%22https%3A%2F%2Fwww.weingarten-grosse-groessen.de%2FImpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F258%22%5D%2C%22slug%22%3A%22weingarten-grosse-groessende%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
