### ISSUE TITLE
New company suggestion: `Buchbinder`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#259]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Buchbinder",
    "address": "Carpartner Nord GmbH\n\nKulmbacher Straße 8-10\n93057 Regensburg",
    "web": "https://www.buchbinder.de",
    "sources": [
        "https://www.buchbinder.de/de/weitere-informationen/impressum/",
        "https://www.buchbinder.de/de/weitere-informationen/datenschutz/",
        "https://github.com/datenanfragen/data/issues/259"
    ],
    "slug": "buchbinderde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Buchbinder%22%2C%22address%22%3A%22Carpartner%20Nord%20GmbH%5Cn%5CnKulmbacher%20Stra%C3%9Fe%208-10%5Cn93057%20Regensburg%22%2C%22web%22%3A%22https%3A%2F%2Fwww.buchbinder.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.buchbinder.de%2Fde%2Fweitere-informationen%2Fimpressum%2F%22%2C%22https%3A%2F%2Fwww.buchbinder.de%2Fde%2Fweitere-informationen%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F259%22%5D%2C%22slug%22%3A%22buchbinderde%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
