### ISSUE TITLE
New company suggestion: `DriveNow`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#260]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "DriveNow",
    "address": "DriveNow GmbH & Co. KG. \n\nSeidlstraße 26\n80335 Munich",
    "web": "https://www.drive-now.com/de/de",
    "sources": [
        "https://www.drive-now.com/de/de/legal-notice",
        "https://www.drive-now.com/de/de/privacy",
        "https://github.com/datenanfragen/data/issues/260"
    ],
    "slug": "drive-nowcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22DriveNow%22%2C%22address%22%3A%22DriveNow%20GmbH%20%26%20Co.%20KG.%20%5Cn%5CnSeidlstra%C3%9Fe%2026%5Cn80335%20Munich%22%2C%22web%22%3A%22https%3A%2F%2Fwww.drive-now.com%2Fde%2Fde%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.drive-now.com%2Fde%2Fde%2Flegal-notice%22%2C%22https%3A%2F%2Fwww.drive-now.com%2Fde%2Fde%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F260%22%5D%2C%22slug%22%3A%22drive-nowcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
