### ISSUE TITLE
New company suggestion: `Konstantin Primbas e.K.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#261]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health"
    ],
    "name": "Konstantin Primbas e.K.",
    "runs": [
        "APONEO – Mehr als Apotheke"
    ],
    "address": "APONEO – Mehr als Apotheke\nKonstantin Primbas e.K.\nPlauener Str. 163-165\n13053 Berlin",
    "web": "https://www.aponeo.de",
    "sources": [
        "https://www.aponeo.de/informationen/rechtliches/impressum/",
        "https://www.aponeo.de/informationen/rechtliches/datenschutz/",
        "https://github.com/datenanfragen/data/issues/261"
    ],
    "slug": "aponeode"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Konstantin%20Primbas%20e.K.%22%2C%22runs%22%3A%5B%22APONEO%20%E2%80%93%20Mehr%20als%20Apotheke%22%5D%2C%22address%22%3A%22APONEO%20%E2%80%93%20Mehr%20als%20Apotheke%5CnKonstantin%20Primbas%20e.K.%5CnPlauener%20Str.%20163-165%5Cn13053%20Berlin%22%2C%22web%22%3A%22https%3A%2F%2Fwww.aponeo.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.aponeo.de%2Finformationen%2Frechtliches%2Fimpressum%2F%22%2C%22https%3A%2F%2Fwww.aponeo.de%2Finformationen%2Frechtliches%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F261%22%5D%2C%22slug%22%3A%22aponeode%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
