### ISSUE TITLE
New company suggestion: `Blizzard Entertainment SAS`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#265]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Blizzard Entertainment SAS",
    "address": "Blizzard Entertainment SAS\nTSA 60001\n78008 Versailles CEDEX\nFrance ",
    "email": "DPO@blizzard.com",
    "web": "www.blizzard.com",
    "sources": [
        "https://www.blizzard.com/de-de/company/about/contact.html",
        "https://github.com/datenanfragen/data/issues/265"
    ],
    "suggested-transport-medium": "email",
    "slug": "blizzard-entertainment-sas"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Blizzard%20Entertainment%20SAS%22%2C%22address%22%3A%22Blizzard%20Entertainment%20SAS%5CnTSA%2060001%5Cn78008%20Versailles%20CEDEX%5CnFrance%20%22%2C%22email%22%3A%22DPO%40blizzard.com%22%2C%22web%22%3A%22www.blizzard.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.blizzard.com%2Fde-de%2Fcompany%2Fabout%2Fcontact.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F265%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22blizzard-entertainment-sas%22%7D)**

**Comment by baltpeter** [comment]
Good one, thank you!
