### ISSUE TITLE
New company suggestion: `Bernstein Bank`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#266]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "it",
        "de",
        "gb",
        "pl",
        "ru"
    ],
    "categories": [
        "finance"
    ],
    "name": "Bernstein Bank",
    "address": "Maximilianstr. 13 - 80539 Munich - Germany",
    "phone": "+49 89 215431034",
    "fax": "+49 89 215431099",
    "email": "service@bernstein-bank.com",
    "web": "https://www.bernstein-bank.com",
    "sources": [
        "https://www.bernstein-bank.com/service/#contact",
        "https://github.com/datenanfragen/data/issues/266"
    ],
    "suggested-transport-medium": "email",
    "slug": "bernstein-bankcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22it%22%2C%22de%22%2C%22gb%22%2C%22pl%22%2C%22ru%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Bernstein%20Bank%22%2C%22address%22%3A%22Maximilianstr.%2013%20-%2080539%20Munich%20-%20Germany%22%2C%22phone%22%3A%22%2B49%2089%20215431034%22%2C%22fax%22%3A%22%2B49%2089%20215431099%22%2C%22email%22%3A%22service%40bernstein-bank.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bernstein-bank.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bernstein-bank.com%2Fservice%2F%23contact%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F266%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22bernstein-bankcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
