### ISSUE TITLE
New company suggestion: `PAYBACK GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#269]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "addresses",
        "ads"
    ],
    "name": "PAYBACK GmbH",
    "address": "PAYBACK GmbH\nTheresienhöhe 12\n80339 München",
    "email": "pb_gmbh@PAYBACK.net",
    "web": "https://www.payback.de",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/269"
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "letter",
    "slug": "paybackde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%2C%22ads%22%5D%2C%22name%22%3A%22PAYBACK%20GmbH%22%2C%22address%22%3A%22PAYBACK%20GmbH%5CnTheresienh%C3%B6he%2012%5Cn80339%20M%C3%BCnchen%22%2C%22email%22%3A%22pb_gmbh%40PAYBACK.net%22%2C%22web%22%3A%22https%3A%2F%2Fwww.payback.de%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F269%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22paybackde%22%7D)**

**Comment by baltpeter** [comment]
Thanks but we already have this record for Payback: https://www.datarequests.org/company/payback
