### ISSUE TITLE
New company suggestion: ` Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#273]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "school"
    ],
    "name": " Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)",
    "address": "Schloßplatz 4\n91054 Erlangen ",
    "phone": "+49 9131 8525860",
    "email": "norbert.gaertner@fau.de",
    "web": "https://www.fau.de",
    "sources": [
        "https://www.fau.de/fau/leitung-und-gremien/gremien-und-beauftragte/beauftragte/datenschutzbeauftragter/",
        "https://www.fau.de/impressum/",
        "https://github.com/datenanfragen/data/issues/273"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        }
    ],
    "slug": "faude"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22%20Friedrich-Alexander-Universit%C3%A4t%20Erlangen-N%C3%BCrnberg%20(FAU)%22%2C%22address%22%3A%22Schlo%C3%9Fplatz%204%5Cn91054%20Erlangen%20%22%2C%22phone%22%3A%22%2B49%209131%208525860%22%2C%22email%22%3A%22norbert.gaertner%40fau.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fau.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fau.de%2Ffau%2Fleitung-und-gremien%2Fgremien-und-beauftragte%2Fbeauftragte%2Fdatenschutzbeauftragter%2F%22%2C%22https%3A%2F%2Fwww.fau.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F273%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%5D%2C%22slug%22%3A%22faude%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
