### ISSUE TITLE
Suggested update for company `imgur`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#275]
The following suggestion was submitted through the website:

```
{
    "slug": "imgur",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "social media",
        "entertainment"
    ],
    "name": "Imgur Inc.",
    "address": "415 Jackson Street\n2nd Floor\nSuite 200\nSan Francisco\nCA 94111\nUnited States of America",
    "email": "privacy@imgur.com",
    "web": "https://imgur.com/",
    "sources": [
        "https://imgur.com/privacy",
        "https://imgur.com/tos",
        "https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapid=252810438",
        "https://github.com/datenanfragen/data/issues/275"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail",
            "type": "input"
        }
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22imgur%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%2C%22entertainment%22%5D%2C%22name%22%3A%22Imgur%20Inc.%22%2C%22address%22%3A%22415%20Jackson%20Street%5Cn2nd%20Floor%5CnSuite%20200%5CnSan%20Francisco%5CnCA%2094111%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22privacy%40imgur.com%22%2C%22web%22%3A%22https%3A%2F%2Fimgur.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fimgur.com%2Fprivacy%22%2C%22https%3A%2F%2Fimgur.com%2Ftos%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fresearch%2Fstocks%2Fprivate%2Fsnapshot.asp%3Fprivcapid%3D252810438%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F275%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22input%22%7D%5D%7D)**

**Comment by baltpeter** [comment]
Very helpful, thank you!
