### ISSUE TITLE
New company suggestion: `Arvato infoscore GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#276]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "Arvato infoscore GmbH",
    "address": "Arvato infoscore GmbH\nRheinstraße 99\n76532 Baden-Baden\nDeutschland",
    "phone": "+49 7221 50400",
    "email": "datenschutz@arvato-infoscore.de",
    "web": "https://finance.arvato.com",
    "sources": [
        "https://finance.arvato.com/de/impressum/",
        "https://github.com/datenanfragen/data/issues/276"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "input",
            "optional": false
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ],
    "slug": "financearvatocom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22Arvato%20infoscore%20GmbH%22%2C%22address%22%3A%22Arvato%20infoscore%20GmbH%5CnRheinstra%C3%9Fe%2099%5Cn76532%20Baden-Baden%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%207221%2050400%22%2C%22email%22%3A%22datenschutz%40arvato-infoscore.de%22%2C%22web%22%3A%22https%3A%2F%2Ffinance.arvato.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffinance.arvato.com%2Fde%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F276%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%5D%2C%22slug%22%3A%22financearvatocom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
