### ISSUE TITLE
Suggested update for company `pinterest`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#277]
The following suggestion was submitted through the website:

```
{
    "slug": "pinterest",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "social media"
    ],
    "name": "Pinterest Europe Ltd.",
    "runs": [
        "Pinterest Inc.",
        "Pinterest GmbH"
    ],
    "address": "Palmerston House\n2nd Floor\nFenian Street\nDublin 2\nIreland",
    "email": "hallo@pinterest.com",
    "web": "https://www.pinterest.com/",
    "sources": [
        "https://policy.pinterest.com/en/privacy-policy",
        "https://policy.pinterest.com/en/impressumnetzdg",
        "https://github.com/datenanfragen/data/issues/277"
    ],
    "comments": [
        "Contact form: https://help.pinterest.com/en/contact"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pinterest%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Pinterest%20Europe%20Ltd.%22%2C%22runs%22%3A%5B%22Pinterest%20Inc.%22%2C%22Pinterest%20GmbH%22%5D%2C%22address%22%3A%22Palmerston%20House%5Cn2nd%20Floor%5CnFenian%20Street%5CnDublin%202%5CnIreland%22%2C%22email%22%3A%22hallo%40pinterest.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pinterest.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpolicy.pinterest.com%2Fen%2Fprivacy-policy%22%2C%22https%3A%2F%2Fpolicy.pinterest.com%2Fen%2Fimpressumnetzdg%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F277%22%5D%2C%22comments%22%3A%5B%22Contact%20form%3A%20https%3A%2F%2Fhelp.pinterest.com%2Fen%2Fcontact%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
