### ISSUE TITLE
New company suggestion: `Harlekin Spiel- und Unterhaltungsautomaten Betriebsgesellschaft mbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#285]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        null
    ],
    "name": "Harlekin Spiel- und Unterhaltungsautomaten Betriebsgesellschaft mbH",
    "runs": [
        "Fit/One"
    ],
    "address": "Röntgenstr. 15\n97295 Waldbrunn",
    "phone": "09306 90 91 66",
    "web": "info@fit-one.de",
    "sources": [
        "https://www.fit-one.de/",
        null,
        "https://github.com/datenanfragen/data/issues/285"
    ],
    "slug": "harlekin-spiel-und-unterhaltungsautomaten-betriebsgesellschaft-mbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Harlekin%20Spiel-%20und%20Unterhaltungsautomaten%20Betriebsgesellschaft%20mbH%22%2C%22runs%22%3A%5B%22Fit%2FOne%22%5D%2C%22address%22%3A%22R%C3%B6ntgenstr.%2015%5Cn97295%20Waldbrunn%22%2C%22phone%22%3A%2209306%2090%2091%2066%22%2C%22web%22%3A%22info%40fit-one.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fit-one.de%2F%22%2Cnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F285%22%5D%2C%22slug%22%3A%22harlekin-spiel-und-unterhaltungsautomaten-betriebsgesellschaft-mbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
