### ISSUE TITLE
New company suggestion: `CALVARY Petroleum (UK) Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#297]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "commerce"
    ],
    "name": "CALVARY Petroleum (UK) Limited",
    "address": "22-1 Craighall Gardens\nEdinburgh\nGreat Britain\nEH6 4RJ",
    "email": "accounts@calvarypetroleum.co.uk",
    "sources": [
        "www.google.com",
        "https://github.com/datenanfragen/data/issues/297"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "slug": "calvary-petroleum-uk-limited"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22CALVARY%20Petroleum%20(UK)%20Limited%22%2C%22address%22%3A%2222-1%20Craighall%20Gardens%5CnEdinburgh%5CnGreat%20Britain%5CnEH6%204RJ%22%2C%22email%22%3A%22accounts%40calvarypetroleum.co.uk%22%2C%22sources%22%3A%5B%22www.google.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F297%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22calvary-petroleum-uk-limited%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
