### ISSUE TITLE
New company suggestion: `Alphabet`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#298]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "Alphabet",
    "runs": [
        "Google"
    ],
    "address": "Address unknown",
    "sources": [
        "www.google.com",
        "https://github.com/datenanfragen/data/issues/298"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "slug": "alphabet"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Alphabet%22%2C%22runs%22%3A%5B%22Google%22%5D%2C%22address%22%3A%22Address%20unknown%22%2C%22sources%22%3A%5B%22www.google.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F298%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22alphabet%22%7D)**

**Comment by baltpeter** [comment]
Thanks but Google is already in the database.
