### ISSUE TITLE
New company suggestion: `Serco Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#302]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        null
    ],
    "name": "Serco Limited",
    "address": "Enterprise House\n11 Bartley Wood Business Park \nBartley Way\nRG27 9XB\n",
    "phone": "01256 745900",
    "email": "dpo@serco.com",
    "web": "serco.com",
    "sources": [
        "https://www.serco.com/uk/privacy-policy",
        "https://github.com/datenanfragen/data/issues/302"
    ],
    "slug": "serco-limited"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Serco%20Limited%22%2C%22address%22%3A%22Enterprise%20House%5Cn11%20Bartley%20Wood%20Business%20Park%20%5CnBartley%20Way%5CnRG27%209XB%5Cn%22%2C%22phone%22%3A%2201256%20745900%22%2C%22email%22%3A%22dpo%40serco.com%22%2C%22web%22%3A%22serco.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.serco.com%2Fuk%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F302%22%5D%2C%22slug%22%3A%22serco-limited%22%7D)**

**Comment by ManishAradwad** [comment]
Can anyone tell me what am i supposed to do in this issue?? 
I assume we want to add this company in the database..

**Comment by baltpeter** [comment]
@ManishAradwad Sorry, this is essentially already a pull request. Nothing to do here.
