### ISSUE TITLE
New company suggestion: `Concentrix`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#342]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Concentrix",
    "address": "DPO@concentrix.com",
    "sources": [
        "https://www.concentrix.com/gdpr-faq/",
        "https://github.com/datenanfragen/data/issues/342"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "comments": [
        null
    ],
    "slug": "concentrix"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Concentrix%22%2C%22address%22%3A%22DPO%40concentrix.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.concentrix.com%2Fgdpr-faq%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F342%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5Bnull%5D%2C%22slug%22%3A%22concentrix%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
