### ISSUE TITLE
New company suggestion: `Intelligent Apps GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#344]
The following suggestion was submitted through the website:

```
{
    "name": "Intelligent Apps GmbH",
    "address": "Große Elbstraße 273\n22767 Hamburg\nDeutschland",
    "email": "help@mytaxi.com",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/344"
    ],
    "slug": "intelligent-apps-gmbh",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22Intelligent%20Apps%20GmbH%22%2C%22address%22%3A%22Gro%C3%9Fe%20Elbstra%C3%9Fe%20273%5Cn22767%20Hamburg%5CnDeutschland%22%2C%22email%22%3A%22help%40mytaxi.com%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F344%22%5D%2C%22slug%22%3A%22intelligent-apps-gmbh%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
