### ISSUE TITLE
New company suggestion: `DPV Deutscher Pressevertrieb GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#352]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "DPV Deutscher Pressevertrieb GmbH",
    "runs": [
        "Gruner + Jahr GmbH"
    ],
    "address": "Gruner + Jahr GmbH\nc/o Datenschutz\n\n20080 Hamburg\n",
    "phone": "040 / 55 55 78 09",
    "email": "datenschutz@dpv.de",
    "web": "dpv.de",
    "sources": [
        "https://serviceportal.dpv.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/352"
    ],
    "required-elements": [
        {
            "desc": "Abo-Nr. (falls vorh.)",
            "type": "textarea"
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "slug": "dpv-deutscher-pressevertrieb-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22DPV%20Deutscher%20Pressevertrieb%20GmbH%22%2C%22runs%22%3A%5B%22Gruner%20%2B%20Jahr%20GmbH%22%5D%2C%22address%22%3A%22Gruner%20%2B%20Jahr%20GmbH%5Cnc%2Fo%20Datenschutz%5Cn%5Cn20080%20Hamburg%5Cn%22%2C%22phone%22%3A%22040%20%2F%2055%2055%2078%2009%22%2C%22email%22%3A%22datenschutz%40dpv.de%22%2C%22web%22%3A%22dpv.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fserviceportal.dpv.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F352%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Abo-Nr.%20(falls%20vorh.)%22%2C%22type%22%3A%22textarea%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22dpv-deutscher-pressevertrieb-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
