### ISSUE TITLE
New company entries don't show up in autocomplete

### ISSUE THREAD

**Issue by max-horvath** [datenanfragen/data#36]
When adding new entries to the database, those entries show up at https://www.datenanfragen.de/company - but you cannot select those new entries on the generator page in the company select field.

**Comment by baltpeter** [comment]
Thank you for the report!

There was a bug in our deploy script that caused the deploy to fail at some point. I have now fixed that bug and as far as I can see, the new records (and record updates) should now be available in the search.

Let me now if you notice any other problems.
