### ISSUE TITLE
New company suggestion: `Proximus`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#361]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "be"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Proximus",
    "address": "Proximus Towers\nKoning Albert II-laan 27\n1030 Brussel",
    "sources": [
        "https://www.proximus.com/nl/our-company/offices_headquarters_Schaerbeek.html",
        "https://github.com/datenanfragen/data/issues/361"
    ],
    "slug": "proximus"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22be%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Proximus%22%2C%22address%22%3A%22Proximus%20Towers%5CnKoning%20Albert%20II-laan%2027%5Cn1030%20Brussel%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.proximus.com%2Fnl%2Four-company%2Foffices_headquarters_Schaerbeek.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F361%22%5D%2C%22slug%22%3A%22proximus%22%7D)**

**Comment by CXgamer** [comment]
Found the email as well: privacy@proximus.com

**Comment by baltpeter** [comment]
Thanks.
