### ISSUE TITLE
New company suggestion: `Günstiger Reisen`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#363]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Günstiger Reisen",
    "address": "Mariendorfer Damm 147, 12107 Berlin, Deutschland",
    "phone": " 030994040181",
    "fax": "030994040183",
    "email": "service@guenstiger-reisen.de",
    "web": "https://www.günstiger-reisen.de",
    "sources": [
        "https://www.günstiger-reisen.de/datenschutz",
        "https://www.günstiger-reisen.de/impressum",
        "https://www.billigflug.de/service/privacy",
        "https://www.billigflug.de/service/imprint",
        "https://www.reisen.de/service/datenschutz",
        "https://www.reisen.de/service/impressum",
        "https://github.com/datenanfragen/data/issues/363"
    ],
    "slug": "gnstiger-reisende"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22G%C3%BCnstiger%20Reisen%22%2C%22address%22%3A%22Mariendorfer%20Damm%20147%2C%2012107%20Berlin%2C%20Deutschland%22%2C%22phone%22%3A%22%20030994040181%22%2C%22fax%22%3A%22030994040183%22%2C%22email%22%3A%22service%40guenstiger-reisen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.g%C3%BCnstiger-reisen.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.g%C3%BCnstiger-reisen.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.g%C3%BCnstiger-reisen.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.billigflug.de%2Fservice%2Fprivacy%22%2C%22https%3A%2F%2Fwww.billigflug.de%2Fservice%2Fimprint%22%2C%22https%3A%2F%2Fwww.reisen.de%2Fservice%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.reisen.de%2Fservice%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F363%22%5D%2C%22slug%22%3A%22gnstiger-reisende%22%7D)**

**Comment by baltpeter** [comment]
Thanks.

**Comment by m-rey** [comment]
Added in https://github.com/datenanfragen/data/commit/40ea7ebbda405c09d09aa9a766516bd7cc707056
Closing.
