### ISSUE TITLE
New company suggestion: `Folkestone and Hythe District Council`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#366]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "public body"
    ],
    "name": "Folkestone and Hythe District Council",
    "runs": [
        null
    ],
    "address": "Civic Centre, Castle Hill Avenue,Folkestone, Kent CT20 2QY",
    "phone": "01303 853000",
    "email": "dat.protection@folkestone-hythe.gov.uk",
    "web": "folkestone-hythe.gov.uk",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "folkestone-and-hythe-district-council",
    "sources": [
        "https://github.com/datenanfragen/data/issues/366"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Folkestone%20and%20Hythe%20District%20Council%22%2C%22runs%22%3A%5Bnull%5D%2C%22address%22%3A%22Civic%20Centre%2C%20Castle%20Hill%20Avenue%2CFolkestone%2C%20Kent%20CT20%202QY%22%2C%22phone%22%3A%2201303%20853000%22%2C%22email%22%3A%22dat.protection%40folkestone-hythe.gov.uk%22%2C%22web%22%3A%22folkestone-hythe.gov.uk%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22folkestone-and-hythe-district-council%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F366%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
