### ISSUE TITLE
New company suggestion: `Prepaid Services Company Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#372]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "finance"
    ],
    "name": "Prepaid Services Company Limited",
    "runs": [
        "paysafecard.com Deutschland"
    ],
    "address": "Roßstr. 92\nD-40476 Düsseldorf",
    "web": "https://www.paysafecard.com",
    "sources": [
        "https://www.paysafecard.com/de-de/impressum/",
        "https://github.com/datenanfragen/data/issues/372"
    ],
    "slug": "paysafecardcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Prepaid%20Services%20Company%20Limited%22%2C%22runs%22%3A%5B%22paysafecard.com%20Deutschland%22%5D%2C%22address%22%3A%22Ro%C3%9Fstr.%2092%5CnD-40476%20D%C3%BCsseldorf%22%2C%22web%22%3A%22https%3A%2F%2Fwww.paysafecard.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.paysafecard.com%2Fde-de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F372%22%5D%2C%22slug%22%3A%22paysafecardcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
