### ISSUE TITLE
Add CI check for neccesary 'name' type field in the required elements

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#388]
In order for the generator to work properly, when we specify `required-elements` in a record, they need to always contain a field of type `name`.

This needs to be documented.

Ideally, the CI would also check for that.

**Comment by m-rey** [comment]
I've checked. You documented it in commit 1899edff09c0c37973d28bff5bf880573817738e already.

Having a CI test for it would be nice, though.
