### ISSUE TITLE
New company suggestion: ` Institut der deutschen Wirtschaft Köln Medien GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#406]
The following suggestion was submitted through the website:

```
{
    "name": " Institut der deutschen Wirtschaft Köln Medien GmbH",
    "address": "Postfach 10 18 63, 50458 Köln\nKonrad-Adenauer-Ufer 21, 50668 Köln\nTelefon +49 221 4981-0\nTelefax +49 221 4981-533\n",
    "email": "iwmedien(at)iwkoeln.de",
    "web": "https://www.wirtschaftundschule.de",
    "sources": [
        "https://www.wirtschaftundschule.de/datenschutz/",
        "https://www.wirtschaftundschule.de/impressum/",
        "https://github.com/datenanfragen/data/issues/406"
    ],
    "slug": "wirtschaftundschulede",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22%20Institut%20der%20deutschen%20Wirtschaft%20K%C3%B6ln%20Medien%20GmbH%22%2C%22address%22%3A%22Postfach%2010%2018%2063%2C%2050458%20K%C3%B6ln%5CnKonrad-Adenauer-Ufer%2021%2C%2050668%20K%C3%B6ln%5CnTelefon%20%2B49%20221%204981-0%5CnTelefax%20%2B49%20221%204981-533%5Cn%22%2C%22email%22%3A%22iwmedien(at)iwkoeln.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.wirtschaftundschule.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.wirtschaftundschule.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.wirtschaftundschule.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F406%22%5D%2C%22slug%22%3A%22wirtschaftundschulede%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
