### ISSUE TITLE
New company suggestion: `Campact e.V. `

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#407]
The following suggestion was submitted through the website:

```
{
    "name": "Campact e.V. ",
    "runs": [
        "WeAct - die Petitionsplattform von Campact"
    ],
    "address": "Artilleriestr. 6 – 27283 Verden / Aller",
    "web": "https://campact.de",
    "sources": [
        "https://weact.campact.de/media",
        "https://github.com/datenanfragen/data/issues/407"
    ],
    "slug": "campactde",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22Campact%20e.V.%20%22%2C%22runs%22%3A%5B%22WeAct%20-%20die%20Petitionsplattform%20von%20Campact%22%5D%2C%22address%22%3A%22Artilleriestr.%206%20%E2%80%93%2027283%20Verden%20%2F%20Aller%22%2C%22web%22%3A%22https%3A%2F%2Fcampact.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fweact.campact.de%2Fmedia%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F407%22%5D%2C%22slug%22%3A%22campactde%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
