### ISSUE TITLE
New company suggestion: `Kotis Design, LLC`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#409]
The following suggestion was submitted through the website:

```
{
    "name": "Kotis Design, LLC",
    "runs": [
        "https://college.kotisdesign.com/"
    ],
    "web": "https://kotisdesign.com/",
    "sources": [
        "https://go.kotisdesign.com/privacy-policy/",
        "https://github.com/datenanfragen/data/issues/409"
    ],
    "slug": "kotisdesigncom",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22Kotis%20Design%2C%20LLC%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fcollege.kotisdesign.com%2F%22%5D%2C%22web%22%3A%22https%3A%2F%2Fkotisdesign.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgo.kotisdesign.com%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F409%22%5D%2C%22slug%22%3A%22kotisdesigncom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
