### ISSUE TITLE
New company suggestion: `VMG, Vertriebs-Marketing-Gesellschaft mbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#410]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "VMG, Vertriebs-Marketing-Gesellschaft mbH",
    "address": "Niedesheimer Straße 18\n\n67547 Worms\n\n",
    "email": "info@vmg-mbh.de",
    "web": "https://vmg-mbh.de/",
    "slug": "vmg-mbhde",
    "sources": [
        "https://github.com/datenanfragen/data/issues/410"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22VMG%2C%20Vertriebs-Marketing-Gesellschaft%20mbH%22%2C%22address%22%3A%22Niedesheimer%20Stra%C3%9Fe%2018%5Cn%5Cn67547%20Worms%5Cn%5Cn%22%2C%22email%22%3A%22info%40vmg-mbh.de%22%2C%22web%22%3A%22https%3A%2F%2Fvmg-mbh.de%2F%22%2C%22slug%22%3A%22vmg-mbhde%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F410%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
