### ISSUE TITLE
New company suggestion: `The Conservative Party `

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#412]
The following suggestion was submitted through the website:

```
{
    "name": "The Conservative Party ",
    "address": "Compliance Department\nConservative Campaign Headquarters\n4 Matthew Parker Street\nLondon\nSW1H",
    "phone": "+44 20 7984 8005",
    "email": "compliance@conservatives.com",
    "web": "www.conservatives.com",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "the-conservative-party",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/412"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22The%20Conservative%20Party%20%22%2C%22address%22%3A%22Compliance%20Department%5CnConservative%20Campaign%20Headquarters%5Cn4%20Matthew%20Parker%20Street%5CnLondon%5CnSW1H%22%2C%22phone%22%3A%22%2B44%2020%207984%208005%22%2C%22email%22%3A%22compliance%40conservatives.com%22%2C%22web%22%3A%22www.conservatives.com%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22the-conservative-party%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F412%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
