### ISSUE TITLE
New company suggestion: `blackbeards`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#418]
The following suggestion was submitted through the website:

```
{
    "name": "blackbeards",
    "address": "Prinzregentenstraße 14, 83022 Rosenheim",
    "email": "impressum@blackbeards.de",
    "slug": "blackbeards",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/418"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22blackbeards%22%2C%22address%22%3A%22Prinzregentenstra%C3%9Fe%2014%2C%2083022%20Rosenheim%22%2C%22email%22%3A%22impressum%40blackbeards.de%22%2C%22slug%22%3A%22blackbeards%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F418%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
