### ISSUE TITLE
New company suggestion: `ZuluTrade`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#419]
The following suggestion was submitted through the website:

```
{
    "name": "ZuluTrade",
    "address": "Akti Kondili 14,\nPiraeus 185 45\nGreece",
    "phone": "+30 21 3017 6300",
    "email": "support@zulutrade.com",
    "web": "https://www.zulutrade.com",
    "suggested-transport-medium": "letter",
    "slug": "zulutradecom",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/419"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22ZuluTrade%22%2C%22address%22%3A%22Akti%20Kondili%2014%2C%5CnPiraeus%20185%2045%5CnGreece%22%2C%22phone%22%3A%22%2B30%2021%203017%206300%22%2C%22email%22%3A%22support%40zulutrade.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.zulutrade.com%22%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22zulutradecom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F419%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
