### ISSUE TITLE
New company suggestion: `DuckDuckGo`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#420]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "DuckDuckGo",
    "address": "20 Paoli Pike\nPaoli\nPA 19301\nUSA",
    "email": "legal@duckduckgo.com",
    "web": "https://duckduckgo.com",
    "sources": [
        "https://help.duckduckgo.com/duckduckgo-help-pages/company/contact-us/",
        "https://duckduckgo.com/about",
        "https://github.com/datenanfragen/data/issues/420"
    ],
    "suggested-transport-medium": "email",
    "slug": "duckduckgocom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22DuckDuckGo%22%2C%22address%22%3A%2220%20Paoli%20Pike%5CnPaoli%5CnPA%2019301%5CnUSA%22%2C%22email%22%3A%22legal%40duckduckgo.com%22%2C%22web%22%3A%22https%3A%2F%2Fduckduckgo.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fhelp.duckduckgo.com%2Fduckduckgo-help-pages%2Fcompany%2Fcontact-us%2F%22%2C%22https%3A%2F%2Fduckduckgo.com%2Fabout%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F420%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22duckduckgocom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
