### ISSUE TITLE
New company suggestion: `Bisnode AB`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#421]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "Bisnode AB",
    "address": "Bisnode AB Sweden, 169 93 Solna",
    "web": "https://www.bisnode.com",
    "slug": "bisnodecom",
    "sources": [
        "https://github.com/datenanfragen/data/issues/421"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Bisnode%20AB%22%2C%22address%22%3A%22Bisnode%20AB%20Sweden%2C%20169%2093%20Solna%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bisnode.com%22%2C%22slug%22%3A%22bisnodecom%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F421%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
