### ISSUE TITLE
New company suggestion: `Startnext Crowdfunding GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#422]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce",
        "social media"
    ],
    "name": "Startnext Crowdfunding GmbH",
    "web": "https://www.startnext.com",
    "slug": "startnextcom",
    "sources": [
        "https://github.com/datenanfragen/data/issues/422"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Startnext%20Crowdfunding%20GmbH%22%2C%22web%22%3A%22https%3A%2F%2Fwww.startnext.com%22%2C%22slug%22%3A%22startnextcom%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F422%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
