### ISSUE TITLE
New company suggestion: `SK Acquisition Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#423]
The following suggestion was submitted through the website:

```
{
    "name": "SK Acquisition Ltd",
    "runs": [
        "Songkick"
    ],
    "web": "https://www.songkick.com/",
    "slug": "songkickcom",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/423"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22SK%20Acquisition%20Ltd%22%2C%22runs%22%3A%5B%22Songkick%22%5D%2C%22web%22%3A%22https%3A%2F%2Fwww.songkick.com%2F%22%2C%22slug%22%3A%22songkickcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F423%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
