### ISSUE TITLE
New company suggestion: `Under Armour, Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#428]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "Under Armour, Inc.",
    "address": "1020 Hull Street\nBaltimore, MD USA 21230",
    "sources": [
        "https://account.underarmour.com/en-us/privacy#location-specific-disclosures",
        "https://github.com/datenanfragen/data/issues/428"
    ],
    "slug": "under-armour-inc"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Under%20Armour%2C%20Inc.%22%2C%22address%22%3A%221020%20Hull%20Street%5CnBaltimore%2C%20MD%20USA%2021230%22%2C%22sources%22%3A%5B%22https%3A%2F%2Faccount.underarmour.com%2Fen-us%2Fprivacy%23location-specific-disclosures%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F428%22%5D%2C%22slug%22%3A%22under-armour-inc%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
