### ISSUE TITLE
New company suggestion: `Zomato`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#429]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "Zomato",
    "address": "Zomato Media Portugal, Unipessoal LDA,\nAvenida 24 de Julho,\nN 102-E, 1200-870, Lisboa, Portugal",
    "email": "privacy@zomato.com",
    "sources": [
        "https://www.zomato.com/privacy",
        "https://github.com/datenanfragen/data/issues/429"
    ],
    "slug": "zomato"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Zomato%22%2C%22address%22%3A%22Zomato%20Media%20Portugal%2C%20Unipessoal%20LDA%2C%5CnAvenida%2024%20de%20Julho%2C%5CnN%20102-E%2C%201200-870%2C%20Lisboa%2C%20Portugal%22%2C%22email%22%3A%22privacy%40zomato.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.zomato.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F429%22%5D%2C%22slug%22%3A%22zomato%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
