### ISSUE TITLE
New company suggestion: `Orange SA`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#432]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr",
        "be",
        "es",
        "lu",
        "md",
        "pl",
        "ro",
        "sk"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Orange SA",
    "address": "78 rue Olivier de Serres\n75 015 Paris",
    "phone": "+33 1 44 44 22 22",
    "web": "https://www.orange.com/",
    "sources": [
        "https://www.orange.com/en/Footer/legal-matters",
        "https://fr.wikipedia.org/wiki/Orange_(entreprise)",
        "https://github.com/datenanfragen/data/issues/432"
    ],
    "slug": "orangecom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%2C%22be%22%2C%22es%22%2C%22lu%22%2C%22md%22%2C%22pl%22%2C%22ro%22%2C%22sk%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Orange%20SA%22%2C%22address%22%3A%2278%20rue%20Olivier%20de%20Serres%5Cn75%20015%20Paris%22%2C%22phone%22%3A%22%2B33%201%2044%2044%2022%2022%22%2C%22web%22%3A%22https%3A%2F%2Fwww.orange.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.orange.com%2Fen%2FFooter%2Flegal-matters%22%2C%22https%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FOrange_(entreprise)%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F432%22%5D%2C%22slug%22%3A%22orangecom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
