### ISSUE TITLE
New company suggestion: `Free`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#434]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Free",
    "runs": [
        "Free SAS"
    ],
    "address": "FREE SAS\n8 rue de la Ville l’Évêque\n75008 Paris",
    "phone": "32 44",
    "web": "https://www.free.fr/",
    "sources": [
        "https://www.free.fr/",
        "https://github.com/datenanfragen/data/issues/434"
    ],
    "slug": "freefr"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Free%22%2C%22runs%22%3A%5B%22Free%20SAS%22%5D%2C%22address%22%3A%22FREE%20SAS%5Cn8%20rue%20de%20la%20Ville%20l%E2%80%99%C3%89v%C3%AAque%5Cn75008%20Paris%22%2C%22phone%22%3A%2232%2044%22%2C%22web%22%3A%22https%3A%2F%2Fwww.free.fr%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.free.fr%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F434%22%5D%2C%22slug%22%3A%22freefr%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
