### ISSUE TITLE
New company suggestion: `SFR`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#435]
The following suggestion was submitted through the website:

```
{
    "name": "SFR",
    "runs": [
        "Numericable",
        "Altice France"
    ],
    "address": "Client SFR :\n\nService client SFR Données personnelles\nTSA 10101\n69947 LYON CEDEX 20\n\nClient NUMERICABLE :\n\nService client SFR FIBRE SAS Données personnelles\nTSA 61000\n92894 NANTERRE CEDEX",
    "phone": "+33 1 85 06 00 00",
    "web": "https://www.sfr.fr/",
    "sources": [
        "https://www.sfr.fr/mentions-legales.html",
        "https://www.sfr.fr/politique-de-protection-des-donnees-personnelles.html",
        "https://github.com/datenanfragen/data/issues/435"
    ],
    "required-elements": [
        {
            "desc": "Nom",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Prénom",
            "type": "input",
            "optional": false
        },
        {
            "desc": "Numéro d'appel",
            "type": "input",
            "optional": false
        }
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "letter",
    "slug": "sfrfr",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22SFR%22%2C%22runs%22%3A%5B%22Numericable%22%2C%22Altice%20France%22%5D%2C%22address%22%3A%22Client%20SFR%20%3A%5Cn%5CnService%20client%20SFR%20Donn%C3%A9es%20personnelles%5CnTSA%2010101%5Cn69947%20LYON%20CEDEX%2020%5Cn%5CnClient%20NUMERICABLE%20%3A%5Cn%5CnService%20client%20SFR%20FIBRE%20SAS%20Donn%C3%A9es%20personnelles%5CnTSA%2061000%5Cn92894%20NANTERRE%20CEDEX%22%2C%22phone%22%3A%22%2B33%201%2085%2006%2000%2000%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sfr.fr%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sfr.fr%2Fmentions-legales.html%22%2C%22https%3A%2F%2Fwww.sfr.fr%2Fpolitique-de-protection-des-donnees-personnelles.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F435%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Nom%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Pr%C3%A9nom%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Num%C3%A9ro%20d'appel%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22sfrfr%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by NathanBnm** [comment]
`fr` should be added to relevant-countries

**Comment by baltpeter** [comment]
Thanks.
