### ISSUE TITLE
New company suggestion: `Fnac`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#436]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr",
        "es",
        "pt",
        "be",
        "ch",
        "lu"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Fnac",
    "runs": [
        "Darty"
    ],
    "address": "FNAC DARTY\nService Consommateur\nLe Flavia\n9, rue des Bateaux Lavoirs\n94768 Ivry sur Seine",
    "phone": "+33 1 55 21 57 93",
    "email": "vieprivee@fnacdarty.com",
    "web": "https://www.fnac.com/",
    "sources": [
        "https://www.fnac.com/Help/donneesPersonnelles",
        "https://www.fnac.com/entreprise/mentions_legales.aspx",
        "https://github.com/datenanfragen/data/issues/436"
    ],
    "required-elements": [
        {
            "desc": "Nom",
            "type": "name",
            "optional": true
        },
        {
            "desc": "Prénom",
            "type": "input",
            "optional": true
        },
        {
            "desc": "Adresse e-mail",
            "type": "input",
            "optional": true
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": true
        },
        {
            "desc": "Enseigne visée (Fnac, Darty)",
            "type": "input",
            "optional": true
        }
    ],
    "needs-id-document": false,
    "slug": "fnaccom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%2C%22es%22%2C%22pt%22%2C%22be%22%2C%22ch%22%2C%22lu%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Fnac%22%2C%22runs%22%3A%5B%22Darty%22%5D%2C%22address%22%3A%22FNAC%20DARTY%5CnService%20Consommateur%5CnLe%20Flavia%5Cn9%2C%20rue%20des%20Bateaux%20Lavoirs%5Cn94768%20Ivry%20sur%20Seine%22%2C%22phone%22%3A%22%2B33%201%2055%2021%2057%2093%22%2C%22email%22%3A%22vieprivee%40fnacdarty.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fnac.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fnac.com%2FHelp%2FdonneesPersonnelles%22%2C%22https%3A%2F%2Fwww.fnac.com%2Fentreprise%2Fmentions_legales.aspx%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F436%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Nom%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Atrue%7D%2C%7B%22desc%22%3A%22Pr%C3%A9nom%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Atrue%7D%2C%7B%22desc%22%3A%22Adresse%20e-mail%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Atrue%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Atrue%7D%2C%7B%22desc%22%3A%22Enseigne%20vis%C3%A9e%20(Fnac%2C%20Darty)%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Atrue%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22slug%22%3A%22fnaccom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
