### ISSUE TITLE
New company suggestion: `Cdiscount`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#437]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr",
        "be",
        "it",
        "de",
        "es",
        "lu"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Cdiscount",
    "address": "Cdiscount.com / SGPN\nService Clients\nBP 90200\n93472 Neuilly Sur Marne",
    "email": "informatique-et-libertes@cdiscount.com",
    "web": "https://www.cdiscount.com/",
    "required-elements": [
        {
            "desc": "Adresse e-mail rattachée au compte client",
            "type": "input",
            "optional": false
        },
        {
            "desc": "Nom",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Prénom",
            "type": "input",
            "optional": false
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "cdiscountcom",
    "sources": [
        "https://github.com/datenanfragen/data/issues/437"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%2C%22be%22%2C%22it%22%2C%22de%22%2C%22es%22%2C%22lu%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Cdiscount%22%2C%22address%22%3A%22Cdiscount.com%20%2F%20SGPN%5CnService%20Clients%5CnBP%2090200%5Cn93472%20Neuilly%20Sur%20Marne%22%2C%22email%22%3A%22informatique-et-libertes%40cdiscount.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cdiscount.com%2F%22%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Adresse%20e-mail%20rattach%C3%A9e%20au%20compte%20client%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Nom%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Pr%C3%A9nom%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22cdiscountcom%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F437%22%5D%7D)**

**Comment by NathanBnm** [comment]
Please add the following sources:
- https://www.cdiscount.com/vie-privee-et-cookies.html
- https://i6.cdscdn.com/resources/imagesok/cgv/ml.pdf

**Comment by baltpeter** [comment]
Thanks.
