### ISSUE TITLE
New company suggestion: `Wikipédia`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#438]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "nonprofit"
    ],
    "name": "Wikipédia",
    "runs": [
        "Wikimedia Commons",
        "Mediawiki",
        "Méta-Wiki",
        "Wikispecies",
        "Wikilivres",
        "Wikidata",
        "Wikimania",
        "Wikinews",
        "Wikiquote",
        "Wikiversité",
        "Wikivoyage",
        "Wiktionnaire"
    ],
    "address": "Wikimedia Foundation, Inc.\n1 Montgomery Street\nSuite 1600\nSan Francisco, CA 94104\nUSA",
    "phone": "+1 415 839 6885",
    "fax": "+1 415 882 0495",
    "email": "privacy@wikimedia.org",
    "web": "https://www.wikipedia.org/",
    "sources": [
        "https://meta.wikimedia.org/wiki/Privacy_policy/",
        "https://github.com/datenanfragen/data/issues/438"
    ],
    "slug": "wikipediaorg"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22Wikip%C3%A9dia%22%2C%22runs%22%3A%5B%22Wikimedia%20Commons%22%2C%22Mediawiki%22%2C%22M%C3%A9ta-Wiki%22%2C%22Wikispecies%22%2C%22Wikilivres%22%2C%22Wikidata%22%2C%22Wikimania%22%2C%22Wikinews%22%2C%22Wikiquote%22%2C%22Wikiversit%C3%A9%22%2C%22Wikivoyage%22%2C%22Wiktionnaire%22%5D%2C%22address%22%3A%22Wikimedia%20Foundation%2C%20Inc.%5Cn1%20Montgomery%20Street%5CnSuite%201600%5CnSan%20Francisco%2C%20CA%2094104%5CnUSA%22%2C%22phone%22%3A%22%2B1%20415%20839%206885%22%2C%22fax%22%3A%22%2B1%20415%20882%200495%22%2C%22email%22%3A%22privacy%40wikimedia.org%22%2C%22web%22%3A%22https%3A%2F%2Fwww.wikipedia.org%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmeta.wikimedia.org%2Fwiki%2FPrivacy_policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F438%22%5D%2C%22slug%22%3A%22wikipediaorg%22%7D)**

**Comment by tstrohmeier** [comment]
the url is not resolving correctly, the last slash is to much : `"https://meta.wikimedia.org/wiki/Privacy_policy/",`

**Comment by tstrohmeier** [comment]
The names seems to be FR. I would suggest to use EN for `all` countries.
`Wikiversité` -> `Wikiversity` 
`Wiktionnaire` -> `Wiktionary`

**Comment by baltpeter** [comment]
Thanks!
