### ISSUE TITLE
New company suggestion: `Hutchison Drei Austria GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#439]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Hutchison Drei Austria GmbH",
    "address": "Brünner Straße 52\nA - 1210 Wien",
    "phone": "+43 660 303030",
    "fax": "+43 660 303031",
    "email": "serviceteam@drei.at",
    "web": "https://www.drei.at",
    "sources": [
        "https://www.drei.at/de/footernavigation/impressum/",
        "https://github.com/datenanfragen/data/issues/439"
    ],
    "slug": "dreiat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Hutchison%20Drei%20Austria%20GmbH%22%2C%22address%22%3A%22Br%C3%BCnner%20Stra%C3%9Fe%2052%5CnA%20-%201210%20Wien%22%2C%22phone%22%3A%22%2B43%20660%20303030%22%2C%22fax%22%3A%22%2B43%20660%20303031%22%2C%22email%22%3A%22serviceteam%40drei.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.drei.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.drei.at%2Fde%2Ffooternavigation%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F439%22%5D%2C%22slug%22%3A%22dreiat%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
