### ISSUE TITLE
New company suggestion: `Digitalraum GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#441]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads",
        "social media"
    ],
    "name": "Digitalraum GmbH",
    "address": "Ackerstrassse 11, 40233 Düsseldorf",
    "phone": "+49 211 93677836",
    "fax": "+49 211 93677830",
    "email": "marketing@digitalraum.de",
    "web": "https://www.digitalraum.de/",
    "sources": [
        "https://www.digitalraum.de/datenschutz/",
        "https://github.com/datenanfragen/data/issues/441"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "digitalraumde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Digitalraum%20GmbH%22%2C%22address%22%3A%22Ackerstrassse%2011%2C%2040233%20D%C3%BCsseldorf%22%2C%22phone%22%3A%22%2B49%20211%2093677836%22%2C%22fax%22%3A%22%2B49%20211%2093677830%22%2C%22email%22%3A%22marketing%40digitalraum.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.digitalraum.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.digitalraum.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F441%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22digitalraumde%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
