### ISSUE TITLE
New company suggestion: `Stadium Sverige AB`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#442]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "se"
    ],
    "categories": [
        "commerce",
        null
    ],
    "name": "Stadium Sverige AB",
    "address": "601 60 Norrköping\nSweden",
    "phone": "0771-499 499",
    "email": "info@stadium.se",
    "web": "https://www.stadium.se/",
    "slug": "stadiumse",
    "sources": [
        "https://github.com/datenanfragen/data/issues/442"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22se%22%5D%2C%22categories%22%3A%5B%22commerce%22%2Cnull%5D%2C%22name%22%3A%22Stadium%20Sverige%20AB%22%2C%22address%22%3A%22601%2060%20Norrk%C3%B6ping%5CnSweden%22%2C%22phone%22%3A%220771-499%20499%22%2C%22email%22%3A%22info%40stadium.se%22%2C%22web%22%3A%22https%3A%2F%2Fwww.stadium.se%2F%22%2C%22slug%22%3A%22stadiumse%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F442%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
