### ISSUE TITLE
New company suggestion: `Abel & Cole`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#443]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "health"
    ],
    "name": "Abel & Cole",
    "address": "Data Protection Office,\nAbel & Cole,\nThe Riverside Building,\nLivingstone Road,\nHessle,\nEast Yorkshire,\nUnited Kingdom,\nHU13 0DZ",
    "phone": "+44 345 262 6262",
    "email": "privacy@abelandcole.co.uk",
    "web": "www.abelandcole.co.uk",
    "sources": [
        "https://www.abelandcole.co.uk/",
        "https://github.com/datenanfragen/data/issues/443"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "abel-cole"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Abel%20%26%20Cole%22%2C%22address%22%3A%22Data%20Protection%20Office%2C%5CnAbel%20%26%20Cole%2C%5CnThe%20Riverside%20Building%2C%5CnLivingstone%20Road%2C%5CnHessle%2C%5CnEast%20Yorkshire%2C%5CnUnited%20Kingdom%2C%5CnHU13%200DZ%22%2C%22phone%22%3A%22%2B44%20345%20262%206262%22%2C%22email%22%3A%22privacy%40abelandcole.co.uk%22%2C%22web%22%3A%22www.abelandcole.co.uk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.abelandcole.co.uk%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F443%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22abel-cole%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
