### ISSUE TITLE
Suggested update for company `unitymedia`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#444]
The following suggestion was submitted through the website:

```
{
    "slug": "unitymedia",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Unitymedia GmbH",
    "runs": [
        "Unitymedia NRW GmbH",
        "Unitymedia Hessen GmbH & Co KG",
        "Unitymedia BW GmbH",
        "Unitymedia Finanz-Service GmbH",
        "Horizon Go"
    ],
    "address": "Aachener Straße 746 – 750\n50933 Köln\nDeutschland",
    "phone": "+49 221 46619100",
    "fax": "+49 221 46619109",
    "email": "datenschutz@unitymedia.de",
    "web": "https://www.unitymedia.de/",
    "sources": [
        "https://www.unitymedia.de/privatkunden/datenschutz/",
        "https://www.unitymedia.de/privatkunden/impressum/",
        "https://github.com/datenanfragen/data/issues/444"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Unitymedia ist inzwischne von Vodafone aufgekauft worden. Da die Auskunft alle vom Konzern gespeicherten DAten betrifft z.B. Vertäge mit Vodafone fürs Handy und Unitymedia fürs Internet, muss man sich dann nicht an den Mutterkonzern Vodafone wenden?"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22unitymedia%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Unitymedia%20GmbH%22%2C%22runs%22%3A%5B%22Unitymedia%20NRW%20GmbH%22%2C%22Unitymedia%20Hessen%20GmbH%20%26%20Co%20KG%22%2C%22Unitymedia%20BW%20GmbH%22%2C%22Unitymedia%20Finanz-Service%20GmbH%22%2C%22Horizon%20Go%22%5D%2C%22address%22%3A%22Aachener%20Stra%C3%9Fe%20746%20%E2%80%93%20750%5Cn50933%20K%C3%B6ln%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20221%2046619100%22%2C%22fax%22%3A%22%2B49%20221%2046619109%22%2C%22email%22%3A%22datenschutz%40unitymedia.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.unitymedia.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.unitymedia.de%2Fprivatkunden%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.unitymedia.de%2Fprivatkunden%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F444%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Unitymedia%20ist%20inzwischne%20von%20Vodafone%20aufgekauft%20worden.%20Da%20die%20Auskunft%20alle%20vom%20Konzern%20gespeicherten%20DAten%20betrifft%20z.B.%20Vert%C3%A4ge%20mit%20Vodafone%20f%C3%BCrs%20Handy%20und%20Unitymedia%20f%C3%BCrs%20Internet%2C%20muss%20man%20sich%20dann%20nicht%20an%20den%20Mutterkonzern%20Vodafone%20wenden%3F%22%5D%7D)**

**Comment by baltpeter** [comment]
Also die [Datenschutzerklärung](https://www.unitymedia.de/privatkunden/datenschutz) von Unitymedia listet immer noch die Kontaktdaten, die wir auch haben. Und [Vodafone](https://www.vodafone.de/media/downloads/pdf/190115-vertragliche-datenschutz-hinweise.pdf) spricht in ihrer DSE weiterhin nur von Vodafone und Kabel Deutschland.

Sollte also noch alles richtig sein.
