### ISSUE TITLE
New company suggestion: `Wolterskluwer Deutschland GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#445]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Wolterskluwer Deutschland GmbH",
    "runs": [
        "Akademische Arbeitsgemeinschaft Verlagsgesellschaft mbH"
    ],
    "address": "c/o TÜV IT, IT Security & Privacy\nLangemarckstr. 20\n45141 Essen",
    "phone": "0201 8999-899",
    "fax": "0201 8999-666",
    "email": "dsb@wolterskluwer.com",
    "web": "https://www.wolterskluwer.de",
    "sources": [
        "https://www.wolterskluwer.de/datenschutz/",
        "https://www.steuertipps.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/445"
    ],
    "required-elements": [
        {
            "desc": "Auskunftsanfrage für Wolterskluwer-Tochterfirma:",
            "type": "input"
        }
    ],
    "needs-id-document": false,
    "slug": "wolterskluwerde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Wolterskluwer%20Deutschland%20GmbH%22%2C%22runs%22%3A%5B%22Akademische%20Arbeitsgemeinschaft%20Verlagsgesellschaft%20mbH%22%5D%2C%22address%22%3A%22c%2Fo%20T%C3%9CV%20IT%2C%20IT%20Security%20%26%20Privacy%5CnLangemarckstr.%2020%5Cn45141%20Essen%22%2C%22phone%22%3A%220201%208999-899%22%2C%22fax%22%3A%220201%208999-666%22%2C%22email%22%3A%22dsb%40wolterskluwer.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.wolterskluwer.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.wolterskluwer.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.steuertipps.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F445%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Auskunftsanfrage%20f%C3%BCr%20Wolterskluwer-Tochterfirma%3A%22%2C%22type%22%3A%22input%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22slug%22%3A%22wolterskluwerde%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
