### ISSUE TITLE
New company suggestion: `DECENTRALIZED GLOBAL PAYMENTS, S.L.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#446]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "finance"
    ],
    "name": "DECENTRALIZED GLOBAL PAYMENTS, S.L.",
    "address": "Plaza de Catalunya, 21\n08002, Barcelona\nSpain",
    "email": "hello@verse.me",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/446"
    ],
    "slug": "decentralized-global-payments-sl"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22DECENTRALIZED%20GLOBAL%20PAYMENTS%2C%20S.L.%22%2C%22address%22%3A%22Plaza%20de%20Catalunya%2C%2021%5Cn08002%2C%20Barcelona%5CnSpain%22%2C%22email%22%3A%22hello%40verse.me%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F446%22%5D%2C%22slug%22%3A%22decentralized-global-payments-sl%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
