### ISSUE TITLE
New company suggestion: `Versio`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#447]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "nl",
        "be",
        "gb"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Versio",
    "address": "Francois Haverschmidtwei 2\n8914 BC Leeuwarden\nNederland",
    "fax": "+31 84 873 7447",
    "email": "support@versio.nl",
    "web": "https://versio.nl/",
    "sources": [
        "https://versio.nl/",
        "https://github.com/datenanfragen/data/issues/447"
    ],
    "required-elements": [
        {
            "desc": "Email",
            "type": "email"
        },
        {
            "desc": "Name",
            "type": "name"
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "versionl"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22nl%22%2C%22be%22%2C%22gb%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Versio%22%2C%22address%22%3A%22Francois%20Haverschmidtwei%202%5Cn8914%20BC%20Leeuwarden%5CnNederland%22%2C%22fax%22%3A%22%2B31%2084%20873%207447%22%2C%22email%22%3A%22support%40versio.nl%22%2C%22web%22%3A%22https%3A%2F%2Fversio.nl%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fversio.nl%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F447%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%7D%2C%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22versionl%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
