### ISSUE TITLE
New company suggestion: `Qwant`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#449]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "social media"
    ],
    "name": "Qwant",
    "address": "QWANT\nDirection Ethique & Affaires Juridiques\n7 rue Spontini\n75116 Paris\nFrance ",
    "phone": "+33 1 83 64 89 37",
    "email": "privacy@qwant.com",
    "web": "https://www.qwant.com/",
    "sources": [
        "https://about.qwant.com/fr/legal/confidentialite/",
        "https://github.com/datenanfragen/data/issues/449"
    ],
    "slug": "qwantcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Qwant%22%2C%22address%22%3A%22QWANT%5CnDirection%20Ethique%20%26%20Affaires%20Juridiques%5Cn7%20rue%20Spontini%5Cn75116%20Paris%5CnFrance%20%22%2C%22phone%22%3A%22%2B33%201%2083%2064%2089%2037%22%2C%22email%22%3A%22privacy%40qwant.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.qwant.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fabout.qwant.com%2Ffr%2Flegal%2Fconfidentialite%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F449%22%5D%2C%22slug%22%3A%22qwantcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
