### ISSUE TITLE
New company suggestion: `Werbeagentur 1Plus Agency GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#450]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads",
        "social media"
    ],
    "name": "Werbeagentur 1Plus Agency GmbH",
    "address": "O4 4, 68161 Mannheim, Baden-Württemberg, Germany",
    "phone": "+49 621 49078707",
    "fax": "+49 6252 6990559",
    "email": "support@1plus-agency.com",
    "web": "https://www.1plus-agency.com/",
    "sources": [
        "https://www.facebook.com/1plusagency/",
        "https://github.com/datenanfragen/data/issues/450"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "comments": [
        "Mit Sitz in Heppenheim und Mannheim hat die international tätige Full-Service Werbeagentur 1Plus Agency ihre Schwerpunkte in den Disziplinen Web, App, Online Marketing, Design & Print und Video & Bild gesetzt. Zudem richtet sich unser Augenmerk auf die Entwicklung, Realisierung, Beratung und Betreuung von Web und Online Marketing Projekten aller Art. Unser Fokus liegt in der kreativen Gestaltung und technischen Umsetzung Ihrer Ideen und Wünsche."
    ],
    "slug": "1plus-agencycom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Werbeagentur%201Plus%20Agency%20GmbH%22%2C%22address%22%3A%22O4%204%2C%2068161%20Mannheim%2C%20Baden-W%C3%BCrttemberg%2C%20Germany%22%2C%22phone%22%3A%22%2B49%20621%2049078707%22%2C%22fax%22%3A%22%2B49%206252%206990559%22%2C%22email%22%3A%22support%401plus-agency.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.1plus-agency.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.facebook.com%2F1plusagency%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F450%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Mit%20Sitz%20in%20Heppenheim%20und%20Mannheim%20hat%20die%20international%20t%C3%A4tige%20Full-Service%20Werbeagentur%201Plus%20Agency%20ihre%20Schwerpunkte%20in%20den%20Disziplinen%20Web%2C%20App%2C%20Online%20Marketing%2C%20Design%20%26%20Print%20und%20Video%20%26%20Bild%20gesetzt.%20Zudem%20richtet%20sich%20unser%20Augenmerk%20auf%20die%20Entwicklung%2C%20Realisierung%2C%20Beratung%20und%20Betreuung%20von%20Web%20und%20Online%20Marketing%20Projekten%20aller%20Art.%20Unser%20Fokus%20liegt%20in%20der%20kreativen%20Gestaltung%20und%20technischen%20Umsetzung%20Ihrer%20Ideen%20und%20W%C3%BCnsche.%22%5D%2C%22slug%22%3A%221plus-agencycom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
