### ISSUE TITLE
New company suggestion: `Erzbistum Berlin`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#451]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "Erzbistum Berlin",
    "address": "Postfach 040856\n10064 Berlin",
    "web": "https://erzbistumberlin.de",
    "suggested-transport-medium": "letter",
    "slug": "erzbistumberlinde",
    "sources": [
        "https://github.com/datenanfragen/data/issues/451"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Erzbistum%20Berlin%22%2C%22address%22%3A%22Postfach%20040856%5Cn10064%20Berlin%22%2C%22web%22%3A%22https%3A%2F%2Ferzbistumberlin.de%22%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22erzbistumberlinde%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F451%22%5D%7D)**

**Comment by baltpeter** [comment]
Some of the churches in Germany have their own data protection laws and the GDPR doesn't apply to them. As such, it doesn't make too much sense to add this until we have specific templates for this case.
