### ISSUE TITLE
New company suggestion: `ZOLA, Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#452]
The following suggestion was submitted through the website:

```
{
    "name": "ZOLA, Inc.",
    "address": " 250 Greenwich St. 39th Floor, New York, NY 10007",
    "web": "zola.com",
    "slug": "zola-inc",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/452"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22ZOLA%2C%20Inc.%22%2C%22address%22%3A%22%20250%20Greenwich%20St.%2039th%20Floor%2C%20New%20York%2C%20NY%2010007%22%2C%22web%22%3A%22zola.com%22%2C%22slug%22%3A%22zola-inc%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F452%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
