### ISSUE TITLE
New company suggestion: `PERX TECHNOLOGIES PTE LTD`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#453]
The following suggestion was submitted through the website:

```
{
    "categories": [
        "commerce"
    ],
    "name": "PERX TECHNOLOGIES PTE LTD",
    "address": "The Riverwalk\n20 Upper Circular Road\n#02-21B\nSingapore 058416",
    "phone": "(65) 6816 2711",
    "email": "contact@perxtech.com",
    "web": "https://www.perxtech.com",
    "sources": [
        "https://www.perxtech.com/privacy/#privacy",
        "https://github.com/datenanfragen/data/issues/453"
    ],
    "suggested-transport-medium": "email",
    "slug": "perxtechcom",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22PERX%20TECHNOLOGIES%20PTE%20LTD%22%2C%22address%22%3A%22The%20Riverwalk%5Cn20%20Upper%20Circular%20Road%5Cn%2302-21B%5CnSingapore%20058416%22%2C%22phone%22%3A%22(65)%206816%202711%22%2C%22email%22%3A%22contact%40perxtech.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.perxtech.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.perxtech.com%2Fprivacy%2F%23privacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F453%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22perxtechcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
