### ISSUE TITLE
New company suggestion: `E-Werk Kulturzentrum GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#454]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "E-Werk Kulturzentrum GmbH",
    "address": "c/o WGM Consulting GmbH\nTheatinerstrasse 11\n80333 München\nDeutschland",
    "phone": "089/ 71042 24 98",
    "email": "info@wgm-consulting.de",
    "web": "https://www.e-werk.de",
    "sources": [
        "https://www.e-werk.de/impressum/",
        "https://www.e-werk.de/datenschutz/",
        "https://github.com/datenanfragen/data/issues/454"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Email",
            "type": "email"
        }
    ],
    "slug": "e-werkde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22E-Werk%20Kulturzentrum%20GmbH%22%2C%22address%22%3A%22c%2Fo%20WGM%20Consulting%20GmbH%5CnTheatinerstrasse%2011%5Cn80333%20M%C3%BCnchen%5CnDeutschland%22%2C%22phone%22%3A%22089%2F%2071042%2024%2098%22%2C%22email%22%3A%22info%40wgm-consulting.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.e-werk.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.e-werk.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fwww.e-werk.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F454%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%7D%5D%2C%22slug%22%3A%22e-werkde%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
