### ISSUE TITLE
New company suggestion: `Google.com`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#455]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "es",
        null
    ],
    "categories": [
        null
    ],
    "name": "Google.com",
    "slug": "googlecom",
    "sources": [
        "https://github.com/datenanfragen/data/issues/455"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22es%22%2Cnull%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Google.com%22%2C%22slug%22%3A%22googlecom%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F455%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks for the suggestion but Google is already in our database: https://www.datarequests.org/company/google
