### ISSUE TITLE
New company suggestion: `Lotto24 AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#456]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Lotto24 AG",
    "address": "Straßenbahnring 11\n20251 Hamburg",
    "phone": "040 - 8 222 39 - 0",
    "fax": "040 - 8 222 39 - 70",
    "email": "office@lotto24.de",
    "web": "https://www.lotto24.de",
    "sources": [
        "https://www.lotto24.de/webshop/content/datenschutz.html",
        "https://de.wikipedia.org/wiki/Lotto24",
        "https://github.com/datenanfragen/data/issues/456"
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "letter",
    "slug": "lotto24de"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Lotto24%20AG%22%2C%22address%22%3A%22Stra%C3%9Fenbahnring%2011%5Cn20251%20Hamburg%22%2C%22phone%22%3A%22040%20-%208%20222%2039%20-%200%22%2C%22fax%22%3A%22040%20-%208%20222%2039%20-%2070%22%2C%22email%22%3A%22office%40lotto24.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.lotto24.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lotto24.de%2Fwebshop%2Fcontent%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FLotto24%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F456%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22lotto24de%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
