### ISSUE TITLE
New company suggestion: `Toto-Lotto Niedersachsen GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#457]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Toto-Lotto Niedersachsen GmbH",
    "address": "Am TÜV 2 + 4\n30519 Hannover",
    "phone": "0511 8402-0",
    "email": "datenschutz@lotto-niedersachsen.de",
    "web": "https://www.lotto.de/datenschutzerklaerung",
    "sources": [
        "https://www.lotto.de/datenschutzerklaerung",
        "https://de.wikipedia.org/wiki/Toto-Lotto_Niedersachsen",
        "https://github.com/datenanfragen/data/issues/457"
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "letter",
    "slug": "lottode"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Toto-Lotto%20Niedersachsen%20GmbH%22%2C%22address%22%3A%22Am%20T%C3%9CV%202%20%2B%204%5Cn30519%20Hannover%22%2C%22phone%22%3A%220511%208402-0%22%2C%22email%22%3A%22datenschutz%40lotto-niedersachsen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.lotto.de%2Fdatenschutzerklaerung%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lotto.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FToto-Lotto_Niedersachsen%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F457%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22lottode%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
