### ISSUE TITLE
New company suggestion: `PGN Pirckheimer-Gymnasium Nürnberg`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#458]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "school"
    ],
    "name": "PGN Pirckheimer-Gymnasium Nürnberg",
    "address": "Gibitzenhofstraße 151\n90443 Nürnberg\nDeutschland",
    "phone": "0911/231-14033",
    "fax": "0911/424-9318",
    "email": "sekretariat@pirckheimer-gymnasium.de",
    "web": "https://www.pirckheimer-gymnasium.de",
    "sources": [
        "https://www.pirckheimer-gymnasium.de/seite/kontakt",
        "https://www.pirckheimer-gymnasium.de/seite/datenschutzhinweise",
        "https://github.com/datenanfragen/data/issues/458"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Adresse",
            "type": "address"
        },
        {
            "desc": "E-Mail",
            "type": "email"
        }
    ],
    "slug": "pirckheimer-gymnasiumde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22PGN%20Pirckheimer-Gymnasium%20N%C3%BCrnberg%22%2C%22address%22%3A%22Gibitzenhofstra%C3%9Fe%20151%5Cn90443%20N%C3%BCrnberg%5CnDeutschland%22%2C%22phone%22%3A%220911%2F231-14033%22%2C%22fax%22%3A%220911%2F424-9318%22%2C%22email%22%3A%22sekretariat%40pirckheimer-gymnasium.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pirckheimer-gymnasium.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.pirckheimer-gymnasium.de%2Fseite%2Fkontakt%22%2C%22https%3A%2F%2Fwww.pirckheimer-gymnasium.de%2Fseite%2Fdatenschutzhinweise%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F458%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22email%22%7D%5D%2C%22slug%22%3A%22pirckheimer-gymnasiumde%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
