### ISSUE TITLE
New company suggestion: `HabboCity`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#459]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "HabboCity",
    "address": "Unknown",
    "email": "contact@habbocity.me",
    "web": "https://www.habbocity.me",
    "sources": [
        "https://www.habbocity.me/conditions",
        "https://github.com/datenanfragen/data/issues/459"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "habbocityme"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22HabboCity%22%2C%22address%22%3A%22Unknown%22%2C%22email%22%3A%22contact%40habbocity.me%22%2C%22web%22%3A%22https%3A%2F%2Fwww.habbocity.me%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.habbocity.me%2Fconditions%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F459%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22habbocityme%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
