### ISSUE TITLE
New company suggestion: `NRJ`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#460]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr",
        "be",
        "de",
        "at",
        "bg",
        "dk",
        "fi",
        "ge",
        "gr",
        "jo",
        "lb",
        "no",
        "ru",
        "se",
        "ma"
    ],
    "categories": [
        "entertainment",
        "telecommunication"
    ],
    "name": "NRJ",
    "runs": [
        "Nostalgie",
        "Chérie FM",
        "Rires et chansons"
    ],
    "address": "e-NRJ\n22 rue Boileau\n75 016 PARIS\nFRANCE",
    "phone": "01 40 71 40 00",
    "web": "https://www.nrj.fr",
    "sources": [
        "https://www.nrj.fr/cgu",
        "https://www.nrj.fr/politique-confidentialite",
        "https://github.com/datenanfragen/data/issues/460"
    ],
    "suggested-transport-medium": "letter",
    "slug": "nrjfr"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%2C%22be%22%2C%22de%22%2C%22at%22%2C%22bg%22%2C%22dk%22%2C%22fi%22%2C%22ge%22%2C%22gr%22%2C%22jo%22%2C%22lb%22%2C%22no%22%2C%22ru%22%2C%22se%22%2C%22ma%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22NRJ%22%2C%22runs%22%3A%5B%22Nostalgie%22%2C%22Ch%C3%A9rie%20FM%22%2C%22Rires%20et%20chansons%22%5D%2C%22address%22%3A%22e-NRJ%5Cn22%20rue%20Boileau%5Cn75%20016%20PARIS%5CnFRANCE%22%2C%22phone%22%3A%2201%2040%2071%2040%2000%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nrj.fr%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nrj.fr%2Fcgu%22%2C%22https%3A%2F%2Fwww.nrj.fr%2Fpolitique-confidentialite%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F460%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22nrjfr%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
