### ISSUE TITLE
New company suggestion: `CINECITTA' Multiplexkino GmbH & Co. KG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#461]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "CINECITTA' Multiplexkino GmbH & Co. KG",
    "address": "c/o Rechtsanwalt Thomas P. Costard\nRechtsanwaltskanzlei Costard\nLina-Ammon-Straße 9\n90471 Nürnberg\nDeutschland",
    "phone": "0911 / 790 30 34",
    "fax": "0911 / 790 30 35",
    "email": "info@it-rechtsberater.de",
    "web": "https://www.cinecitta.de",
    "sources": [
        "https://www.cinecitta.de/de/Datenschutzerklaerung-4889,560649.html",
        "https://github.com/datenanfragen/data/issues/461"
    ],
    "required-elements": [
        {
            "type": "input"
        }
    ],
    "slug": "cinecittade"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22CINECITTA'%20Multiplexkino%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22c%2Fo%20Rechtsanwalt%20Thomas%20P.%20Costard%5CnRechtsanwaltskanzlei%20Costard%5CnLina-Ammon-Stra%C3%9Fe%209%5Cn90471%20N%C3%BCrnberg%5CnDeutschland%22%2C%22phone%22%3A%220911%20%2F%20790%2030%2034%22%2C%22fax%22%3A%220911%20%2F%20790%2030%2035%22%2C%22email%22%3A%22info%40it-rechtsberater.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cinecitta.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cinecitta.de%2Fde%2FDatenschutzerklaerung-4889%2C560649.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F461%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%2C%22slug%22%3A%22cinecittade%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
