### ISSUE TITLE
Suggested update for company `direkta-marketing`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#464]
The following suggestion was submitted through the website:

```
{
    "slug": "direkta-marketing",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads"
    ],
    "name": "Direkta Gesellschaft für Marketing mbH",
    "address": "Hoyendonk 12\n47638 Straelen\nDeuschland",
    "phone": "+49 2834 982614",
    "fax": "+49 2834 7982617",
    "sources": [
        "https://github.com/datenanfragen/data/issues/185",
        "https://github.com/datenanfragen/data/issues/464"
    ],
    "comments": [
        "Geschäftführerin ist möglicherweise identisch mit der Geschäftsführerin von niersbroek12 dot com"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22direkta-marketing%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Direkta%20Gesellschaft%20f%C3%BCr%20Marketing%20mbH%22%2C%22address%22%3A%22Hoyendonk%2012%5Cn47638%20Straelen%5CnDeuschland%22%2C%22phone%22%3A%22%2B49%202834%20982614%22%2C%22fax%22%3A%22%2B49%202834%207982617%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F185%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F464%22%5D%2C%22comments%22%3A%5B%22Gesch%C3%A4ftf%C3%BChrerin%20ist%20m%C3%B6glicherweise%20identisch%20mit%20der%20Gesch%C3%A4ftsf%C3%BChrerin%20von%20niersbroek12%20dot%20com%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks for the note. This detail is more appropriate for the comments section on the website. I have added it as a [there](https://www.datenanfragen.de/company/direkta-marketing).
