### ISSUE TITLE
Replace invalid DigiTrust email address

### ISSUE THREAD

**Issue by m-rey** [datenanfragen/data#465]
The [privacy policy](https://www.digitru.st/privacy-policy/) of DigiTrust lists privacy@digitru.st as a contact email address. However, when sending a request to that email, you get an automatic response with the following content:

> Hello xxxxx@xxxxxxxxxx.xx,
> 
> We're writing to let you know that the group you tried to contact (privacy) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
>  * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/digitru.st/bin/topic.py?topic=25838.
> 
> Thanks,
> 
> digitru.st admins

Thus, the contact email address needs to be replaced in https://github.com/datenanfragen/data/blob/master/companies/digitrust.json#L11
As DigiTrust is now part of [IAB Technology Laboratory](https://iabtechlab.com/), they probably can be contacted instead regarding requests to DigiTrust.

**Comment by danimart1991** [comment]
I would like to take this issue.
