### ISSUE TITLE
New company suggestion: `Ranger Marketing & Vertriebs GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#466]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads",
        "telecommunication"
    ],
    "name": "Ranger Marketing & Vertriebs GmbH",
    "address": "Parsevalstraße 11\n40468 Düsseldorf\nDeutschland",
    "phone": "+49 211 20008300",
    "email": "datenschutz@ranger.de",
    "web": "www.ranger.de",
    "sources": [
        "Unternehmenswebsite",
        "https://github.com/datenanfragen/data/issues/466"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Vertriebspartner der Deutschen Telekom AG.\nBetätigen sich in Haustürgeschäften und Kaltaquise.\nVerkaufen neue teurer Telekommunikationsverträge und Strom- und Gaslieferverträge."
    ],
    "slug": "ranger-marketing-vertriebs-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22Ranger%20Marketing%20%26%20Vertriebs%20GmbH%22%2C%22address%22%3A%22Parsevalstra%C3%9Fe%2011%5Cn40468%20D%C3%BCsseldorf%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20211%2020008300%22%2C%22email%22%3A%22datenschutz%40ranger.de%22%2C%22web%22%3A%22www.ranger.de%22%2C%22sources%22%3A%5B%22Unternehmenswebsite%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F466%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Vertriebspartner%20der%20Deutschen%20Telekom%20AG.%5CnBet%C3%A4tigen%20sich%20in%20Haust%C3%BCrgesch%C3%A4ften%20und%20Kaltaquise.%5CnVerkaufen%20neue%20teurer%20Telekommunikationsvertr%C3%A4ge%20und%20Strom-%20und%20Gasliefervertr%C3%A4ge.%22%5D%2C%22slug%22%3A%22ranger-marketing-vertriebs-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
