### ISSUE TITLE
New company suggestion: `Dreamsoft Infotech`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#467]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "in"
    ],
    "categories": [
        "social media"
    ],
    "name": "Dreamsoft Infotech",
    "address": "A-75, 3rd Floor\nSector - 5, Noida\nUP - 201301 India",
    "phone": "01204380622",
    "email": "seo@wordpressindia.in",
    "web": "http://www.dreamsoftinfotech.com/",
    "sources": [
        "http://www.wordpressindia.in/",
        "https://github.com/datenanfragen/data/issues/467"
    ],
    "slug": "dreamsoftinfotechcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22in%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Dreamsoft%20Infotech%22%2C%22address%22%3A%22A-75%2C%203rd%20Floor%5CnSector%20-%205%2C%20Noida%5CnUP%20-%20201301%20India%22%2C%22phone%22%3A%2201204380622%22%2C%22email%22%3A%22seo%40wordpressindia.in%22%2C%22web%22%3A%22http%3A%2F%2Fwww.dreamsoftinfotech.com%2F%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.wordpressindia.in%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F467%22%5D%2C%22slug%22%3A%22dreamsoftinfotechcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
