### ISSUE TITLE
New company suggestion: `Crystal`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#470]
The following suggestion was submitted through the website:

```
{
    "name": "Crystal",
    "address": "90 Oceanside Dr, Nashville, TN 37204",
    "web": "https://www.crystalknows.com",
    "slug": "crystalknowscom",
    "relevant-countries": [
        "all"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/470"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22name%22%3A%22Crystal%22%2C%22address%22%3A%2290%20Oceanside%20Dr%2C%20Nashville%2C%20TN%2037204%22%2C%22web%22%3A%22https%3A%2F%2Fwww.crystalknows.com%22%2C%22slug%22%3A%22crystalknowscom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F470%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
