### ISSUE TITLE
New company suggestion: `OUTFITTERY GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#471]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de",
        "nl",
        "ch",
        "dk"
    ],
    "name": "OUTFITTERY GmbH",
    "address": "Leuschnerdamm 31\n10999 Berlin",
    "phone": "+49 30 46722431",
    "email": "service@outfittery.de",
    "web": "https://www.outfittery.com/",
    "slug": "outfitterycom",
    "sources": [
        "https://github.com/datenanfragen/data/issues/471"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%2C%22nl%22%2C%22ch%22%2C%22dk%22%5D%2C%22name%22%3A%22OUTFITTERY%20GmbH%22%2C%22address%22%3A%22Leuschnerdamm%2031%5Cn10999%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%2046722431%22%2C%22email%22%3A%22service%40outfittery.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.outfittery.com%2F%22%2C%22slug%22%3A%22outfitterycom%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F471%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
