### ISSUE TITLE
New company suggestion: ` Private Internet Access, Incorporated`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#479]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce"
    ],
    "name": " Private Internet Access, Incorporated",
    "address": "5555 DTC Parkway\nSuite 360\nGreenwood Village, CO 80111\nUnited States (347)586-9467 (Ext. 904)",
    "email": "privacy@privateinternetaccess.com",
    "sources": [
        "https://deu.privateinternetaccess.com/pages/privacy-policy/",
        "https://github.com/datenanfragen/data/issues/479"
    ],
    "slug": "private-internet-access-incorporated"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22%20Private%20Internet%20Access%2C%20Incorporated%22%2C%22address%22%3A%225555%20DTC%20Parkway%5CnSuite%20360%5CnGreenwood%20Village%2C%20CO%2080111%5CnUnited%20States%20(347)586-9467%20(Ext.%20904)%22%2C%22email%22%3A%22privacy%40privateinternetaccess.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdeu.privateinternetaccess.com%2Fpages%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F479%22%5D%2C%22slug%22%3A%22private-internet-access-incorporated%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
