### ISSUE TITLE
New company suggestion: `Cubic Transportation Systems (Deutschland) GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#483]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Cubic Transportation Systems (Deutschland) GmbH",
    "address": "Alter Fischmarkt 11\n20457, Hamburg",
    "phone": "+49 40 300863680",
    "email": "datenschutz@cubic.com",
    "sources": [
        "https://www.cubic-cts.de/impressum",
        "https://github.com/datenanfragen/data/issues/483"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Cubic betreibt Apps für verschiedene ÖPNVs über die man Handytickets kaufen kann."
    ],
    "slug": "cubic-transportation-systems-deutschland-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Cubic%20Transportation%20Systems%20(Deutschland)%20GmbH%22%2C%22address%22%3A%22Alter%20Fischmarkt%2011%5Cn20457%2C%20Hamburg%22%2C%22phone%22%3A%22%2B49%2040%20300863680%22%2C%22email%22%3A%22datenschutz%40cubic.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cubic-cts.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F483%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Cubic%20betreibt%20Apps%20f%C3%BCr%20verschiedene%20%C3%96PNVs%20%C3%BCber%20die%20man%20Handytickets%20kaufen%20kann.%22%5D%2C%22slug%22%3A%22cubic-transportation-systems-deutschland-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
