### ISSUE TITLE
New company suggestion: `Hewlett-Packard Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#486]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Hewlett-Packard Limited",
    "runs": [
        "Aruba"
    ],
    "address": "Amen Corner,\nCain Road,\nBracknell,\nBerkshire,\nRG12 1HN,\nUK",
    "web": "hp.com",
    "slug": "hewlett-packard-limited",
    "sources": [
        "https://github.com/datenanfragen/data/issues/486"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Hewlett-Packard%20Limited%22%2C%22runs%22%3A%5B%22Aruba%22%5D%2C%22address%22%3A%22Amen%20Corner%2C%5CnCain%20Road%2C%5CnBracknell%2C%5CnBerkshire%2C%5CnRG12%201HN%2C%5CnUK%22%2C%22web%22%3A%22hp.com%22%2C%22slug%22%3A%22hewlett-packard-limited%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F486%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
