### ISSUE TITLE
New company suggestion: `Currys PC World`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#488]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "name": "Currys PC World",
    "runs": [
        "Dixons Travel",
        "Team Knowhow"
    ],
    "address": "Dixons Carphone SAR\nPO Box 689\nSALFORD\nM5 OPD",
    "email": "dpo@dixonscarphone.com",
    "web": "www.currys.co.uk",
    "sources": [
        "https://www.currys.co.uk/gbuk/privacy-on-currys-321-commercial.html",
        "https://github.com/datenanfragen/data/issues/488"
    ],
    "needs-id-document": true,
    "slug": "currys-pc-world"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22name%22%3A%22Currys%20PC%20World%22%2C%22runs%22%3A%5B%22Dixons%20Travel%22%2C%22Team%20Knowhow%22%5D%2C%22address%22%3A%22Dixons%20Carphone%20SAR%5CnPO%20Box%20689%5CnSALFORD%5CnM5%20OPD%22%2C%22email%22%3A%22dpo%40dixonscarphone.com%22%2C%22web%22%3A%22www.currys.co.uk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.currys.co.uk%2Fgbuk%2Fprivacy-on-currys-321-commercial.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F488%22%5D%2C%22needs-id-document%22%3Atrue%2C%22slug%22%3A%22currys-pc-world%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
