### ISSUE TITLE
New company suggestion: `Gameforge AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#489]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de",
        "it",
        "fr",
        "es",
        "gb"
    ],
    "categories": [
        "entertainment",
        "ads"
    ],
    "name": "Gameforge AG",
    "address": "Albert-Nestler-Straße 8\n76131 Karlsruhe",
    "phone": "+49 721 3548080",
    "fax": "+49 721 354808152",
    "email": "info@gameforge.com",
    "web": "https://corporate.gameforge.com/?lang=en",
    "sources": [
        "https://corporate.gameforge.com/about/?lang=en",
        "https://github.com/datenanfragen/data/issues/489"
    ],
    "slug": "corporategameforgecom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%2C%22it%22%2C%22fr%22%2C%22es%22%2C%22gb%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22ads%22%5D%2C%22name%22%3A%22Gameforge%20AG%22%2C%22address%22%3A%22Albert-Nestler-Stra%C3%9Fe%208%5Cn76131%20Karlsruhe%22%2C%22phone%22%3A%22%2B49%20721%203548080%22%2C%22fax%22%3A%22%2B49%20721%20354808152%22%2C%22email%22%3A%22info%40gameforge.com%22%2C%22web%22%3A%22https%3A%2F%2Fcorporate.gameforge.com%2F%3Flang%3Den%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fcorporate.gameforge.com%2Fabout%2F%3Flang%3Den%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F489%22%5D%2C%22slug%22%3A%22corporategameforgecom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
