### ISSUE TITLE
New company suggestion: `AstraDirect Leasing & Service GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#490]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "name": "AstraDirect Leasing & Service GmbH",
    "address": "Dudenstr. 46\nD-68167 Mannheim",
    "web": "https://www.astradirect.de/",
    "sources": [
        "https://www.astradirect.de/index.html?p=impressum",
        "https://github.com/datenanfragen/data/issues/490"
    ],
    "slug": "astradirectde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22AstraDirect%20Leasing%20%26%20Service%20GmbH%22%2C%22address%22%3A%22Dudenstr.%2046%5CnD-68167%20Mannheim%22%2C%22web%22%3A%22https%3A%2F%2Fwww.astradirect.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.astradirect.de%2Findex.html%3Fp%3Dimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F490%22%5D%2C%22slug%22%3A%22astradirectde%22%7D)**

**Comment by zner0L** [comment]
Thank yoU!
