### ISSUE TITLE
New company suggestion: `optivel AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#491]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de",
        "ch",
        "fr",
        "at"
    ],
    "name": "optivel AG",
    "runs": [
        "cpx online active AG",
        "Entertainment Media GmbH"
    ],
    "address": "Bahnhofstr. 52\nCH - 8001 Zürich",
    "phone": "+41 44 214 67 65",
    "email": "kontakt@optivel.com",
    "slug": "optivel-ag",
    "sources": [
        "https://github.com/datenanfragen/data/issues/491"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%2C%22ch%22%2C%22fr%22%2C%22at%22%5D%2C%22name%22%3A%22optivel%20AG%22%2C%22runs%22%3A%5B%22cpx%20online%20active%20AG%22%2C%22Entertainment%20Media%20GmbH%22%5D%2C%22address%22%3A%22Bahnhofstr.%2052%5CnCH%20-%208001%20Z%C3%BCrich%22%2C%22phone%22%3A%22%2B41%2044%20214%2067%2065%22%2C%22email%22%3A%22kontakt%40optivel.com%22%2C%22slug%22%3A%22optivel-ag%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F491%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
