### ISSUE TITLE
New company suggestion: `Storex`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#492]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Storex",
    "runs": [
        "PACT Informatique"
    ],
    "address": "33 rue du Ballon\n93160 NOISY-LE-GRAND",
    "phone": "01 55 85 81 81",
    "fax": "01 55 85 81 82",
    "email": "info@storex.eu",
    "web": "https://storex.fr/",
    "sources": [
        "https://storex.fr/mentions-legales/",
        "https://github.com/datenanfragen/data/issues/492"
    ],
    "slug": "storexfr"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Storex%22%2C%22runs%22%3A%5B%22PACT%20Informatique%22%5D%2C%22address%22%3A%2233%20rue%20du%20Ballon%5Cn93160%20NOISY-LE-GRAND%22%2C%22phone%22%3A%2201%2055%2085%2081%2081%22%2C%22fax%22%3A%2201%2055%2085%2081%2082%22%2C%22email%22%3A%22info%40storex.eu%22%2C%22web%22%3A%22https%3A%2F%2Fstorex.fr%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fstorex.fr%2Fmentions-legales%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F492%22%5D%2C%22slug%22%3A%22storexfr%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
