### ISSUE TITLE
New company suggestion: `RocketReach`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#493]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "us"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "RocketReach",
    "address": "RocketReach\n135 100th Ave NE\nBellevue, WA 98004",
    "phone": "+1 415 669 0604",
    "email": "privacy@rocketreach.co",
    "web": "rocketreach.co",
    "sources": [
        "https://rocketreach.co/gdpr",
        "https://rocketreach.co/privacy",
        "https://github.com/datenanfragen/data/issues/493"
    ],
    "suggested-transport-medium": "email",
    "slug": "rocketreach"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22us%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22RocketReach%22%2C%22address%22%3A%22RocketReach%5Cn135%20100th%20Ave%20NE%5CnBellevue%2C%20WA%2098004%22%2C%22phone%22%3A%22%2B1%20415%20669%200604%22%2C%22email%22%3A%22privacy%40rocketreach.co%22%2C%22web%22%3A%22rocketreach.co%22%2C%22sources%22%3A%5B%22https%3A%2F%2Frocketreach.co%2Fgdpr%22%2C%22https%3A%2F%2Frocketreach.co%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F493%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22rocketreach%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
