### ISSUE TITLE
New company suggestion: `AIRARABIA MAROC`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#494]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "ma"
    ],
    "categories": [
        "travel"
    ],
    "name": "AIRARABIA MAROC",
    "address": "4 Rue de Carthage\nQuartier les Iris\nCasablanca\nMaroc",
    "phone": "+212 5225 36400",
    "fax": "+212 5229 50326",
    "email": "contactus@airarabia.com",
    "web": "airarabia.com",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "airarabia-maroc",
    "sources": [
        "https://github.com/datenanfragen/data/issues/494"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22ma%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22AIRARABIA%20MAROC%22%2C%22address%22%3A%224%20Rue%20de%20Carthage%5CnQuartier%20les%20Iris%5CnCasablanca%5CnMaroc%22%2C%22phone%22%3A%22%2B212%205225%2036400%22%2C%22fax%22%3A%22%2B212%205229%2050326%22%2C%22email%22%3A%22contactus%40airarabia.com%22%2C%22web%22%3A%22airarabia.com%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22airarabia-maroc%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F494%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
