### ISSUE TITLE
New company suggestion: `Giebel und Kollegen `

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#495]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "Giebel und Kollegen ",
    "address": "Stresemannstraße 60 \n28207 Bremen",
    "phone": "+49 421 22310516",
    "email": "kanzlei@giebel.de",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/495"
    ],
    "slug": "giebel-und-kollegen"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22Giebel%20und%20Kollegen%20%22%2C%22address%22%3A%22Stresemannstra%C3%9Fe%2060%20%5Cn28207%20Bremen%22%2C%22phone%22%3A%22%2B49%20421%2022310516%22%2C%22email%22%3A%22kanzlei%40giebel.de%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F495%22%5D%2C%22slug%22%3A%22giebel-und-kollegen%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
