### ISSUE TITLE
New company suggestion: `HelloWork SASU`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#496]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "name": "HelloWork SASU",
    "address": "2, rue de la Mabilais\n35000 RENNES",
    "phone": "02 23 44 80 44",
    "fax": "02 23 44 80 45",
    "email": "contact@regionsjob.com",
    "web": "www.regionsjob.com",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "hellowork-sasu",
    "sources": [
        "https://github.com/datenanfragen/data/issues/496"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22name%22%3A%22HelloWork%20SASU%22%2C%22address%22%3A%222%2C%20rue%20de%20la%20Mabilais%5Cn35000%20RENNES%22%2C%22phone%22%3A%2202%2023%2044%2080%2044%22%2C%22fax%22%3A%2202%2023%2044%2080%2045%22%2C%22email%22%3A%22contact%40regionsjob.com%22%2C%22web%22%3A%22www.regionsjob.com%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22hellowork-sasu%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F496%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
