### ISSUE TITLE
New company suggestion: `Alecto GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#497]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "insurance",
        "finance"
    ],
    "name": "Alecto GmbH",
    "runs": [
        "Friendsurance.de"
    ],
    "address": "Alecto GmbH (Friendsurance)\nMehringdamm 34\n10961 Berlin\nDeutschland",
    "phone": "0800 087 088 0",
    "email": "datenschutz@friendsurance.de",
    "web": "https://www.friendsurance.de/",
    "sources": [
        "https://www.friendsurance.de/datenschutz-allgemein",
        "https://github.com/datenanfragen/data/issues/497"
    ],
    "required-elements": [
        {
            "desc": "Email/LOgin",
            "type": "email",
            "optional": false
        }
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Alternative Anschrift Datenschutzbeauftragter lt. Datenschutzerklärung:\nGregor Klar\nHoltzendorffstraße 20\n14057 Berlin\nDeutschland"
    ],
    "slug": "friendsurancede"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%2C%22finance%22%5D%2C%22name%22%3A%22Alecto%20GmbH%22%2C%22runs%22%3A%5B%22Friendsurance.de%22%5D%2C%22address%22%3A%22Alecto%20GmbH%20(Friendsurance)%5CnMehringdamm%2034%5Cn10961%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%220800%20087%20088%200%22%2C%22email%22%3A%22datenschutz%40friendsurance.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.friendsurance.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.friendsurance.de%2Fdatenschutz-allgemein%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F497%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%2FLOgin%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Alternative%20Anschrift%20Datenschutzbeauftragter%20lt.%20Datenschutzerkl%C3%A4rung%3A%5CnGregor%20Klar%5CnHoltzendorffstra%C3%9Fe%2020%5Cn14057%20Berlin%5CnDeutschland%22%5D%2C%22slug%22%3A%22friendsurancede%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
