### ISSUE TITLE
New company suggestion: `Zattoo.com`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#498]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de",
        "at",
        "ch"
    ],
    "categories": [
        "entertainment",
        "social media"
    ],
    "name": "Zattoo.com",
    "address": "Zattoo Europa AG\nDatenschutzbeauftragte_r\nBaslerstrasse 60\nCH-8048 Zürich\nSchweiz",
    "phone": "+41 43 500 21 00",
    "fax": "+41 43 500 21 11",
    "email": "datenschutz@zattoo.com",
    "web": "https://zattoo.com/",
    "sources": [
        "https://zattoo.com/company/privacy/",
        "https://github.com/datenanfragen/data/issues/498"
    ],
    "required-elements": [
        {
            "desc": "Nutzername",
            "type": "textarea",
            "optional": false
        }
    ],
    "suggested-transport-medium": "email",
    "slug": "zattoocom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Zattoo.com%22%2C%22address%22%3A%22Zattoo%20Europa%20AG%5CnDatenschutzbeauftragte_r%5CnBaslerstrasse%2060%5CnCH-8048%20Z%C3%BCrich%5CnSchweiz%22%2C%22phone%22%3A%22%2B41%2043%20500%2021%2000%22%2C%22fax%22%3A%22%2B41%2043%20500%2021%2011%22%2C%22email%22%3A%22datenschutz%40zattoo.com%22%2C%22web%22%3A%22https%3A%2F%2Fzattoo.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fzattoo.com%2Fcompany%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F498%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Nutzername%22%2C%22type%22%3A%22textarea%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22zattoocom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
