### ISSUE TITLE
New company suggestion: `BGL Inkasso UG (haftungsbeschränkt)`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#499]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "BGL Inkasso UG (haftungsbeschränkt)",
    "address": "Marktplatz 22\nD-72250 Freudenstadt\nGermany",
    "phone": "074415290092",
    "email": "info@bgl-inkasso.de",
    "web": "https://www.bgl-inkasso.de",
    "slug": "bgl-inkassode",
    "sources": [
        "https://github.com/datenanfragen/data/issues/499"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22BGL%20Inkasso%20UG%20(haftungsbeschr%C3%A4nkt)%22%2C%22address%22%3A%22Marktplatz%2022%5CnD-72250%20Freudenstadt%5CnGermany%22%2C%22phone%22%3A%22074415290092%22%2C%22email%22%3A%22info%40bgl-inkasso.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bgl-inkasso.de%22%2C%22slug%22%3A%22bgl-inkassode%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F499%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
