### ISSUE TITLE
New company suggestion: `McDonald's Deutschland LLC`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#500]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "McDonald's Deutschland LLC",
    "address": "Datenschutzbeauftragter\nDrygalski-Allee 51\n81477 München\nDeutschland",
    "email": "datenschutz@de.mcd.com",
    "web": "https://www.mcdonalds.com/de/",
    "sources": [
        "https://www.mcdonalds.com/de/de-de/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/500"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Could have information about you, if you use their app for discount and coupons. You can even enable an option for personalized coupons. So they must have some data about you.\n\nAlso if you took part raffles, they might have data about you."
    ],
    "slug": "mcdonaldscom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22McDonald's%20Deutschland%20LLC%22%2C%22address%22%3A%22Datenschutzbeauftragter%5CnDrygalski-Allee%2051%5Cn81477%20M%C3%BCnchen%5CnDeutschland%22%2C%22email%22%3A%22datenschutz%40de.mcd.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mcdonalds.com%2Fde%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mcdonalds.com%2Fde%2Fde-de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F500%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Could%20have%20information%20about%20you%2C%20if%20you%20use%20their%20app%20for%20discount%20and%20coupons.%20You%20can%20even%20enable%20an%20option%20for%20personalized%20coupons.%20So%20they%20must%20have%20some%20data%20about%20you.%5Cn%5CnAlso%20if%20you%20took%20part%20raffles%2C%20they%20might%20have%20data%20about%20you.%22%5D%2C%22slug%22%3A%22mcdonaldscom%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
