### ISSUE TITLE
New company suggestion: `mmf-ug`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#501]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "addresses",
        "finance"
    ],
    "name": "mmf-ug",
    "address": "Hauptstraße 134\n51143 Köln",
    "phone": "02174 – 71480 00",
    "fax": "02174 – 71480 01",
    "email": "kontakt@mmf-ug.de",
    "web": "http://mmf-ug.de",
    "slug": "mmf-ugde",
    "sources": [
        "https://github.com/datenanfragen/data/issues/501"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%2C%22finance%22%5D%2C%22name%22%3A%22mmf-ug%22%2C%22address%22%3A%22Hauptstra%C3%9Fe%20134%5Cn51143%20K%C3%B6ln%22%2C%22phone%22%3A%2202174%20%E2%80%93%2071480%2000%22%2C%22fax%22%3A%2202174%20%E2%80%93%2071480%2001%22%2C%22email%22%3A%22kontakt%40mmf-ug.de%22%2C%22web%22%3A%22http%3A%2F%2Fmmf-ug.de%22%2C%22slug%22%3A%22mmf-ugde%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F501%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
