### ISSUE TITLE
New company suggestion: `GIS Gebühren Info Service GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#505]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "telecommunication",
        "public body",
        "utility"
    ],
    "name": "GIS Gebühren Info Service GmbH",
    "address": "GIS Gebühren Info Service GmbH\nOperngasse 20 B, 1040 Wien",
    "phone": "+43 50 200",
    "fax": "+43 50 200 DW 300",
    "email": "kundenservice@gis.at",
    "web": "https://www.gis.at",
    "sources": [
        "https://www.gis.at/impressum",
        "https://github.com/datenanfragen/data/issues/505"
    ],
    "slug": "gisat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22public%20body%22%2C%22utility%22%5D%2C%22name%22%3A%22GIS%20Geb%C3%BChren%20Info%20Service%20GmbH%22%2C%22address%22%3A%22GIS%20Geb%C3%BChren%20Info%20Service%20GmbH%5CnOperngasse%2020%20B%2C%201040%20Wien%22%2C%22phone%22%3A%22%2B43%2050%20200%22%2C%22fax%22%3A%22%2B43%2050%20200%20DW%20300%22%2C%22email%22%3A%22kundenservice%40gis.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gis.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gis.at%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F505%22%5D%2C%22slug%22%3A%22gisat%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
