### ISSUE TITLE
New company suggestion: `WINDATEN`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#506]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "addresses"
    ],
    "name": "WINDATEN",
    "address": "Nelkenstraße 2\n71723 Großbottwar\nDeutschland",
    "phone": "+49 7148 1637171",
    "email": "win-daten@t-online.de",
    "sources": [
        "http://win-daten.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/506"
    ],
    "slug": "windaten"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22WINDATEN%22%2C%22address%22%3A%22Nelkenstra%C3%9Fe%202%5Cn71723%20Gro%C3%9Fbottwar%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%207148%201637171%22%2C%22email%22%3A%22win-daten%40t-online.de%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwin-daten.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F506%22%5D%2C%22slug%22%3A%22windaten%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
