### ISSUE TITLE
New company suggestion: `Assurant Deutschland GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#507]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "insurance"
    ],
    "name": "Assurant Deutschland GmbH",
    "address": "Lyoner Straße 15 \n60528 Frankfurt am Main \nDeutschland ",
    "phone": "+49 69 6657580",
    "fax": "+49 69 66164867",
    "email": "info@assurantsolutions.de ",
    "web": "https://www.assurant.de/",
    "sources": [
        "https://www.assurant.de/impressum",
        "https://github.com/datenanfragen/data/issues/507"
    ],
    "comments": [
        "Datenschutzerklärung auf der Website zZt nicht erreichbar."
    ],
    "slug": "assurantde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Assurant%20Deutschland%20GmbH%22%2C%22address%22%3A%22Lyoner%20Stra%C3%9Fe%2015%20%5Cn60528%20Frankfurt%20am%20Main%20%5CnDeutschland%20%22%2C%22phone%22%3A%22%2B49%2069%206657580%22%2C%22fax%22%3A%22%2B49%2069%2066164867%22%2C%22email%22%3A%22info%40assurantsolutions.de%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.assurant.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.assurant.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F507%22%5D%2C%22comments%22%3A%5B%22Datenschutzerkl%C3%A4rung%20auf%20der%20Website%20zZt%20nicht%20erreichbar.%22%5D%2C%22slug%22%3A%22assurantde%22%7D)**

**Comment by baltpeter** [comment]
Thanks!

**Comment by WebworkrNet** [comment]
Since the data protection declaration is still not available today and no one in the company has noticed this fact after such a long time, I have now pointed this fact out to the North Rhine-Westphalia State Data Protection Officer.
