### ISSUE TITLE
New company suggestion: `BKK VerbundPlus`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#508]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "insurance",
        "health"
    ],
    "name": "BKK VerbundPlus",
    "address": "Andreas Röger\nBKK VerbundPlus\nZeppelinring 13\n88400 Biberach ",
    "phone": "+49 7351 18240",
    "email": "datenschutz@bkkvp.de",
    "web": "https://www.bkk-verbundplus.de/",
    "sources": [
        "https://www.bkk-verbundplus.de/unternehmen/datenschutz/datenschutzerklaerung",
        "https://github.com/datenanfragen/data/issues/508"
    ],
    "slug": "bkk-verbundplusde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%2C%22health%22%5D%2C%22name%22%3A%22BKK%20VerbundPlus%22%2C%22address%22%3A%22Andreas%20R%C3%B6ger%5CnBKK%20VerbundPlus%5CnZeppelinring%2013%5Cn88400%20Biberach%20%22%2C%22phone%22%3A%22%2B49%207351%2018240%22%2C%22email%22%3A%22datenschutz%40bkkvp.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bkk-verbundplus.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bkk-verbundplus.de%2Funternehmen%2Fdatenschutz%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F508%22%5D%2C%22slug%22%3A%22bkk-verbundplusde%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
