### ISSUE TITLE
New company suggestion: `LAREM`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#509]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "political party"
    ],
    "name": "LAREM",
    "runs": [
        "LA REPUBLIQUE EN MARCHE"
    ],
    "address": "63, rue Sainte-Anne \n75002 Paris",
    "email": "dpo@en-marche.fr",
    "web": "https://en-marche.fr/",
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "en-marchefr",
    "sources": [
        "https://github.com/datenanfragen/data/issues/509"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22political%20party%22%5D%2C%22name%22%3A%22LAREM%22%2C%22runs%22%3A%5B%22LA%20REPUBLIQUE%20EN%20MARCHE%22%5D%2C%22address%22%3A%2263%2C%20rue%20Sainte-Anne%20%5Cn75002%20Paris%22%2C%22email%22%3A%22dpo%40en-marche.fr%22%2C%22web%22%3A%22https%3A%2F%2Fen-marche.fr%2F%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22en-marchefr%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F509%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
