### ISSUE TITLE
New company suggestion: `food.de`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#510]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "utility"
    ],
    "name": "food.de",
    "runs": [
        "food direkt GmbH"
    ],
    "address": "Spohrstraße 10, 04103 Leipzig",
    "phone": "0341-26375011",
    "email": "einkaufen@food.de",
    "web": "https://food.de",
    "required-elements": [
        {
            "type": "input"
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "foodde",
    "sources": [
        "https://github.com/datenanfragen/data/issues/510"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22food.de%22%2C%22runs%22%3A%5B%22food%20direkt%20GmbH%22%5D%2C%22address%22%3A%22Spohrstra%C3%9Fe%2010%2C%2004103%20Leipzig%22%2C%22phone%22%3A%220341-26375011%22%2C%22email%22%3A%22einkaufen%40food.de%22%2C%22web%22%3A%22https%3A%2F%2Ffood.de%22%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22foodde%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F510%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
