### ISSUE TITLE
New company suggestion: `PERM4 | Permanent Recruiting GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#511]
The following suggestion was submitted through the website:

```
{
    "categories": [
        "finance"
    ],
    "name": "PERM4 | Permanent Recruiting GmbH",
    "address": "Lindencorso – Unter den Linden 21\n10117 Berlin",
    "phone": "+49 30 333063100",
    "fax": "+49 30 333063149",
    "email": "info@perm4.com",
    "web": "https://www.perm4.com/",
    "sources": [
        "https://www.perm4.com/impressum/",
        "https://github.com/datenanfragen/data/issues/511"
    ],
    "slug": "perm4com",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22PERM4%20%7C%20Permanent%20Recruiting%20GmbH%22%2C%22address%22%3A%22Lindencorso%20%E2%80%93%20Unter%20den%20Linden%2021%5Cn10117%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%20333063100%22%2C%22fax%22%3A%22%2B49%2030%20333063149%22%2C%22email%22%3A%22info%40perm4.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.perm4.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.perm4.com%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F511%22%5D%2C%22slug%22%3A%22perm4com%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
