### ISSUE TITLE
New company suggestion: `RWE Power AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#512]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "utility"
    ],
    "name": "RWE Power AG",
    "runs": [
        "Kohlekraftwerke"
    ],
    "email": "datenschutz@rwe.com",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/512"
    ],
    "slug": "rwe-power-ag"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22RWE%20Power%20AG%22%2C%22runs%22%3A%5B%22Kohlekraftwerke%22%5D%2C%22email%22%3A%22datenschutz%40rwe.com%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F512%22%5D%2C%22slug%22%3A%22rwe-power-ag%22%7D)**

**Comment by baltpeter** [comment]
From the [group.rwe privacy policy](https://www.group.rwe/datenschutz), it seems like RWE AG is the privacy contact for all related companies, so I'll merge this with #513.
