### ISSUE TITLE
New company suggestion: `Polizeipräsidium Aachen`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#514]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "public body"
    ],
    "name": "Polizeipräsidium Aachen",
    "address": "Trierer Str. 501, 52078 Aachen",
    "sources": [
        "https://www.neues-deutschland.de/artikel/1132465.hambacher-forst-polizei-uebermittelte-daten-an-rwe-ohne-rechtsgrundlage.html",
        "https://github.com/datenanfragen/data/issues/514"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "comments": [
        "Das Polizeipräsidium Aachen hat personenbezogene Daten von UmweltaktivistInnen an die RWE Power AG weitergeleitet. \n\nDadurch ist die Einleitung von zahlreichen Abmahnungen bzw. Ermittlungsverfahren erst ermöglicht worden."
    ],
    "slug": "polizeiprsidium-aachen"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Polizeipr%C3%A4sidium%20Aachen%22%2C%22address%22%3A%22Trierer%20Str.%20501%2C%2052078%20Aachen%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.neues-deutschland.de%2Fartikel%2F1132465.hambacher-forst-polizei-uebermittelte-daten-an-rwe-ohne-rechtsgrundlage.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F514%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22Das%20Polizeipr%C3%A4sidium%20Aachen%20hat%20personenbezogene%20Daten%20von%20UmweltaktivistInnen%20an%20die%20RWE%20Power%20AG%20weitergeleitet.%20%5Cn%5CnDadurch%20ist%20die%20Einleitung%20von%20zahlreichen%20Abmahnungen%20bzw.%20Ermittlungsverfahren%20erst%20erm%C3%B6glicht%20worden.%22%5D%2C%22slug%22%3A%22polizeiprsidium-aachen%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
