### ISSUE TITLE
New company suggestion: `DTM Deutsche Tele Medien GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#515]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "addresses",
        "telecommunication"
    ],
    "name": "DTM Deutsche Tele Medien GmbH",
    "address": "Wiesenhüttenstr. 18\n60329 Frankfurt\nDeutschland",
    "phone": "+49 69 26820",
    "fax": "+49 69 6821101",
    "email": "datenschutz@dtme.de",
    "web": "https://www.dastelefonbuch.de/",
    "sources": [
        "https://www.dastelefonbuch.de/Datenschutz",
        "https://github.com/datenanfragen/data/issues/515"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Addresse",
            "type": "address"
        }
    ],
    "suggested-transport-medium": "email",
    "slug": "dastelefonbuchde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22DTM%20Deutsche%20Tele%20Medien%20GmbH%22%2C%22address%22%3A%22Wiesenh%C3%BCttenstr.%2018%5Cn60329%20Frankfurt%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2069%2026820%22%2C%22fax%22%3A%22%2B49%2069%206821101%22%2C%22email%22%3A%22datenschutz%40dtme.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dastelefonbuch.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dastelefonbuch.de%2FDatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F515%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Addresse%22%2C%22type%22%3A%22address%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22dastelefonbuchde%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
