### ISSUE TITLE
New company suggestion: `TT Online Marketing GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#516]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads"
    ],
    "name": "TT Online Marketing GmbH",
    "runs": [
        "http://special24-angebote.de",
        "http://top24-angebote.de"
    ],
    "address": "Josef-Göres-Platz 2\n56068 Koblenz",
    "phone": "+49 261 45099419",
    "email": "datenschutz@trusted-traffic.de",
    "web": "http://www.trusted-traffic.de",
    "sources": [
        "https://trusted-traffic.de/datenschutz",
        "https://trusted-traffic.de/impressum",
        "https://github.com/datenanfragen/data/issues/516"
    ],
    "required-elements": [
        {
            "type": "input"
        }
    ],
    "needs-id-document": false,
    "comments": [
        "Schnelle und vorbildliche Reaktion des Betreibers"
    ],
    "slug": "trusted-trafficde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22TT%20Online%20Marketing%20GmbH%22%2C%22runs%22%3A%5B%22http%3A%2F%2Fspecial24-angebote.de%22%2C%22http%3A%2F%2Ftop24-angebote.de%22%5D%2C%22address%22%3A%22Josef-G%C3%B6res-Platz%202%5Cn56068%20Koblenz%22%2C%22phone%22%3A%22%2B49%20261%2045099419%22%2C%22email%22%3A%22datenschutz%40trusted-traffic.de%22%2C%22web%22%3A%22http%3A%2F%2Fwww.trusted-traffic.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ftrusted-traffic.de%2Fdatenschutz%22%2C%22https%3A%2F%2Ftrusted-traffic.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F516%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22comments%22%3A%5B%22Schnelle%20und%20vorbildliche%20Reaktion%20des%20Betreibers%22%5D%2C%22slug%22%3A%22trusted-trafficde%22%7D)**

**Comment by baltpeter** [comment]
Thank you!

**Comment by WebworkrNet** [comment]
All latest changes including this ticket will be visible only after a central website update? Thanks

**Comment by baltpeter** [comment]
Exactly. All changes are deployed automatically but it usually takes 15 to 20 minutes for a full website build. These changes are now live.

You can always see the status of all deploys here: https://app.netlify.com/sites/datenanfragen/deploys?filter=master

**Comment by WebworkrNet** [comment]
Hello Benjamin,

thanks for your reply and considering my suggestion for updating your company database.

Kind regards

Denis Müller


Benjamin Altpeter schrieb am 14. Feb 2020 13:04 (GMT +01:00):
