### ISSUE TITLE
New company suggestion: `ÖBB-Personenverkehr AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#517]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "name": "ÖBB-Personenverkehr AG",
    "address": "Am Hauptbahnhof 2\n1100 Wien",
    "phone": "+43 1 930000",
    "email": "datenschutz.personenverkehr@pv.oebb.at",
    "web": "https://www.oebb.at",
    "sources": [
        "https://www.oebb.at/static/tarife/de/datenschutzerklaerung/index.html",
        "https://personenverkehr.oebb.at/de/personenverkehr/impressum",
        "https://www.oebb.at/de/reiseplanung-services/kundenservice",
        "https://github.com/datenanfragen/data/issues/517"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail-Adresse",
            "type": "email"
        }
    ],
    "suggested-transport-medium": "email",
    "slug": "oebbat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22name%22%3A%22%C3%96BB-Personenverkehr%20AG%22%2C%22address%22%3A%22Am%20Hauptbahnhof%202%5Cn1100%20Wien%22%2C%22phone%22%3A%22%2B43%201%20930000%22%2C%22email%22%3A%22datenschutz.personenverkehr%40pv.oebb.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.oebb.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.oebb.at%2Fstatic%2Ftarife%2Fde%2Fdatenschutzerklaerung%2Findex.html%22%2C%22https%3A%2F%2Fpersonenverkehr.oebb.at%2Fde%2Fpersonenverkehr%2Fimpressum%22%2C%22https%3A%2F%2Fwww.oebb.at%2Fde%2Freiseplanung-services%2Fkundenservice%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F517%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail-Adresse%22%2C%22type%22%3A%22email%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22oebbat%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
