### ISSUE TITLE
New company suggestion: `McDonald's Werbegesellschaft mbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#518]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "commerce"
    ],
    "name": "McDonald's Werbegesellschaft mbH",
    "address": "Campus 21\nLiebermannstrasse, A01601\n2345 Brunn am Gebirge \nÖsterreich",
    "phone": "+43 2236 30700",
    "email": "datenschutz@at.mcd.com",
    "web": "https://www.mcdonalds.at/",
    "sources": [
        "https://www.mcdonalds.at/kontakt",
        "https://www.mcdonalds.at/datenschutz#oesterreich",
        "https://www.mcdonalds.at/impressum",
        "https://corporate.mcdonalds.com/corpmcd/gdpr-rights-center.html",
        "https://github.com/datenanfragen/data/issues/518"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail-Adresse",
            "type": "email"
        }
    ],
    "suggested-transport-medium": "email",
    "slug": "mcdonaldsat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22McDonald's%20Werbegesellschaft%20mbH%22%2C%22address%22%3A%22Campus%2021%5CnLiebermannstrasse%2C%20A01601%5Cn2345%20Brunn%20am%20Gebirge%20%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%202236%2030700%22%2C%22email%22%3A%22datenschutz%40at.mcd.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mcdonalds.at%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mcdonalds.at%2Fkontakt%22%2C%22https%3A%2F%2Fwww.mcdonalds.at%2Fdatenschutz%23oesterreich%22%2C%22https%3A%2F%2Fwww.mcdonalds.at%2Fimpressum%22%2C%22https%3A%2F%2Fcorporate.mcdonalds.com%2Fcorpmcd%2Fgdpr-rights-center.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F518%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail-Adresse%22%2C%22type%22%3A%22email%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22mcdonaldsat%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
