### ISSUE TITLE
New company suggestion: `Payoneer Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#519]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "finance"
    ],
    "name": "Payoneer Inc.",
    "address": "150 West 30th Street, Suite 600, New York, NY, 10001",
    "phone": "1-800-251-2521",
    "email": "CustomerServiceManager@Payoneer.com",
    "web": "payoneer.com",
    "comments": [
        "please add company in your database"
    ],
    "slug": "payoneer-inc",
    "sources": [
        "https://github.com/datenanfragen/data/issues/519"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Payoneer%20Inc.%22%2C%22address%22%3A%22150%20West%2030th%20Street%2C%20Suite%20600%2C%20New%20York%2C%20NY%2C%2010001%22%2C%22phone%22%3A%221-800-251-2521%22%2C%22email%22%3A%22CustomerServiceManager%40Payoneer.com%22%2C%22web%22%3A%22payoneer.com%22%2C%22comments%22%3A%5B%22please%20add%20company%20in%20your%20database%22%5D%2C%22slug%22%3A%22payoneer-inc%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F519%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
