### ISSUE TITLE
New company suggestion: `Movie Park Germany GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#520]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Movie Park Germany GmbH",
    "address": "Warner-Allee 1\n46244 Bottrop",
    "email": "hr@moviepark.de",
    "web": "https://www.movieparkgermany.de",
    "sources": [
        "https://www.movieparkgermany.de/impressum",
        "https://github.com/datenanfragen/data/issues/520"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "movieparkgermanyde"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Movie%20Park%20Germany%20GmbH%22%2C%22address%22%3A%22Warner-Allee%201%5Cn46244%20Bottrop%22%2C%22email%22%3A%22hr%40moviepark.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.movieparkgermany.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.movieparkgermany.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F520%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22movieparkgermanyde%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
