### ISSUE TITLE
New company suggestion: `Urkund`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#521]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "se",
        "us"
    ],
    "name": "Urkund",
    "address": "\nVisit us at:\n\nGustavslundsvägen 135\nSE-167 51 Bromma\nSweden\nPostal address:\n\nUrkund | Prio Infocenter AB\nBox 15120\nSE-167 15 Bromma\nSweden\n",
    "phone": "+46 8 738 52 10",
    "email": "support@urkund.com",
    "web": "https://www.urkund.com/",
    "sources": [
        "https://www.urkund.com/contact-us/",
        "https://github.com/datenanfragen/data/issues/521"
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "email",
    "slug": "urkundcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22se%22%2C%22us%22%5D%2C%22name%22%3A%22Urkund%22%2C%22address%22%3A%22%5CnVisit%20us%20at%3A%5Cn%5CnGustavslundsv%C3%A4gen%20135%5CnSE-167%2051%20Bromma%5CnSweden%5CnPostal%20address%3A%5Cn%5CnUrkund%20%7C%20Prio%20Infocenter%20AB%5CnBox%2015120%5CnSE-167%2015%20Bromma%5CnSweden%5Cn%22%2C%22phone%22%3A%22%2B46%208%20738%2052%2010%22%2C%22email%22%3A%22support%40urkund.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.urkund.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.urkund.com%2Fcontact-us%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F521%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22urkundcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
