### ISSUE TITLE
New company suggestion: `Sonoma Internet GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#522]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Sonoma Internet GmbH",
    "runs": [
        "amorelie.de"
    ],
    "address": "Wattstraße 11-13\n13355 Berlin \nDeutschland",
    "phone": "+49 30 20847388",
    "email": "datenschutz@amorelie.com",
    "web": "https://www.amorelie.de/",
    "sources": [
        "https://www.amorelie.de/",
        "https://github.com/datenanfragen/data/issues/522"
    ],
    "slug": "amoreliede"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Sonoma%20Internet%20GmbH%22%2C%22runs%22%3A%5B%22amorelie.de%22%5D%2C%22address%22%3A%22Wattstra%C3%9Fe%2011-13%5Cn13355%20Berlin%20%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2020847388%22%2C%22email%22%3A%22datenschutz%40amorelie.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.amorelie.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.amorelie.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F522%22%5D%2C%22slug%22%3A%22amoreliede%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
