### ISSUE TITLE
New company suggestion: `EXCLUSIV Marketing GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#524]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "EXCLUSIV Marketing GmbH",
    "address": "Kistlerhofstr. 170\n81379 München\nDeutschland",
    "phone": "089 21129188",
    "email": "info@kioskpresse.de",
    "web": "www.kioskpresse.de",
    "sources": [
        "https://kioskpresse.de/",
        "https://github.com/datenanfragen/data/issues/524"
    ],
    "slug": "exclusiv-marketing-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22EXCLUSIV%20Marketing%20GmbH%22%2C%22address%22%3A%22Kistlerhofstr.%20170%5Cn81379%20M%C3%BCnchen%5CnDeutschland%22%2C%22phone%22%3A%22089%2021129188%22%2C%22email%22%3A%22info%40kioskpresse.de%22%2C%22web%22%3A%22www.kioskpresse.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fkioskpresse.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F524%22%5D%2C%22slug%22%3A%22exclusiv-marketing-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
