### ISSUE TITLE
Suggested update for company `ifttt`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#525]
The following suggestion was submitted through the website:

```
{
    "slug": "ifttt",
    "relevant-countries": [
        "all"
    ],
    "name": "IFTTT Inc.",
    "address": "923 Market Street\nSuite #400\nSan Francisco\nCA 94103\nUnited States of America",
    "phone": "+49 40 999993430",
    "fax": "+49 40 999993332",
    "email": "IFTTT@gdpr-rep.com",
    "web": "https://ifttt.com/",
    "sources": [
        "https://ifttt.com/terms",
        "https://github.com/datenanfragen/data/issues/212",
        "https://github.com/datenanfragen/data/issues/525"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Emails sent to privacy@ifttt.com gets the following response:\nWe don't monitor emails sent directly to this email address unless they have to do with copyright issues, and we won't be able to respond to this email. Don't worry though, we still want to make sure you get the support you need. "
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ifttt%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22IFTTT%20Inc.%22%2C%22address%22%3A%22923%20Market%20Street%5CnSuite%20%23400%5CnSan%20Francisco%5CnCA%2094103%5CnUnited%20States%20of%20America%22%2C%22phone%22%3A%22%2B49%2040%20999993430%22%2C%22fax%22%3A%22%2B49%2040%20999993332%22%2C%22email%22%3A%22IFTTT%40gdpr-rep.com%22%2C%22web%22%3A%22https%3A%2F%2Fifttt.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fifttt.com%2Fterms%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F212%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F525%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Emails%20sent%20to%20privacy%40ifttt.com%20gets%20the%20following%20response%3A%5CnWe%20don't%20monitor%20emails%20sent%20directly%20to%20this%20email%20address%20unless%20they%20have%20to%20do%20with%20copyright%20issues%2C%20and%20we%20won't%20be%20able%20to%20respond%20to%20this%20email.%20Don't%20worry%20though%2C%20we%20still%20want%20to%20make%20sure%20you%20get%20the%20support%20you%20need.%20%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks, I'll update the record. Curiously enough, they still list privacy@ifttt.com in their privacy policy…
