### ISSUE TITLE
New company suggestion: `M-Industry Germany`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#526]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce"
    ],
    "name": "M-Industry Germany",
    "runs": [
        "Café Royal",
        "Delica AG"
    ],
    "address": "Rudolf-Diesel-Strasse 24\n64625 Bensheim\nDeutschland",
    "phone": "+41 61 315 77 88",
    "email": "datenschutz@delica.ch",
    "web": "delica.ch",
    "sources": [
        "https://www.cafe-royal.com/de-ch/s/datenschutzbestimmungen",
        "https://www.delica.ch/-/media/delica/files/Datenschutz/Datenschutzerklrung_Delica_DE.ashx?la=de",
        "https://github.com/datenanfragen/data/issues/526"
    ],
    "slug": "m-industry-germany"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22M-Industry%20Germany%22%2C%22runs%22%3A%5B%22Caf%C3%A9%20Royal%22%2C%22Delica%20AG%22%5D%2C%22address%22%3A%22Rudolf-Diesel-Strasse%2024%5Cn64625%20Bensheim%5CnDeutschland%22%2C%22phone%22%3A%22%2B41%2061%20315%2077%2088%22%2C%22email%22%3A%22datenschutz%40delica.ch%22%2C%22web%22%3A%22delica.ch%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cafe-royal.com%2Fde-ch%2Fs%2Fdatenschutzbestimmungen%22%2C%22https%3A%2F%2Fwww.delica.ch%2F-%2Fmedia%2Fdelica%2Ffiles%2FDatenschutz%2FDatenschutzerklrung_Delica_DE.ashx%3Fla%3Dde%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F526%22%5D%2C%22slug%22%3A%22m-industry-germany%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
