### ISSUE TITLE
New company suggestion: `contactout.com`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#527]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "contactout.com",
    "address": "contactout.com",
    "sources": [
        "contactout.com",
        "https://github.com/datenanfragen/data/issues/527"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "contactoutcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22contactout.com%22%2C%22address%22%3A%22contactout.com%22%2C%22sources%22%3A%5B%22contactout.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F527%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22contactoutcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
