### ISSUE TITLE
New company suggestion: `Raunak Group`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#528]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "in"
    ],
    "categories": [
        "public body"
    ],
    "name": "Raunak Group",
    "address": "Plot No.1, Mohan Mill Compound,\nNext to Audi Thane, Ghodbunder Road,\nThane West 400607",
    "phone": "2225847000",
    "email": "joquim.raunakgroup@gmail.com",
    "web": "http://raunakgroup.com",
    "sources": [
        "Website",
        "https://github.com/datenanfragen/data/issues/528"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "raunakgroupcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22in%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Raunak%20Group%22%2C%22address%22%3A%22Plot%20No.1%2C%20Mohan%20Mill%20Compound%2C%5CnNext%20to%20Audi%20Thane%2C%20Ghodbunder%20Road%2C%5CnThane%20West%20400607%22%2C%22phone%22%3A%222225847000%22%2C%22email%22%3A%22joquim.raunakgroup%40gmail.com%22%2C%22web%22%3A%22http%3A%2F%2Fraunakgroup.com%22%2C%22sources%22%3A%5B%22Website%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F528%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22raunakgroupcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
