### ISSUE TITLE
New company suggestion: `Me`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#529]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Me",
    "runs": [
        "MeApp"
    ],
    "address": "Ben Yehoda, Tel Aviv, Israel",
    "sources": [
        "http://www.meapp.info",
        "http://www.meapp.info/privacy-policy-terms-of-use/",
        "https://github.com/datenanfragen/data/issues/529"
    ],
    "slug": "me"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Me%22%2C%22runs%22%3A%5B%22MeApp%22%5D%2C%22address%22%3A%22Ben%20Yehoda%2C%20Tel%20Aviv%2C%20Israel%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.meapp.info%22%2C%22http%3A%2F%2Fwww.meapp.info%2Fprivacy-policy-terms-of-use%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F529%22%5D%2C%22slug%22%3A%22me%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
