### ISSUE TITLE
Suggested update for company `adobe`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#531]
The following suggestion was submitted through the website:

```
{
    "slug": "adobe",
    "relevant-countries": [
        "all"
    ],
    "name": "Adobe Systems Software Ireland Ltd.",
    "runs": [
        "Adobe Systems Inc.",
        "Behance (www.behance.net)",
        "Creative Cloud",
        "Document Cloud",
        "Adobe-ID"
    ],
    "address": "4–6 Riverwalk\nCity West Business Campus\nDublin 24\nIreland",
    "phone": "+353 1 242 6700",
    "fax": "+353 1 242 6711",
    "email": "dpo@adobe.com",
    "web": "https://www.adobe.com",
    "sources": [
        "https://www.adobe.com/privacy/policy.html",
        "https://www.adobe.com/legal/terms.html",
        "https://www.adobe.com/de/about-adobe/impressum.html",
        "https://github.com/datenanfragen/data/issues/531"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail",
            "type": "input"
        }
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22adobe%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Adobe%20Systems%20Software%20Ireland%20Ltd.%22%2C%22runs%22%3A%5B%22Adobe%20Systems%20Inc.%22%2C%22Behance%20(www.behance.net)%22%2C%22Creative%20Cloud%22%2C%22Document%20Cloud%22%2C%22Adobe-ID%22%5D%2C%22address%22%3A%224%E2%80%936%20Riverwalk%5CnCity%20West%20Business%20Campus%5CnDublin%2024%5CnIreland%22%2C%22phone%22%3A%22%2B353%201%20242%206700%22%2C%22fax%22%3A%22%2B353%201%20242%206711%22%2C%22email%22%3A%22dpo%40adobe.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.adobe.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.adobe.com%2Fprivacy%2Fpolicy.html%22%2C%22https%3A%2F%2Fwww.adobe.com%2Flegal%2Fterms.html%22%2C%22https%3A%2F%2Fwww.adobe.com%2Fde%2Fabout-adobe%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F531%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22input%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
