### ISSUE TITLE
New company suggestion: `RB Information Services`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#532]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "addresses"
    ],
    "name": "RB Information Services",
    "address": "Wiener Straße 79\n60599 Frankfurt am Main",
    "phone": "+49 69 655273",
    "email": "[redacted]@rbinformationservices.de",
    "web": "www.rbinformationservices.de",
    "sources": [
        "https://rbinformationservices.de/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/532"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Dienstleistungsunternehmen für B2B-Adressmanagement."
    ],
    "slug": "rb-information-services"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22RB%20Information%20Services%22%2C%22address%22%3A%22Wiener%20Stra%C3%9Fe%2079%5Cn60599%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22%2B49%2069%20655273%22%2C%22email%22%3A%22redacted%40rbinformationservices.de%22%2C%22web%22%3A%22www.rbinformationservices.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Frbinformationservices.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F532%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Dienstleistungsunternehmen%20f%C3%BCr%20B2B-Adressmanagement.%22%5D%2C%22slug%22%3A%22rb-information-services%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
