### ISSUE TITLE
New company suggestion: `Nike`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#533]
The following suggestion was submitted through the website:

```
{
    "categories": [
        "commerce"
    ],
    "name": "Nike",
    "address": "Nike Privacy Office, Nike European Operations Netherlands B.V., Colosseum 1, 1213NL Hilversum, Niederlande",
    "email": "privacy@nike.com",
    "sources": [
        "https://agreementservice.svs.nike.com/rest/agreement?agreementType=privacyPolicy&uxId=com.nike.commerce.nikedotcom.web&country=DE",
        "https://github.com/datenanfragen/data/issues/533"
    ],
    "slug": "nike",
    "relevant-countries": [
        "all"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Nike%22%2C%22address%22%3A%22Nike%20Privacy%20Office%2C%20Nike%20European%20Operations%20Netherlands%20B.V.%2C%20Colosseum%201%2C%201213NL%20Hilversum%2C%20Niederlande%22%2C%22email%22%3A%22privacy%40nike.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fagreementservice.svs.nike.com%2Frest%2Fagreement%3FagreementType%3DprivacyPolicy%26uxId%3Dcom.nike.commerce.nikedotcom.web%26country%3DDE%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F533%22%5D%2C%22slug%22%3A%22nike%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
