### ISSUE TITLE
New company suggestion: `Süd-Tiroler Freiheit`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#534]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "it"
    ],
    "categories": [
        "political party"
    ],
    "name": "Süd-Tiroler Freiheit",
    "address": "Laubengasse 9\n39100 Bozen",
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "sd-tiroler-freiheit",
    "sources": [
        "https://github.com/datenanfragen/data/issues/534"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22it%22%5D%2C%22categories%22%3A%5B%22political%20party%22%5D%2C%22name%22%3A%22S%C3%BCd-Tiroler%20Freiheit%22%2C%22address%22%3A%22Laubengasse%209%5Cn39100%20Bozen%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22sd-tiroler-freiheit%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F534%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
