### ISSUE TITLE
New company suggestion: `Cognizant`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#535]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "name": "Cognizant",
    "address": "1 Kingdom Street. Paddington Central. London W2 6BD",
    "sources": [
        "https://www.cognizant.com/en-uk/",
        "https://github.com/datenanfragen/data/issues/535"
    ],
    "slug": "cognizant"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22name%22%3A%22Cognizant%22%2C%22address%22%3A%221%20Kingdom%20Street.%20Paddington%20Central.%20London%20W2%206BD%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cognizant.com%2Fen-uk%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F535%22%5D%2C%22slug%22%3A%22cognizant%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
