### ISSUE TITLE
New company suggestion: `MLP Finanzberatung SE`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#536]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "finance"
    ],
    "name": "MLP Finanzberatung SE",
    "address": "Alte Heerstraße 40\nD-69168 Wiesloch",
    "phone": "06222 308 0",
    "fax": "06222 308 9000",
    "email": "info@mlp.de",
    "web": "mlp.de",
    "sources": [
        "Nicht in der Datenbank.",
        "https://github.com/datenanfragen/data/issues/536"
    ],
    "slug": "mlp-finanzberatung-se"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22MLP%20Finanzberatung%20SE%22%2C%22address%22%3A%22Alte%20Heerstra%C3%9Fe%2040%5CnD-69168%20Wiesloch%22%2C%22phone%22%3A%2206222%20308%200%22%2C%22fax%22%3A%2206222%20308%209000%22%2C%22email%22%3A%22info%40mlp.de%22%2C%22web%22%3A%22mlp.de%22%2C%22sources%22%3A%5B%22Nicht%20in%20der%20Datenbank.%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F536%22%5D%2C%22slug%22%3A%22mlp-finanzberatung-se%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
