### ISSUE TITLE
New company suggestion: `BrandMaker GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#537]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "BrandMaker GmbH",
    "address": "Rüppurrer Straße 1\n76137 Karlsruhe",
    "phone": "+49 721 97791000",
    "fax": "+49 721 97791098",
    "web": "www.brandmaker.com",
    "sources": [
        "www.brandmaker.com",
        "https://github.com/datenanfragen/data/issues/537"
    ],
    "slug": "brandmaker-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22BrandMaker%20GmbH%22%2C%22address%22%3A%22R%C3%BCppurrer%20Stra%C3%9Fe%201%5Cn76137%20Karlsruhe%22%2C%22phone%22%3A%22%2B49%20721%2097791000%22%2C%22fax%22%3A%22%2B49%20721%2097791098%22%2C%22web%22%3A%22www.brandmaker.com%22%2C%22sources%22%3A%5B%22www.brandmaker.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F537%22%5D%2C%22slug%22%3A%22brandmaker-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
