### ISSUE TITLE
New company suggestion: `Wirtschaftskammer Steiermark`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#538]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "at"
    ],
    "categories": [
        "public body"
    ],
    "name": "Wirtschaftskammer Steiermark",
    "address": "Körblergasse 111-113, 8010 Graz",
    "phone": "+43 316 601",
    "email": "datenschutz@wkstmk.at",
    "web": "https://www.wko.at/service/stmk/Wirtschaftskammer.html",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/538"
    ],
    "slug": "wkoat"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Wirtschaftskammer%20Steiermark%22%2C%22address%22%3A%22K%C3%B6rblergasse%20111-113%2C%208010%20Graz%22%2C%22phone%22%3A%22%2B43%20316%20601%22%2C%22email%22%3A%22datenschutz%40wkstmk.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.wko.at%2Fservice%2Fstmk%2FWirtschaftskammer.html%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F538%22%5D%2C%22slug%22%3A%22wkoat%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
