### ISSUE TITLE
New company suggestion: `Likee Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#539]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "sg"
    ],
    "categories": [
        "entertainment",
        "social media"
    ],
    "name": "Likee Inc.",
    "address": "30 Pasir Panjang Road # 15-31A Mapletree Business City, Singapour 117440",
    "email": "feedback@likee.video",
    "web": "https://likee.com",
    "sources": [
        "https://likee.com/en/privacy",
        "https://likee.com/privacy",
        "https://github.com/datenanfragen/data/issues/539"
    ],
    "slug": "likeecom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22sg%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Likee%20Inc.%22%2C%22address%22%3A%2230%20Pasir%20Panjang%20Road%20%23%2015-31A%20Mapletree%20Business%20City%2C%20Singapour%20117440%22%2C%22email%22%3A%22feedback%40likee.video%22%2C%22web%22%3A%22https%3A%2F%2Flikee.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Flikee.com%2Fen%2Fprivacy%22%2C%22https%3A%2F%2Flikee.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F539%22%5D%2C%22slug%22%3A%22likeecom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
