### ISSUE TITLE
New company suggestion: ` cpx online active AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#541]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "ch",
        "de",
        "all"
    ],
    "categories": [
        "ads",
        null
    ],
    "name": " cpx online active AG",
    "address": "cpx online active AG\nOrtsgmeindstrasse 5\n9444 Diepoldsau",
    "email": "datenschutz@cpx-onlineactive.com",
    "web": "http://cpx-onlineactive.com",
    "sources": [
        "http://cpx-onlineactive.com/privacy-policy",
        "https://github.com/datenanfragen/data/issues/541"
    ],
    "suggested-transport-medium": "email",
    "slug": "cpx-onlineactivecom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22ch%22%2C%22de%22%2C%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2Cnull%5D%2C%22name%22%3A%22%20cpx%20online%20active%20AG%22%2C%22address%22%3A%22cpx%20online%20active%20AG%5CnOrtsgmeindstrasse%205%5Cn9444%20Diepoldsau%22%2C%22email%22%3A%22datenschutz%40cpx-onlineactive.com%22%2C%22web%22%3A%22http%3A%2F%2Fcpx-onlineactive.com%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fcpx-onlineactive.com%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F541%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22cpx-onlineactivecom%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
