### ISSUE TITLE
New company suggestion: `Entertainment Media GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#542]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "Entertainment Media GmbH",
    "address": "Entertainment Media GmbH\nTwin Towers\nWienerbergstraße 11/12A\n1100 Vienna",
    "email": "datenschutz@entertainment.at",
    "web": "entertainment.at",
    "sources": [
        "https://www.entertainment.at/datenschutzerklaerung",
        "https://github.com/datenanfragen/data/issues/542"
    ],
    "suggested-transport-medium": "email",
    "slug": "entertainment-media-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Entertainment%20Media%20GmbH%22%2C%22address%22%3A%22Entertainment%20Media%20GmbH%5CnTwin%20Towers%5CnWienerbergstra%C3%9Fe%2011%2F12A%5Cn1100%20Vienna%22%2C%22email%22%3A%22datenschutz%40entertainment.at%22%2C%22web%22%3A%22entertainment.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.entertainment.at%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F542%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22entertainment-media-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
