### ISSUE TITLE
New company suggestion: `4Care GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#543]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce"
    ],
    "name": "4Care GmbH",
    "address": "4Care GmbH\nWissenschaftspark\nFraunhoferstr. 17\nD-24118 Kiel",
    "phone": "+49 431 881188",
    "fax": "+49 431 881166",
    "email": "feedback@4care.de",
    "web": "www.4care.de",
    "sources": [
        "https://www.4care.de/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/543"
    ],
    "suggested-transport-medium": "email",
    "slug": "4care-gmbh"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%224Care%20GmbH%22%2C%22address%22%3A%224Care%20GmbH%5CnWissenschaftspark%5CnFraunhoferstr.%2017%5CnD-24118%20Kiel%22%2C%22phone%22%3A%22%2B49%20431%20881188%22%2C%22fax%22%3A%22%2B49%20431%20881166%22%2C%22email%22%3A%22feedback%404care.de%22%2C%22web%22%3A%22www.4care.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.4care.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F543%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%224care-gmbh%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
