### ISSUE TITLE
New company suggestion: `Better Information Group Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#544]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "Better Information Group Ltd",
    "address": "Better Information Group Ltd.\n132-134 Great Ancoats Street, Manchester, England, M4 6DE\nRegistered in England, Company No 10543466\n",
    "email": "info@informationgroup.co.uk",
    "web": "https://informationgroup.co.uk/",
    "sources": [
        "https://informationgroup.co.uk/privacy.html",
        "https://github.com/datenanfragen/data/issues/544"
    ],
    "slug": "informationgroupcouk"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Better%20Information%20Group%20Ltd%22%2C%22address%22%3A%22Better%20Information%20Group%20Ltd.%5Cn132-134%20Great%20Ancoats%20Street%2C%20Manchester%2C%20England%2C%20M4%206DE%5CnRegistered%20in%20England%2C%20Company%20No%2010543466%5Cn%22%2C%22email%22%3A%22info%40informationgroup.co.uk%22%2C%22web%22%3A%22https%3A%2F%2Finformationgroup.co.uk%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Finformationgroup.co.uk%2Fprivacy.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F544%22%5D%2C%22slug%22%3A%22informationgroupcouk%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
