### ISSUE TITLE
New company suggestion: `Piranha Games Inc`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#545]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Piranha Games Inc",
    "address": "Data Protection Officer \nc/o Piranha Games Inc.\n2065 - 88 Pender St W\nVancouver, BC V6B 6N9\nCanada",
    "email": "dpo@piranhagames.com",
    "web": "piranhagames.com",
    "sources": [
        "mwomercs.com/privacy",
        "piranhagames.com/contact",
        "https://github.com/datenanfragen/data/issues/545"
    ],
    "slug": "piranha-games-inc"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Piranha%20Games%20Inc%22%2C%22address%22%3A%22Data%20Protection%20Officer%20%5Cnc%2Fo%20Piranha%20Games%20Inc.%5Cn2065%20-%2088%20Pender%20St%20W%5CnVancouver%2C%20BC%20V6B%206N9%5CnCanada%22%2C%22email%22%3A%22dpo%40piranhagames.com%22%2C%22web%22%3A%22piranhagames.com%22%2C%22sources%22%3A%5B%22mwomercs.com%2Fprivacy%22%2C%22piranhagames.com%2Fcontact%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F545%22%5D%2C%22slug%22%3A%22piranha-games-inc%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
