### ISSUE TITLE
New company suggestion: `Hammy Media Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#546]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Hammy Media Ltd",
    "runs": [
        "xhamster.com"
    ],
    "address": "79 Spyrou Kyprianou, Protopapas Building, 2nd floor, Flat 201, 3076, Limassol, Cyprus",
    "email": "help@xhamster.com",
    "sources": [
        "https://xhamster.com/info/privacy",
        "https://github.com/datenanfragen/data/issues/546"
    ],
    "suggested-transport-medium": "email",
    "slug": "hammy-media-ltd"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Hammy%20Media%20Ltd%22%2C%22runs%22%3A%5B%22xhamster.com%22%5D%2C%22address%22%3A%2279%20Spyrou%20Kyprianou%2C%20Protopapas%20Building%2C%202nd%20floor%2C%20Flat%20201%2C%203076%2C%20Limassol%2C%20Cyprus%22%2C%22email%22%3A%22help%40xhamster.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fxhamster.com%2Finfo%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F546%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22hammy-media-ltd%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
