### ISSUE TITLE
New company suggestion: `GYMLIB SAS`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#547]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "name": "GYMLIB SAS",
    "address": "156 rue de la Roquette, 75011 Paris",
    "sources": [
        "https://legals.gymlib.com/tos",
        "https://github.com/datenanfragen/data/issues/547"
    ],
    "slug": "gymlib-sas"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22name%22%3A%22GYMLIB%20SAS%22%2C%22address%22%3A%22156%20rue%20de%20la%20Roquette%2C%2075011%20Paris%22%2C%22sources%22%3A%5B%22https%3A%2F%2Flegals.gymlib.com%2Ftos%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F547%22%5D%2C%22slug%22%3A%22gymlib-sas%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
