### ISSUE TITLE
New company suggestion: `Department for Work and Pensions`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#548]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "public body"
    ],
    "name": "Department for Work and Pensions",
    "address": "DWP Data Protection Team \nBenton Park View 6 \nRoom BP6001 \nMail Handling Site A \nWolverhampton \nWV98 1ZX ",
    "email": "data.protectionofficer@dwp.gov.uk",
    "web": "https://www.gov.uk/government/organisations/department-for-work-pensions",
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "slug": "govuk",
    "sources": [
        "https://github.com/datenanfragen/data/issues/548"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Department%20for%20Work%20and%20Pensions%22%2C%22address%22%3A%22DWP%20Data%20Protection%20Team%20%5CnBenton%20Park%20View%206%20%5CnRoom%20BP6001%20%5CnMail%20Handling%20Site%20A%20%5CnWolverhampton%20%5CnWV98%201ZX%20%22%2C%22email%22%3A%22data.protectionofficer%40dwp.gov.uk%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Forganisations%2Fdepartment-for-work-pensions%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22govuk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F548%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
