### ISSUE TITLE
New company suggestion: `SellAnyCar`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#549]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "ae"
    ],
    "categories": [
        null
    ],
    "name": "SellAnyCar",
    "address": "Madina Mall - Al Qusais Dubai ",
    "phone": "+971 4 709 3000",
    "email": "atiyatuma@gmail.com",
    "web": "https://uae.sellanycar.com",
    "sources": [
        "SellAnyCar",
        "https://github.com/datenanfragen/data/issues/549"
    ],
    "comments": [
        "SellAnyCar.com is the largest car buying platform in the UAE. This is the most suitable platform to sell used vehicles at the right price for experienced and inexperienced car sellers alike. It can be stressful and challenging to sell a used car at a fair price and without any safety risks if the car sellers do not have prior experience of selling cars. There are several other factors that can increase the challenges for first-time car sellers to sell their used cars at a fair price and in a hassle-free way. "
    ],
    "slug": "uaesellanycarcom"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22ae%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22SellAnyCar%22%2C%22address%22%3A%22Madina%20Mall%20-%20Al%20Qusais%20Dubai%20%22%2C%22phone%22%3A%22%2B971%204%20709%203000%22%2C%22email%22%3A%22atiyatuma%40gmail.com%22%2C%22web%22%3A%22https%3A%2F%2Fuae.sellanycar.com%22%2C%22sources%22%3A%5B%22SellAnyCar%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F549%22%5D%2C%22comments%22%3A%5B%22SellAnyCar.com%20is%20the%20largest%20car%20buying%20platform%20in%20the%20UAE.%20This%20is%20the%20most%20suitable%20platform%20to%20sell%20used%20vehicles%20at%20the%20right%20price%20for%20experienced%20and%20inexperienced%20car%20sellers%20alike.%20It%20can%20be%20stressful%20and%20challenging%20to%20sell%20a%20used%20car%20at%20a%20fair%20price%20and%20without%20any%20safety%20risks%20if%20the%20car%20sellers%20do%20not%20have%20prior%20experience%20of%20selling%20cars.%20There%20are%20several%20other%20factors%20that%20can%20increase%20the%20challenges%20for%20first-time%20car%20sellers%20to%20sell%20their%20used%20cars%20at%20a%20fair%20price%20and%20in%20a%20hassle-free%20way.%20%22%5D%2C%22slug%22%3A%22uaesellanycarcom%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
