### ISSUE TITLE
New company suggestion: `CyberGhost S.A`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#550]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "all"
    ],
    "name": "CyberGhost S.A",
    "address": "70-72 Dionisie Lupu St.,\nDistrict 1, 010458\nBucharest, Romania",
    "sources": [
        "https://www.cyberghostvpn.com/de_DE/impressum",
        "https://github.com/datenanfragen/data/issues/550"
    ],
    "suggested-transport-medium": "email",
    "slug": "cyberghost-sa"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22CyberGhost%20S.A%22%2C%22address%22%3A%2270-72%20Dionisie%20Lupu%20St.%2C%5CnDistrict%201%2C%20010458%5CnBucharest%2C%20Romania%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cyberghostvpn.com%2Fde_DE%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F550%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22slug%22%3A%22cyberghost-sa%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
