### ISSUE TITLE
New company suggestion: `Livehost`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#551]
The following suggestion was submitted through the website:

```
{
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "commerce",
        "telecommunication"
    ],
    "name": "Livehost",
    "runs": [
        "Livehost.fr"
    ],
    "address": "1 CHEMIN DU MOULIN\n17220 SAINTE SOULLE\nFRANCE",
    "phone": " ",
    "web": "https://www.livehost.fr/",
    "sources": [
        "https://www.livehost.fr/fixe?cgu",
        "https://www.societe.com/societe/monsieur-boris-mace-535288898.html",
        "https://github.com/datenanfragen/data/issues/551"
    ],
    "suggested-transport-medium": "letter",
    "slug": "livehostfr"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22Livehost%22%2C%22runs%22%3A%5B%22Livehost.fr%22%5D%2C%22address%22%3A%221%20CHEMIN%20DU%20MOULIN%5Cn17220%20SAINTE%20SOULLE%5CnFRANCE%22%2C%22phone%22%3A%22%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.livehost.fr%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.livehost.fr%2Ffixe%3Fcgu%22%2C%22https%3A%2F%2Fwww.societe.com%2Fsociete%2Fmonsieur-boris-mace-535288898.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F551%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22slug%22%3A%22livehostfr%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
