### ISSUE TITLE
Suggested update for company `informationgroup`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#555]
The following suggestion was submitted through the website:

```
{
    "slug": "informationgroup",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "Better Information Group Ltd",
    "address": "132-134 Great Ancoats Street\nManchester\nM4 6DE\nUnited Kingdom",
    "email": "reply@informationgroup.co.uk",
    "web": "https://informationgroup.co.uk/",
    "sources": [
        "https://informationgroup.co.uk/privacy.html",
        "https://github.com/datenanfragen/data/issues/544",
        "https://github.com/datenanfragen/data/issues/555"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22informationgroup%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Better%20Information%20Group%20Ltd%22%2C%22address%22%3A%22132-134%20Great%20Ancoats%20Street%5CnManchester%5CnM4%206DE%5CnUnited%20Kingdom%22%2C%22email%22%3A%22reply%40informationgroup.co.uk%22%2C%22web%22%3A%22https%3A%2F%2Finformationgroup.co.uk%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Finformationgroup.co.uk%2Fprivacy.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F544%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F555%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks for the suggestion. Is there a source for that email? The privacy policy only lists `info@informationgroup.co.uk`, so I am going to leave it at that for now.
