### ISSUE TITLE
New company suggestion: `Coca-Cola France`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#557]
The following suggestion was submitted through the website:

```
{
    "slug": "coca-cola-francefr",
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Coca-Cola France",
    "runs": [
        "Coca-Cola"
    ],
    "address": "Coca-Cola Contact,\nRelations Consommateurs,\n9 chemin de Bretagne,\n92130 Issy Les Moulineaux.",
    "phone": "09 69 39 29 00",
    "email": "fr.ciccontact@coca-cola.com",
    "web": "https://www.coca-cola-france.fr/",
    "sources": [
        "https://www.coca-cola-france.fr/politique-de-confidentialite",
        "https://github.com/datenanfragen/data/issues/557"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22coca-cola-francefr%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Coca-Cola%20France%22%2C%22runs%22%3A%5B%22Coca-Cola%22%5D%2C%22address%22%3A%22Coca-Cola%20Contact%2C%5CnRelations%20Consommateurs%2C%5Cn9%20chemin%20de%20Bretagne%2C%5Cn92130%20Issy%20Les%20Moulineaux.%22%2C%22phone%22%3A%2209%2069%2039%2029%2000%22%2C%22email%22%3A%22fr.ciccontact%40coca-cola.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.coca-cola-france.fr%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.coca-cola-france.fr%2Fpolitique-de-confidentialite%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F557%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
