### ISSUE TITLE
New company suggestion: `Fosters.com`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#558]
The following suggestion was submitted through the website:

```
{
    "slug": "fosterscom",
    "relevant-countries": [
        null
    ],
    "categories": [
        null
    ],
    "name": "Fosters.com",
    "address": "111 New Hampshire Ave. \nPortsmouth, N.H. 03801",
    "phone": "8004390303",
    "email": "Haltschiller@seacostonline.com",
    "web": "Fosters.com",
    "sources": [
        "https://github.com/datenanfragen/data/issues/558"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fosterscom%22%2C%22relevant-countries%22%3A%5Bnull%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Fosters.com%22%2C%22address%22%3A%22111%20New%20Hampshire%20Ave.%20%5CnPortsmouth%2C%20N.H.%2003801%22%2C%22phone%22%3A%228004390303%22%2C%22email%22%3A%22Haltschiller%40seacostonline.com%22%2C%22web%22%3A%22Fosters.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F558%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
