### ISSUE TITLE
New company suggestion: `TARGET TEAM EUROPE S.L.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#559]
The following suggestion was submitted through the website:

```
{
    "slug": "target-team-europecom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "TARGET TEAM EUROPE S.L.",
    "address": "TARGET TEAM EUROPE S.L.\nMadrazo 27, 1a Planta\n08006 Barcelona\nEspaña",
    "web": "http://www.target-team-europe.com",
    "sources": [
        "http://www.target-team-europe.com/de/legal/",
        "https://github.com/datenanfragen/data/issues/559"
    ],
    "required-elements": [
        {
            "desc": "Email",
            "type": "email"
        }
    ],
    "suggested-transport-medium": "letter"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22target-team-europecom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22TARGET%20TEAM%20EUROPE%20S.L.%22%2C%22address%22%3A%22TARGET%20TEAM%20EUROPE%20S.L.%5CnMadrazo%2027%2C%201a%20Planta%5Cn08006%20Barcelona%5CnEspan%CC%83a%22%2C%22web%22%3A%22http%3A%2F%2Fwww.target-team-europe.com%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.target-team-europe.com%2Fde%2Flegal%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F559%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%7D%5D%2C%22suggested-transport-medium%22%3A%22letter%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
