### ISSUE TITLE
New company suggestion: `KfW Bankengruppe`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#560]
The following suggestion was submitted through the website:

```
{
    "slug": "kfw-bankengruppe",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "finance"
    ],
    "name": "KfW Bankengruppe",
    "address": "Palmengartenstraße 5-9\n60325 Frankfurt am Main",
    "phone": "069 74 31-0",
    "fax": "069 74 31-29 44",
    "email": "info@kfw.de",
    "web": "www.kfw.de",
    "sources": [
        "https://www.kfw.de/KfW-Konzern/Impressum.html",
        "https://github.com/datenanfragen/data/issues/560"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22kfw-bankengruppe%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22KfW%20Bankengruppe%22%2C%22address%22%3A%22Palmengartenstra%C3%9Fe%205-9%5Cn60325%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22069%2074%2031-0%22%2C%22fax%22%3A%22069%2074%2031-29%2044%22%2C%22email%22%3A%22info%40kfw.de%22%2C%22web%22%3A%22www.kfw.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.kfw.de%2FKfW-Konzern%2FImpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F560%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
