### ISSUE TITLE
Suggested update for company `flixbus`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#561]
The following suggestion was submitted through the website:

```
{
    "slug": "flixbus",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "FlixMobility GmbH",
    "runs": [
        "FlixBus (www.flixbus.de)",
        "FlixBus Mein Fernbus (www.meinfernbus.de)"
    ],
    "address": "Birketweg 33\n80639 München\nDeutschland",
    "phone": "+49 30 300137300",
    "email": "data.protection@flixbus.com",
    "web": "https://www.flixbus.de/",
    "sources": [
        "https://www.flixbus.de/datenschutz",
        "https://cdn.flixbus.de/2017-11/data-privacy.pdf",
        "https://www.flixbus.de/impressum",
        "https://github.com/datenanfragen/data/issues/561"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22flixbus%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22FlixMobility%20GmbH%22%2C%22runs%22%3A%5B%22FlixBus%20(www.flixbus.de)%22%2C%22FlixBus%20Mein%20Fernbus%20(www.meinfernbus.de)%22%5D%2C%22address%22%3A%22Birketweg%2033%5Cn80639%20M%C3%BCnchen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20300137300%22%2C%22email%22%3A%22data.protection%40flixbus.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.flixbus.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.flixbus.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fcdn.flixbus.de%2F2017-11%2Fdata-privacy.pdf%22%2C%22https%3A%2F%2Fwww.flixbus.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F561%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
