### ISSUE TITLE
New company suggestion: `Fivestar OMS`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#563]
The following suggestion was submitted through the website:

```
{
    "slug": "fivestar-omsnet",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Fivestar OMS",
    "address": "Fivestar Marketing EOOD\nPanoniya Straße 3\n3700 Vidin\nBulgaria",
    "email": "info@fivestar-marketing.net",
    "web": "https://fivestar-oms.net/",
    "sources": [
        "https://github.com/datenanfragen/data/issues/563"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fivestar-omsnet%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Fivestar%20OMS%22%2C%22address%22%3A%22Fivestar%20Marketing%20EOOD%5CnPanoniya%20Stra%C3%9Fe%203%5Cn3700%20Vidin%5CnBulgaria%22%2C%22email%22%3A%22info%40fivestar-marketing.net%22%2C%22web%22%3A%22https%3A%2F%2Ffivestar-oms.net%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F563%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
