### ISSUE TITLE
New company suggestion: `Frankfurter Sparkasse`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#564]
The following suggestion was submitted through the website:

```
{
    "slug": "frankfurter-sparkassede",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "finance"
    ],
    "name": "Frankfurter Sparkasse",
    "address": "Neue Mainzer Str. 47-53\n60311 Frankfurt am Main\nDeutschland",
    "phone": "+49 69 26413686",
    "fax": "+49 69 26412900",
    "email": "datenschutz@frankfurter-sparkasse.de",
    "web": "https://www.frankfurter-sparkasse.de/",
    "sources": [
        "https://www.frankfurter-sparkasse.de/de/home/toolbar/datenschutz.html",
        "https://www.frankfurter-sparkasse.de/de/home/toolbar/impressum.html",
        "https://github.com/datenanfragen/data/issues/564"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22frankfurter-sparkassede%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Frankfurter%20Sparkasse%22%2C%22address%22%3A%22Neue%20Mainzer%20Str.%2047-53%5Cn60311%20Frankfurt%20am%20Main%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2069%2026413686%22%2C%22fax%22%3A%22%2B49%2069%2026412900%22%2C%22email%22%3A%22datenschutz%40frankfurter-sparkasse.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.frankfurter-sparkasse.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.frankfurter-sparkasse.de%2Fde%2Fhome%2Ftoolbar%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.frankfurter-sparkasse.de%2Fde%2Fhome%2Ftoolbar%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F564%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
