### ISSUE TITLE
New company suggestion: `Headspace`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#566]
The following suggestion was submitted through the website:

```
{
    "slug": "headspace",
    "relevant-countries": [
        "us"
    ],
    "categories": [
        "health"
    ],
    "name": "Headspace",
    "address": "425 California Street\n2nd Floor\nSan Francisco\nCA 94104",
    "sources": [
        "https://www.headspace.com/contact-us",
        "https://github.com/datenanfragen/data/issues/566"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22headspace%22%2C%22relevant-countries%22%3A%5B%22us%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Headspace%22%2C%22address%22%3A%22425%20California%20Street%5Cn2nd%20Floor%5CnSan%20Francisco%5CnCA%2094104%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.headspace.com%2Fcontact-us%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F566%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
