### ISSUE TITLE
New company suggestion: `Pinnacle Technology Partners`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#567]
The following suggestion was submitted through the website:

```
{
    "slug": "ptpcloud",
    "relevant-countries": [
        "us"
    ],
    "categories": [
        "addresses"
    ],
    "name": "Pinnacle Technology Partners",
    "address": "83 Morse Street, Unit 6B Norwood, MA 02062 USA",
    "phone": "1(617) 297.9670",
    "email": "ptpcloud.innovation@gmail.com",
    "web": "https://www.ptp.cloud",
    "sources": [
        "https://www.ptp.cloud",
        "https://github.com/datenanfragen/data/issues/567"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ptpcloud%22%2C%22relevant-countries%22%3A%5B%22us%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22Pinnacle%20Technology%20Partners%22%2C%22address%22%3A%2283%20Morse%20Street%2C%20Unit%206B%20Norwood%2C%20MA%2002062%20USA%22%2C%22phone%22%3A%221(617)%20297.9670%22%2C%22email%22%3A%22ptpcloud.innovation%40gmail.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ptp.cloud%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ptp.cloud%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F567%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
