### ISSUE TITLE
New company suggestion: `AIG Europe SA, Ireland Branch (American International Group)`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#568]
The following suggestion was submitted through the website:

```
{
    "slug": "aig-europe-sa-ireland-branch-american-international-group",
    "relevant-countries": [
        "ie"
    ],
    "categories": [
        "insurance"
    ],
    "name": "AIG Europe SA, Ireland Branch (American International Group)",
    "address": "30 North Wall Quay,\nDublin 1\nIRELAND",
    "phone": "+353 1 208 1400",
    "email": "dataprotectionofficer.ie@aig.com",
    "sources": [
        "https://www.aig.ie/privacy-policy#accordion-child_pr_cr_cr_accordion_14",
        "https://github.com/datenanfragen/data/issues/568"
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22aig-europe-sa-ireland-branch-american-international-group%22%2C%22relevant-countries%22%3A%5B%22ie%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22AIG%20Europe%20SA%2C%20Ireland%20Branch%20(American%20International%20Group)%22%2C%22address%22%3A%2230%20North%20Wall%20Quay%2C%5CnDublin%201%5CnIRELAND%22%2C%22phone%22%3A%22%2B353%201%20208%201400%22%2C%22email%22%3A%22dataprotectionofficer.ie%40aig.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.aig.ie%2Fprivacy-policy%23accordion-child_pr_cr_cr_accordion_14%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F568%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
