### ISSUE TITLE
New company suggestion: `gms-store`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#569]
The following suggestion was submitted through the website:

```
{
    "slug": "gms-store",
    "relevant-countries": [
        "pt"
    ],
    "categories": [
        "commerce"
    ],
    "name": "gms-store",
    "address": " Rua do Carmo nº 46, Chiado\n1200-094 Lisboa\n\n",
    "phone": "213 420 159 ",
    "email": "loja@gms-store.com",
    "web": "www.gms-store.com",
    "sources": [
        "https://www.gms-store.com/pt/*/lojas_540.html?ids=9",
        "https://github.com/datenanfragen/data/issues/569"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gms-store%22%2C%22relevant-countries%22%3A%5B%22pt%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22gms-store%22%2C%22address%22%3A%22%20Rua%20do%20Carmo%20n%C2%BA%2046%2C%20Chiado%5Cn1200-094%20Lisboa%5Cn%5Cn%22%2C%22phone%22%3A%22213%20420%20159%20%22%2C%22email%22%3A%22loja%40gms-store.com%22%2C%22web%22%3A%22www.gms-store.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gms-store.com%2Fpt%2F*%2Flojas_540.html%3Fids%3D9%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F569%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
