### ISSUE TITLE
New company suggestion: `Internet Marketing Mallorca S.L.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#570]
The following suggestion was submitted through the website:

```
{
    "slug": "bewertungen-kaufen24com",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "social media"
    ],
    "name": "Internet Marketing Mallorca S.L.",
    "address": "Carrer Gran Via, 32\n07180 El Toro",
    "phone": "089  99 52 92 96",
    "email": "support@bewertungenkaufen.com",
    "web": "https://bewertungen-kaufen24.com",
    "sources": [
        "https://bewertungen-kaufen24.com/impressum/",
        "https://github.com/datenanfragen/data/issues/570"
    ],
    "required-elements": [
        {
            "desc": "Impressum",
            "type": "email"
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bewertungen-kaufen24com%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Internet%20Marketing%20Mallorca%20S.L.%22%2C%22address%22%3A%22Carrer%20Gran%20Via%2C%2032%5Cn07180%20El%20Toro%22%2C%22phone%22%3A%22089%20%2099%2052%2092%2096%22%2C%22email%22%3A%22support%40bewertungenkaufen.com%22%2C%22web%22%3A%22https%3A%2F%2Fbewertungen-kaufen24.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbewertungen-kaufen24.com%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F570%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Impressum%22%2C%22type%22%3A%22email%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
