### ISSUE TITLE
New company suggestion: `Frankfurter Volksbank eG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#572]
The following suggestion was submitted through the website:

```
{
    "slug": "frankfurter-volksbankde",
    "relevant-countries": [
        "de"
    ],
    "name": "Frankfurter Volksbank eG",
    "address": "Frankfurter Volksbank eG\nBörsenstrasse 7-11\n60313 Frankfurt\nDeutschland",
    "phone": "06921720",
    "fax": " 069217221501",
    "email": "datenschutz@frankfurter-volksbank.de",
    "web": "https://www.frankfurter-volksbank.de",
    "sources": [
        "https://www.frankfurter-volksbank.de/service/datenschutzhinweis.html",
        "https://github.com/datenanfragen/data/issues/572"
    ],
    "needs-id-document": true,
    "comments": [
        "Da es sich bei der Auskunft im Regelfall um sensible Bankdaten handelt, gibt es einen Identitätsnachweis. Dieser ist allerdings datensparsam gestaltet."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22frankfurter-volksbankde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Frankfurter%20Volksbank%20eG%22%2C%22address%22%3A%22Frankfurter%20Volksbank%20eG%5CnB%C3%B6rsenstrasse%207-11%5Cn60313%20Frankfurt%5CnDeutschland%22%2C%22phone%22%3A%2206921720%22%2C%22fax%22%3A%22%20069217221501%22%2C%22email%22%3A%22datenschutz%40frankfurter-volksbank.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.frankfurter-volksbank.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.frankfurter-volksbank.de%2Fservice%2Fdatenschutzhinweis.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F572%22%5D%2C%22needs-id-document%22%3Atrue%2C%22comments%22%3A%5B%22Da%20es%20sich%20bei%20der%20Auskunft%20im%20Regelfall%20um%20sensible%20Bankdaten%20handelt%2C%20gibt%20es%20einen%20Identit%C3%A4tsnachweis.%20Dieser%20ist%20allerdings%20datensparsam%20gestaltet.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
