### ISSUE TITLE
Suggested update for company `mtch-technology`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#573]
The following suggestion was submitted through the website:

```
{
    "slug": "mtch-technology",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "social media"
    ],
    "name": "MTCH Technology Services Ltd.",
    "runs": [
        "Humor Rainbow, Inc.",
        "OkCupid (www.okcupid.com)",
        "Plentyoffish (www.pof.com)",
        "tinder.com",
        null
    ],
    "address": "Pembroke House\n28–32 Pembroke Street Upper\nDublin 2\nIreland",
    "email": "csr@pof.com",
    "web": "https://www.okcupid.com",
    "sources": [
        "https://www.okcupid.com/legal/privacy",
        "https://www.pof.com/cookiepolicy.aspx",
        "https://github.com/datenanfragen/data/issues/573"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mtch-technology%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22MTCH%20Technology%20Services%20Ltd.%22%2C%22runs%22%3A%5B%22Humor%20Rainbow%2C%20Inc.%22%2C%22OkCupid%20(www.okcupid.com)%22%2C%22Plentyoffish%20(www.pof.com)%22%2C%22tinder.com%22%2Cnull%5D%2C%22address%22%3A%22Pembroke%20House%5Cn28%E2%80%9332%20Pembroke%20Street%20Upper%5CnDublin%202%5CnIreland%22%2C%22email%22%3A%22csr%40pof.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.okcupid.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.okcupid.com%2Flegal%2Fprivacy%22%2C%22https%3A%2F%2Fwww.pof.com%2Fcookiepolicy.aspx%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F573%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
