### ISSUE TITLE
New company suggestion: `Apotheke am Engelbecken`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#574]
The following suggestion was submitted through the website:

```
{
    "slug": "apotheke-am-engelbeckende",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health"
    ],
    "name": "Apotheke am Engelbecken",
    "address": "Apotheke am Engelbecken\nHeinrich-Heine-Str. 15\n10179 Berlin-Mitte",
    "phone": "030 / 275 60 275",
    "fax": "030 / 275 60 276",
    "email": " gesundheit [at] apotheke-am-engelbecken.de",
    "web": "https://www.apotheke-am-engelbecken.de/info/impressum/",
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "sources": [
        "https://github.com/datenanfragen/data/issues/574"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22apotheke-am-engelbeckende%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Apotheke%20am%20Engelbecken%22%2C%22address%22%3A%22Apotheke%20am%20Engelbecken%5CnHeinrich-Heine-Str.%2015%5Cn10179%20Berlin-Mitte%22%2C%22phone%22%3A%22030%20%2F%20275%2060%20275%22%2C%22fax%22%3A%22030%20%2F%20275%2060%20276%22%2C%22email%22%3A%22%20gesundheit%20%5Bat%5D%20apotheke-am-engelbecken.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.apotheke-am-engelbecken.de%2Finfo%2Fimpressum%2F%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F574%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
