### ISSUE TITLE
New company suggestion: `GASPOOL Balancing Services GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#575]
The following suggestion was submitted through the website:

```
{
    "slug": "gaspoolde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "utility"
    ],
    "name": "GASPOOL Balancing Services GmbH",
    "address": "GASPOOL Balancing Services GmbH\nAnna-Louisa-Karsch-Str. 2\n10178 Berlin",
    "email": "info@gaspool.de",
    "web": "https://www.gaspool.de/",
    "sources": [
        "https://www.gaspool.de/impressum/",
        "https://github.com/datenanfragen/data/issues/575"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gaspoolde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22GASPOOL%20Balancing%20Services%20GmbH%22%2C%22address%22%3A%22GASPOOL%20Balancing%20Services%20GmbH%5CnAnna-Louisa-Karsch-Str.%202%5Cn10178%20Berlin%22%2C%22email%22%3A%22info%40gaspool.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gaspool.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gaspool.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F575%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
