### ISSUE TITLE
New company suggestion: `Stadtausstellung`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#576]
The following suggestion was submitted through the website:

```
{
    "slug": "stadtausstellung",
    "relevant-countries": [
        "de",
        "at"
    ],
    "name": "Stadtausstellung",
    "address": "Buchengasse 42/2/6\n1100 Wien ",
    "phone": "+43 7243 57435",
    "email": "wien@stadtausstellung.at, ",
    "web": "www.stadtausstellung.at",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/576"
    ],
    "comments": [
        "Dieses Unternehmen ist sehr fragwürdig in Bezug auf seine Geschäftspraktiken siehe https://inspectus-austria.blogspot.com/\n\nDer eingetragene Firmenname lautet: mobyoucon GmbH\naufgetreten wird mit Stadtausstellung bzw. Grosz in Deutschland und Österreich"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22stadtausstellung%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%5D%2C%22name%22%3A%22Stadtausstellung%22%2C%22address%22%3A%22Buchengasse%2042%2F2%2F6%5Cn1100%20Wien%20%22%2C%22phone%22%3A%22%2B43%207243%2057435%22%2C%22email%22%3A%22wien%40stadtausstellung.at%2C%20%22%2C%22web%22%3A%22www.stadtausstellung.at%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F576%22%5D%2C%22comments%22%3A%5B%22Dieses%20Unternehmen%20ist%20sehr%20fragw%C3%BCrdig%20in%20Bezug%20auf%20seine%20Gesch%C3%A4ftspraktiken%20siehe%20https%3A%2F%2Finspectus-austria.blogspot.com%2F%5Cn%5CnDer%20eingetragene%20Firmenname%20lautet%3A%20mobyoucon%20GmbH%5Cnaufgetreten%20wird%20mit%20Stadtausstellung%20bzw.%20Grosz%20in%20Deutschland%20und%20%C3%96sterreich%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.

**Comment by desti** [comment]
The comments are missleading.
https://inspectus-austria.blogspot.com/ is a non reliable source. The writer of this site is some sort of Freeman, spreading theories of state conspiracy on his Website.
This was already proven in court.

**Comment by baltpeter** [comment]
Thanks for bringing this to our attention, @desti. While we can and will not try to judge the reliability of the arguments of either side, we agree that Datenanfragen.de is not the place for these discussions.  
We have decided to remove both comments from the company page.

The comments on our company database are meant for discussing and sharing your opinions on the data protection-related practices of the respective companies. We will use this incident as an opportunity to work out a policy on what kinds of comments we will allow in the future.

**Comment by desti** [comment]
Thanks for the fast response.
Moderating comments on the web is a difficult and hard job - wish you the best.
regards

**Comment by baltpeter** [comment]
Absolutely and we definitely appreciate your input!

Thus far, this hasn't really been a problem but as we are starting to grow, this will become more and more relevant. So, it's best if we work out a policy now so the rules are clear and transparent for everyone.
