### ISSUE TITLE
New company suggestion: `Lollapalooza Berlin`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#578]
The following suggestion was submitted through the website:

```
{
    "slug": "lollapaloozadecom",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Lollapalooza Berlin",
    "address": "FRHUG Festival GmbH & Co. KG \nPfuelstraße 5, 10997 Berlin",
    "phone": "+49 30 40367050",
    "fax": "+49 30 403670533",
    "email": "info@lollapaloozade.com",
    "web": "https://www.lollapaloozade.com/",
    "sources": [
        "https://www.lollapaloozade.com/impressum",
        "https://github.com/datenanfragen/data/issues/578"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22lollapaloozadecom%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Lollapalooza%20Berlin%22%2C%22address%22%3A%22FRHUG%20Festival%20GmbH%20%26%20Co.%20KG%20%5CnPfuelstra%C3%9Fe%205%2C%2010997%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%2040367050%22%2C%22fax%22%3A%22%2B49%2030%20403670533%22%2C%22email%22%3A%22info%40lollapaloozade.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.lollapaloozade.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lollapaloozade.com%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F578%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
