### ISSUE TITLE
New company suggestion: `UNIVERSUM Inkasso`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#580]
The following suggestion was submitted through the website:

```
{
    "slug": "universum-groupde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "UNIVERSUM Inkasso",
    "address": "UNIVERSUM Inkasso GmbH\nHanauer Landstraße 164\n60314 Frankfurt am Main",
    "phone": "+49 69 42091325",
    "fax": "+49 69 42091318",
    "email": "konto@universum-group.de",
    "web": "https://www.universum-group.de/",
    "sources": [
        "https://www.universum-group.de/",
        "https://github.com/datenanfragen/data/issues/580"
    ],
    "required-elements": [
        {
            "type": "input"
        }
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22universum-groupde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22UNIVERSUM%20Inkasso%22%2C%22address%22%3A%22UNIVERSUM%20Inkasso%20GmbH%5CnHanauer%20Landstra%C3%9Fe%20164%5Cn60314%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22%2B49%2069%2042091325%22%2C%22fax%22%3A%22%2B49%2069%2042091318%22%2C%22email%22%3A%22konto%40universum-group.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.universum-group.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.universum-group.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F580%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%7D)**

**Comment by baltpeter** [comment]
Thanks but UNIVERSUM Inkasso GmbH is already in our database: https://www.datenanfragen.de/company/universum-inkasso
