### ISSUE TITLE
New company suggestion: `Franzis Verlag GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#581]
The following suggestion was submitted through the website:

```
{
    "slug": "franzisde",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Franzis Verlag GmbH",
    "address": "Richard-Reitzner-Allee 2\n85540 Haar\nDeutschland",
    "phone": "+49 89 255561000",
    "fax": "+49 89 255561696",
    "email": "datenschutz_franzis@wekanet.de",
    "web": "https://www.franzis.de",
    "sources": [
        "https://www.franzis.de/impressum",
        "https://www.franzis.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/581"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail",
            "type": "email"
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": true
        }
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22franzisde%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Franzis%20Verlag%20GmbH%22%2C%22address%22%3A%22Richard-Reitzner-Allee%202%5Cn85540%20Haar%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2089%20255561000%22%2C%22fax%22%3A%22%2B49%2089%20255561696%22%2C%22email%22%3A%22datenschutz_franzis%40wekanet.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.franzis.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.franzis.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.franzis.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F581%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22email%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Atrue%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
