### ISSUE TITLE
New company suggestion: `ZenLeads, Inc`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#582]
The following suggestion was submitted through the website:

```
{
    "slug": "apolloio",
    "relevant-countries": [
        "all"
    ],
    "name": "ZenLeads, Inc",
    "runs": [
        "apollo.io"
    ],
    "address": "599 2nd Street San Francisco, CA 94107 United States",
    "email": "privacy@apollo.io",
    "web": "https://apollo.io",
    "sources": [
        "https://www.bloomberg.com/profile/company/1630711D:US",
        "https://www.apollo.io/privacy/ccpa-privacy-statement/",
        "https://github.com/datenanfragen/data/issues/582"
    ],
    "comments": [
        "Company is huge database of scraped data from the internet. The company has two different addresses that need to be verified."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22apolloio%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22ZenLeads%2C%20Inc%22%2C%22runs%22%3A%5B%22apollo.io%22%5D%2C%22address%22%3A%22599%202nd%20Street%20San%20Francisco%2C%20CA%2094107%20United%20States%22%2C%22email%22%3A%22privacy%40apollo.io%22%2C%22web%22%3A%22https%3A%2F%2Fapollo.io%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bloomberg.com%2Fprofile%2Fcompany%2F1630711D%3AUS%22%2C%22https%3A%2F%2Fwww.apollo.io%2Fprivacy%2Fccpa-privacy-statement%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F582%22%5D%2C%22comments%22%3A%5B%22Company%20is%20huge%20database%20of%20scraped%20data%20from%20the%20internet.%20The%20company%20has%20two%20different%20addresses%20that%20need%20to%20be%20verified.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
