### ISSUE TITLE
New company suggestion: `X-tract.io`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#583]
The following suggestion was submitted through the website:

```
{
    "slug": "x-tractio",
    "relevant-countries": [
        "us",
        "in"
    ],
    "categories": [
        "social media"
    ],
    "name": "X-tract.io",
    "address": "48 Wall Street,\n11th floor,\nNY 10005, USA",
    "phone": "1 212-918-4456",
    "email": "jithesh@x-tract.io",
    "web": "https://www.x-tract.io/solutions/online-reputation-management",
    "sources": [
        "https://www.x-tract.io/contact-us",
        "https://github.com/datenanfragen/data/issues/583"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "comments": [
        "X-tract.io tracks any conversations, mentions, and sentiments about your brand across multiple channels, such as social media platforms, review websites, and listings. Through automated and intelligent data preparation, the software classifies whether the context of opinions from prospects and customers is positive, negative, or neutral. Moreover, it allows you to integrate reputation data into your own help desk system and create support tickets so you can promptly respond to customer concerns."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22x-tractio%22%2C%22relevant-countries%22%3A%5B%22us%22%2C%22in%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22X-tract.io%22%2C%22address%22%3A%2248%20Wall%20Street%2C%5Cn11th%20floor%2C%5CnNY%2010005%2C%20USA%22%2C%22phone%22%3A%221%20212-918-4456%22%2C%22email%22%3A%22jithesh%40x-tract.io%22%2C%22web%22%3A%22https%3A%2F%2Fwww.x-tract.io%2Fsolutions%2Fonline-reputation-management%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.x-tract.io%2Fcontact-us%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F583%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22X-tract.io%20tracks%20any%20conversations%2C%20mentions%2C%20and%20sentiments%20about%20your%20brand%20across%20multiple%20channels%2C%20such%20as%20social%20media%20platforms%2C%20review%20websites%2C%20and%20listings.%20Through%20automated%20and%20intelligent%20data%20preparation%2C%20the%20software%20classifies%20whether%20the%20context%20of%20opinions%20from%20prospects%20and%20customers%20is%20positive%2C%20negative%2C%20or%20neutral.%20Moreover%2C%20it%20allows%20you%20to%20integrate%20reputation%20data%20into%20your%20own%20help%20desk%20system%20and%20create%20support%20tickets%20so%20you%20can%20promptly%20respond%20to%20customer%20concerns.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
