### ISSUE TITLE
Improving our search engine

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#584]
Inspired by the discussion in #579, I want to use this issue for something we should have done a long time ago but for some reason never got around to: List and discuss the issues we've been having with our current search engine as well as the feature we need/want in a search engine. And of course, also try to decide how we want to move forward in this regard.

As a little bit of background information: Initially, in the very early stages we were using Algolia as our search engine. This worked well and was very flexible but unfortunately they are doing mandatory search query logging and analytics, which is a definite deal breaker for us. Besides, we much rather wanted to self-host our search engine anyway.  
We started looking around for alternatives. I played around with Elastic Search, a somewhat obvious contender, a bit but that didn't meet our requirements, primarily a) because of the ridiculous resource requirements and b) ES doesn't seem to be intended as a public-facing interface, which is something we need.  
Eventually, we found Typesense which I was very euphoric about and which we have now been using [for more than one and a half years](https://github.com/datenanfragen/website/commit/2c6b380b6b26cf3bc14f449be7fbfcd0b7c95d40). Typesense has served us very well and we are essentially happy with it but unfortunately we are not quite sure if it is the right tool for our quite specific use case.  
@zner0L has been playing around with Xapiand as a potential alternative. Maybe he can share his thoughts on that here.

For the record: There have been quite a few improvements to Typesense recently and I have not kept up with that, so some of the following points might not apply anymore.

---

* Our main problem are the deploy times. They are currently waaaaaay too long. We are deleting and then uploading each entry separately, which has ridiculous overhead for each request.  Typesense's new bulk upload endpoint should be able to solve that. I remember doing some very promising tests with that a while ago.
* However: I haven't tested this recently but with Typesense 0.10.0, there were no record updates, so for the bulk upload we would have to drop the whole index and then reimport it, resulting in downtime.
* Due to how we upload new entries, deleted or renamed entries remain in the search results: https://github.com/datenanfragen/data/issues/46
* We want to support 'unverified' entries that rank lower than the verified ones. We might want to store those in a different index and combine them?  
  @zner0L writes: *we need support for search over multiple indexes (with different weights). And we need to be able to to fidget with the weight calculation to rank popular companies higher in the future.*
* We want to import large, external datasets (larger than the current manually added ones) into the database (like the churches, or data from the Rostock open data resources) and are worried that these results completely displace the existing ones, making the search unusable.
* Typesense is quite strict with its schema. We have [found a solution](https://github.com/datenanfragen/data/blob/master/setup-typesense-collection.py) to that that works for us, however we would sometimes like to change the schema. With Typesense, that means dropping the entire index and recreating it, resulting in downtime. That is not a dealbreaker though and we can make do without that.  
  @zner0L comments: *A flexible index which does not require us to fill in all fields of the schema for every entry and can be changed without the need to manipulate all current entries!*
* If we switch to an engine that allows for more complex queries, we need a query timeout to protect against DOS attacks.
* Ideally, it shouldn't be possible to cause problems through the query API (looking at you, Elastic Search…) but we at least need a way of effectively and definitely sanitising queries otherwise.
* Any engine we decide on needs to be easily and cost-efficiently deployable and—even more importantly—updatable. Personally, I would prefer an APT repository that I can simply update from or even a snap that auto-updates but a static binary would also be OK for example. Typesense fits that bill. Xapiand is a little more difficult but I believe @zner0L has already done some work on automating the building process. Elastic Search is definitely *way* to complicated and resource-hungry.

**Comment by baltpeter** [comment]
We have pretty much narrowed down our search (pardon the pun :D) to Typesense and Xapiand (unless we come across another solution that completely blows us away) but as it might be helpful for other people, here is a list of other search engine solutions we have considered:

* http://groonga.org/
* https://github.com/valeriansaliou/sonic
* https://github.com/meilisearch/MeiliDB
* https://github.com/mosuka/blast
* https://github.com/toshi-search/Toshi
* https://vespa.ai/
* https://github.com/nextapps-de/flexsearch (https://github.com/nextapps-de/flexsearch-server)
* https://github.com/nextapps-de/bulksearch

**Comment by kishorenc** [comment]
Thanks for documenting all the details in this issue.

> We are deleting and then uploading each entry separately, which has ridiculous overhead for each request.

This is certainly the way to go. You avoid all the network round-trips and everything will be done in a jiffy. 

> we would have to drop the whole index and then reimport it, resulting in downtime.

In the next v0.12 release (hopefully by next week), there will be support for aliases. Aliases will allow you to have a virtual collection name, say `companies` but have it point to a real collection like `companies_may_13_2020`. Then later on, you can index the next day's data in a new collection called `companies_may_14_2020` and then just update the `companies` alias to the new collection. Instant and with no downtime.

> We want to support 'unverified' entries that rank lower than the verified ones. 

You can easily do this with a desceding sort on an `is_unverified` field such that matching verified entries are listed above unverified ones.

> We want to import large, external datasets...and are worried that these results completely displace the existing ones, making the search unusable.

The best way to approach such an issue is to give the power to the end-user to choose what kind of organization they want to search on. We will be launching an integration with Instantsearch.js very soon, so that allow you to rapidly build a better search interface. 

> A flexible index which does not require us to fill in all fields of the schema for every entry

Again, this will be possible in the v0.12 release: you can mark fields as optional so won't be forced to provide a default value.

> but we at least need a way of effectively and definitely sanitising queries otherwise.

I can understand why you would want rate limiting. Can you please elaborate what you mean by sanitising queries?

> Personally, I would prefer an APT repository

Typesense publishes DEB packages now, in addition to binaries. We're also going to launch clustering support, again in v0.12 for high availability. It will also make it easy to do rolling updates without downtime.

**Comment by baltpeter** [comment]
Thanks for the suggestions, @kishorenc! That sounds really good. I am especially looking forward to the alias support, that will be awesome to have. Actually, all of the changes you mention sound great, I can't decide which ones I like best. :D

> Can you please elaborate what you mean by sanitising queries?

I'm pretty sure this doesn't apply to Typesense but when we were researching Elastic Search, they mentioned in their documentation that you shouldn't expose the actual query interface to end users as it way too powerful and simply not designed to be public. Apparently, users would be able to submit malicious queries.  
To be honest, I am not entirely sure what the exact specifics around that are. @zner0L should be able to elaborate on that though, he's also the one who suggested adding this to the list.

**Comment by kishorenc** [comment]
👍 Typesense `v0.12.0` is out and it has all those goodies. Happy to hear further feedback on other features we can add that will make your job easier :)

**Comment by baltpeter** [comment]
Hi @kishorenc, just wanted to say thanks again. We have now (finally) updated to Typesense 0.14 and are really happy with it!

This issue can now be closed.
