### ISSUE TITLE
New company suggestion: `Hostinger International, Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#585]
The following suggestion was submitted through the website:

```
{
    "slug": "hostingercom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Hostinger International, Ltd",
    "address": "61 Lordou Vironos Street\n6023 Larnaca, Cyprus",
    "email": "gdpr@hostinger.com",
    "web": "https://www.hostinger.com/",
    "suggested-transport-medium": "email",
    "sources": [
        "https://github.com/datenanfragen/data/issues/585"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hostingercom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Hostinger%20International%2C%20Ltd%22%2C%22address%22%3A%2261%20Lordou%20Vironos%20Street%5Cn6023%20Larnaca%2C%20Cyprus%22%2C%22email%22%3A%22gdpr%40hostinger.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hostinger.com%2F%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F585%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
