### ISSUE TITLE
New company suggestion: `6Minutes Media GmbH `

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#586]
The following suggestion was submitted through the website:

```
{
    "slug": "mydealzde",
    "relevant-countries": [
        "de"
    ],
    "name": "6Minutes Media GmbH ",
    "runs": [
        "mydealz.de"
    ],
    "address": "6Minutes Media GmbH\nTorstr. 164\n10115 Berlin, Deutschland ",
    "email": "privacy@mydealz.de ",
    "web": "https://www.mydealz.de",
    "sources": [
        "https://www.mydealz.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/586"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mydealzde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%226Minutes%20Media%20GmbH%20%22%2C%22runs%22%3A%5B%22mydealz.de%22%5D%2C%22address%22%3A%226Minutes%20Media%20GmbH%5CnTorstr.%20164%5Cn10115%20Berlin%2C%20Deutschland%20%22%2C%22email%22%3A%22privacy%40mydealz.de%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mydealz.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mydealz.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F586%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
