### ISSUE TITLE
New company suggestion: `Jimmy Fairly`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#588]
The following suggestion was submitted through the website:

```
{
    "slug": "jimmyfairlycom",
    "relevant-countries": [
        "fr"
    ],
    "categories": [
        "ads"
    ],
    "name": "Jimmy Fairly",
    "address": "23, rue du Mail, 75002 Paris.",
    "email": "dpo@jimmyfairly.com",
    "web": "https://www.jimmyfairly.com",
    "sources": [
        "https://www.jimmyfairly.com/pages/legal",
        "https://github.com/datenanfragen/data/issues/588"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22jimmyfairlycom%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Jimmy%20Fairly%22%2C%22address%22%3A%2223%2C%20rue%20du%20Mail%2C%2075002%20Paris.%22%2C%22email%22%3A%22dpo%40jimmyfairly.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.jimmyfairly.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.jimmyfairly.com%2Fpages%2Flegal%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F588%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
