### ISSUE TITLE
Suggested update for company `match-group`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#589]
The following suggestion was submitted through the website:

```
{
    "slug": "match-group",
    "relevant-countries": [
        "at",
        "de",
        "fr",
        "it",
        "nl",
        "be",
        "bg",
        "dk",
        "fi",
        "gr",
        "ie",
        "hr",
        "lv",
        "lt",
        "lu",
        "mt",
        "no",
        "pl",
        "pt",
        "ro",
        "se",
        "sk",
        "si",
        "es",
        "cz",
        "hu",
        "cy"
    ],
    "categories": [
        "social media"
    ],
    "name": "MTCH Technology Services Limited",
    "runs": [
        "Tinder (tinder.com)",
        "Match.com (match.com)"
    ],
    "address": "MTCH Technology Services Limited\nTinder\nWeWork Charlemont Exchange\n42 Charlemont Street\nDublin 2, D02 R593\nIreland",
    "email": "privacyinquiries@gotinder.com",
    "web": "http://mtch.com",
    "sources": [
        "https://policies.tinder.com/privacy/intl/en",
        "https://github.com/datenanfragen/data/issues/589"
    ],
    "request-language": "en",
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22match-group%22%2C%22relevant-countries%22%3A%5B%22at%22%2C%22de%22%2C%22fr%22%2C%22it%22%2C%22nl%22%2C%22be%22%2C%22bg%22%2C%22dk%22%2C%22fi%22%2C%22gr%22%2C%22ie%22%2C%22hr%22%2C%22lv%22%2C%22lt%22%2C%22lu%22%2C%22mt%22%2C%22no%22%2C%22pl%22%2C%22pt%22%2C%22ro%22%2C%22se%22%2C%22sk%22%2C%22si%22%2C%22es%22%2C%22cz%22%2C%22hu%22%2C%22cy%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22MTCH%20Technology%20Services%20Limited%22%2C%22runs%22%3A%5B%22Tinder%20(tinder.com)%22%2C%22Match.com%20(match.com)%22%5D%2C%22address%22%3A%22MTCH%20Technology%20Services%20Limited%5CnTinder%5CnWeWork%20Charlemont%20Exchange%5Cn42%20Charlemont%20Street%5CnDublin%202%2C%20D02%20R593%5CnIreland%22%2C%22email%22%3A%22privacyinquiries%40gotinder.com%22%2C%22web%22%3A%22http%3A%2F%2Fmtch.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpolicies.tinder.com%2Fprivacy%2Fintl%2Fen%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F589%22%5D%2C%22request-language%22%3A%22en%22%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Good point, thank you!
