### ISSUE TITLE
New company suggestion: `HTC Europe Co. Ltd`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#594]
The following suggestion was submitted through the website:

```
{
    "slug": "htc-europe-co-ltd",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment",
        "social media",
        "commerce",
        null
    ],
    "name": "HTC Europe Co. Ltd",
    "runs": [
        "Viveport"
    ],
    "address": "HTC Europe Co. Ltd \nSalamanca, Wellington Street\nSlough, Berkshire SL1 1YP, U.K.\nCompany registration number: 04826012\nAttention: Privacy Administrator ",
    "email": "global-privacy@htc.com",
    "web": "htc.com",
    "sources": [
        "https://www.htc.com/us/terms/privacy/#topic-1-10",
        "https://www.viveport.com/",
        "https://github.com/datenanfragen/data/issues/594"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22htc-europe-co-ltd%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%2C%22commerce%22%2Cnull%5D%2C%22name%22%3A%22HTC%20Europe%20Co.%20Ltd%22%2C%22runs%22%3A%5B%22Viveport%22%5D%2C%22address%22%3A%22HTC%20Europe%20Co.%20Ltd%20%5CnSalamanca%2C%20Wellington%20Street%5CnSlough%2C%20Berkshire%20SL1%201YP%2C%20U.K.%5CnCompany%20registration%20number%3A%2004826012%5CnAttention%3A%20Privacy%20Administrator%20%22%2C%22email%22%3A%22global-privacy%40htc.com%22%2C%22web%22%3A%22htc.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.htc.com%2Fus%2Fterms%2Fprivacy%2F%23topic-1-10%22%2C%22https%3A%2F%2Fwww.viveport.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F594%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
