### ISSUE TITLE
New company suggestion: `ottonova Holding AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#596]
The following suggestion was submitted through the website:

```
{
    "slug": "ottonova-holding-ag",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "insurance"
    ],
    "name": "ottonova Holding AG",
    "runs": [
        "ottonova services GmbH",
        "ottonova Krankenversicherung AG"
    ],
    "address": "Ottostraße 4\n80333 München",
    "phone": "+49 89 262098000",
    "email": "ottonova@iitr.de",
    "web": "www.ottonova.de",
    "sources": [
        "www.ottonova.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/596"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ottonova-holding-ag%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22ottonova%20Holding%20AG%22%2C%22runs%22%3A%5B%22ottonova%20services%20GmbH%22%2C%22ottonova%20Krankenversicherung%20AG%22%5D%2C%22address%22%3A%22Ottostra%C3%9Fe%204%5Cn80333%20M%C3%BCnchen%22%2C%22phone%22%3A%22%2B49%2089%20262098000%22%2C%22email%22%3A%22ottonova%40iitr.de%22%2C%22web%22%3A%22www.ottonova.de%22%2C%22sources%22%3A%5B%22www.ottonova.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F596%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
