### ISSUE TITLE
New company suggestion: `Hetzner Online GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#597]
The following suggestion was submitted through the website:

```
{
    "slug": "hetzner-online-gmbh",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Hetzner Online GmbH",
    "address": "Industriestr. 25\n91710 Gunzenhausen ",
    "phone": "+49 9831 5050",
    "fax": "+49 9831 5053",
    "email": "data-protection@hetzner.com.",
    "web": "www.hetzner.de",
    "sources": [
        "www.hetzner.de/rechtliches/datenschutz",
        "https://github.com/datenanfragen/data/issues/597"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hetzner-online-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Hetzner%20Online%20GmbH%22%2C%22address%22%3A%22Industriestr.%2025%5Cn91710%20Gunzenhausen%20%22%2C%22phone%22%3A%22%2B49%209831%205050%22%2C%22fax%22%3A%22%2B49%209831%205053%22%2C%22email%22%3A%22data-protection%40hetzner.com.%22%2C%22web%22%3A%22www.hetzner.de%22%2C%22sources%22%3A%5B%22www.hetzner.de%2Frechtliches%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F597%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
