### ISSUE TITLE
New company suggestion: `InvoZone`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#603]
The following suggestion was submitted through the website:

```
{
    "slug": "invozonecom",
    "relevant-countries": [
        "my",
        "pk"
    ],
    "categories": [
        "collection agency"
    ],
    "name": "InvoZone",
    "address": "F2-2-1, Midfields 2, Sungai Besi, 57100, Kuala Lumpur, Malaysia",
    "phone": "+60 11 2323 4533",
    "email": "info@invozone.com",
    "web": "https://invozone.com/",
    "sources": [
        "https://invozone.com/about-us/",
        "https://github.com/InvoZone",
        "https://en.yelp.my/biz/invozone-kuala-lumpur",
        "https://github.com/datenanfragen/data/issues/603"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "comments": [
        "Based in Kuala Lumpur, we at InvoZone aim to grab the leading position as a software company. We develop innovative software solutions for enterprises located all across the globe, helping them grow their business by increasing their online presence. Our focus lies in, but we are not restricted to, designing, software engineering, and development solutions.\nFor several years, we have been building software products using a team of designers and business people. The combined efforts of this team create a tech-savvy environment with an acute business sense. At InvoZone, we work to be at the front of web-based business initiatives. Thereby, we offer one-stop-shop for all your web business needs.\nOur unmatched services give us the confidence to meet your objectives in solving technical challenges. This is how InvoZone built its reputation as well; by providing innovative software solutions and second-to-none engineering and support services."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22invozonecom%22%2C%22relevant-countries%22%3A%5B%22my%22%2C%22pk%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22InvoZone%22%2C%22address%22%3A%22F2-2-1%2C%20Midfields%202%2C%20Sungai%20Besi%2C%2057100%2C%20Kuala%20Lumpur%2C%20Malaysia%22%2C%22phone%22%3A%22%2B60%2011%202323%204533%22%2C%22email%22%3A%22info%40invozone.com%22%2C%22web%22%3A%22https%3A%2F%2Finvozone.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Finvozone.com%2Fabout-us%2F%22%2C%22https%3A%2F%2Fgithub.com%2FInvoZone%22%2C%22https%3A%2F%2Fen.yelp.my%2Fbiz%2Finvozone-kuala-lumpur%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F603%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Based%20in%20Kuala%20Lumpur%2C%20we%20at%20InvoZone%20aim%20to%20grab%20the%20leading%20position%20as%20a%20software%20company.%20We%20develop%20innovative%20software%20solutions%20for%20enterprises%20located%20all%20across%20the%20globe%2C%20helping%20them%20grow%20their%20business%20by%20increasing%20their%20online%20presence.%20Our%20focus%20lies%20in%2C%20but%20we%20are%20not%20restricted%20to%2C%20designing%2C%20software%20engineering%2C%20and%20development%20solutions.%5CnFor%20several%20years%2C%20we%20have%20been%20building%20software%20products%20using%20a%20team%20of%20designers%20and%20business%20people.%20The%20combined%20efforts%20of%20this%20team%20create%20a%20tech-savvy%20environment%20with%20an%20acute%20business%20sense.%20At%20InvoZone%2C%20we%20work%20to%20be%20at%20the%20front%20of%20web-based%20business%20initiatives.%20Thereby%2C%20we%20offer%20one-stop-shop%20for%20all%20your%20web%20business%20needs.%5CnOur%20unmatched%20services%20give%20us%20the%20confidence%20to%20meet%20your%20objectives%20in%20solving%20technical%20challenges.%20This%20is%20how%20InvoZone%20built%20its%20reputation%20as%20well%3B%20by%20providing%20innovative%20software%20solutions%20and%20second-to-none%20engineering%20and%20support%20services.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
