### ISSUE TITLE
New company suggestion: `BV Bestseller Verlag GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#608]
The following suggestion was submitted through the website:

```
{
    "slug": "bv-bestseller-verlag-gmbh",
    "relevant-countries": [
        "de"
    ],
    "name": "BV Bestseller Verlag GmbH",
    "runs": [
        "dirkkreuter.com"
    ],
    "address": "Universitätsstraße 60\n44789 Bochum",
    "sources": [
        "https://dirkkreuter.com/impressum/",
        "https://bestseller-verlag.com/kontakt/",
        "https://github.com/datenanfragen/data/issues/608"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bv-bestseller-verlag-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22BV%20Bestseller%20Verlag%20GmbH%22%2C%22runs%22%3A%5B%22dirkkreuter.com%22%5D%2C%22address%22%3A%22Universit%C3%A4tsstra%C3%9Fe%2060%5Cn44789%20Bochum%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdirkkreuter.com%2Fimpressum%2F%22%2C%22https%3A%2F%2Fbestseller-verlag.com%2Fkontakt%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F608%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
