### ISSUE TITLE
New company suggestion: `Panic Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#611]
The following suggestion was submitted through the website:

```
{
    "slug": "paniccom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Panic Inc.",
    "runs": [
        "Coda",
        "http://💩.la",
        "http://🚚.la",
        "http://🍃.la"
    ],
    "address": "315 SW 11th Ave 4th Floor, Portland OR, 97205",
    "email": "gdpr@panic.com.",
    "web": "https://panic.com/",
    "sources": [
        "https://panic.com/privacy/",
        "https://panic.com/blog/the-worlds-first-emoji-domain/",
        "https://panic.com/",
        "https://github.com/datenanfragen/data/issues/611"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22paniccom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Panic%20Inc.%22%2C%22runs%22%3A%5B%22Coda%22%2C%22http%3A%2F%2F%F0%9F%92%A9.la%22%2C%22http%3A%2F%2F%F0%9F%9A%9A.la%22%2C%22http%3A%2F%2F%F0%9F%8D%83.la%22%5D%2C%22address%22%3A%22315%20SW%2011th%20Ave%204th%20Floor%2C%20Portland%20OR%2C%2097205%22%2C%22email%22%3A%22gdpr%40panic.com.%22%2C%22web%22%3A%22https%3A%2F%2Fpanic.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpanic.com%2Fprivacy%2F%22%2C%22https%3A%2F%2Fpanic.com%2Fblog%2Fthe-worlds-first-emoji-domain%2F%22%2C%22https%3A%2F%2Fpanic.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F611%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
