### ISSUE TITLE
New company suggestion: `StarLeaf`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#619]
The following suggestion was submitted through the website:

```
{
    "slug": "starleaf",
    "relevant-countries": [
        "gb",
        "fr",
        "de",
        "br",
        "cn",
        "jp",
        "nl",
        "it",
        "nz",
        "no",
        "se",
        "ch",
        "us"
    ],
    "name": "StarLeaf",
    "address": "Building 7, Hatters Lane\nWatford WD18 8YN\nUnited Kingdom",
    "phone": "+44 330 440 1847",
    "email": "infosec@starleaf.com",
    "web": "www.starleaf.com",
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "sources": [
        "https://github.com/datenanfragen/data/issues/619"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22starleaf%22%2C%22relevant-countries%22%3A%5B%22gb%22%2C%22fr%22%2C%22de%22%2C%22br%22%2C%22cn%22%2C%22jp%22%2C%22nl%22%2C%22it%22%2C%22nz%22%2C%22no%22%2C%22se%22%2C%22ch%22%2C%22us%22%5D%2C%22name%22%3A%22StarLeaf%22%2C%22address%22%3A%22Building%207%2C%20Hatters%20Lane%5CnWatford%20WD18%208YN%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%20330%20440%201847%22%2C%22email%22%3A%22infosec%40starleaf.com%22%2C%22web%22%3A%22www.starleaf.com%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F619%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
