### ISSUE TITLE
Suggested update for company `blablacar`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#620]
The following suggestion was submitted through the website:

```
{
    "slug": "blablacar",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Comuto SA",
    "runs": [
        "BlaBlaCar (www.blablacar.de)"
    ],
    "address": "84, avenue de la République\n75011 Paris\nFrance",
    "email": "dataprotection@blablacar.com",
    "web": "https://www.blablacar.de/",
    "sources": [
        "https://www.blablacar.de/ueber-uns/datenschutzerklaerung",
        "https://www.blablacar.de/ueber-uns/impressum",
        "https://www.blablacar.co.uk/about-us/privacy-policy",
        "https://github.com/datenanfragen/data/issues/620"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22blablacar%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Comuto%20SA%22%2C%22runs%22%3A%5B%22BlaBlaCar%20(www.blablacar.de)%22%5D%2C%22address%22%3A%2284%2C%20avenue%20de%20la%20R%C3%A9publique%5Cn75011%20Paris%5CnFrance%22%2C%22email%22%3A%22dataprotection%40blablacar.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.blablacar.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.blablacar.de%2Fueber-uns%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fwww.blablacar.de%2Fueber-uns%2Fimpressum%22%2C%22https%3A%2F%2Fwww.blablacar.co.uk%2Fabout-us%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F620%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
