### ISSUE TITLE
New company suggestion: `Instacart`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#621]
The following suggestion was submitted through the website:

```
{
    "slug": "instacartcom",
    "relevant-countries": [
        "us"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Instacart",
    "address": "Instacart\n50 Beale Street, Suite 600\nSan Francisco, California 94105",
    "phone": "1-888-246-7822",
    "email": "privacy@instacart.com ",
    "web": "https://www.instacart.com/privacy",
    "sources": [
        "https://github.com/datenanfragen/data/issues/621"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22instacartcom%22%2C%22relevant-countries%22%3A%5B%22us%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Instacart%22%2C%22address%22%3A%22Instacart%5Cn50%20Beale%20Street%2C%20Suite%20600%5CnSan%20Francisco%2C%20California%2094105%22%2C%22phone%22%3A%221-888-246-7822%22%2C%22email%22%3A%22privacy%40instacart.com%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.instacart.com%2Fprivacy%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F621%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks but this company doesn't seem relevant to EU citizens.

**Comment by baltpeter** [comment]
For future reference: We have now adopted an official [policy on the companies we are interested in](https://github.com/datenanfragen/data#companies-we-are-interested-in).
