### ISSUE TITLE
New company suggestion: `meinestadt.de GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#622]
The following suggestion was submitted through the website:

```
{
    "slug": "meinestadtde",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "addresses"
    ],
    "name": "meinestadt.de GmbH",
    "address": "Waidmarkt 11\n50676 Köln",
    "phone": "+49 221 995330",
    "email": "datenschutz@meinestadt.de",
    "web": "https://www.meinestadt.de/datenschutzerklaerung#18",
    "suggested-transport-medium": "email",
    "sources": [
        "https://github.com/datenanfragen/data/issues/622"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22meinestadtde%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22meinestadt.de%20GmbH%22%2C%22address%22%3A%22Waidmarkt%2011%5Cn50676%20K%C3%B6ln%22%2C%22phone%22%3A%22%2B49%20221%20995330%22%2C%22email%22%3A%22datenschutz%40meinestadt.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.meinestadt.de%2Fdatenschutzerklaerung%2318%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F622%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
