### ISSUE TITLE
Suggested update for company `twitch`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#623]
The following suggestion was submitted through the website:

```
{
    "slug": "twitch",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "social media"
    ],
    "name": "Twitch Interactive, Inc.",
    "address": "225 Bush Street\n9th Floor\nSan Francisco\nCA 94104\nUnited States of America\n\nEU:\nUK Limited von Twitch Interactive, Inc\n1 New Oxford Street WC1A 1BA, UK",
    "email": "privacy@twitch.tv",
    "web": "https://www.twitch.tv",
    "sources": [
        "https://www.twitch.tv/p/legal/privacy-policy/",
        "https://www.twitch.tv/p/legal/terms-of-service/",
        "https://github.com/datenanfragen/data/issues/623"
    ],
    "request-language": "en",
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22twitch%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Twitch%20Interactive%2C%20Inc.%22%2C%22address%22%3A%22225%20Bush%20Street%5Cn9th%20Floor%5CnSan%20Francisco%5CnCA%2094104%5CnUnited%20States%20of%20America%5Cn%5CnEU%3A%5CnUK%20Limited%20von%20Twitch%20Interactive%2C%20Inc%5Cn1%20New%20Oxford%20Street%20WC1A%201BA%2C%20UK%22%2C%22email%22%3A%22privacy%40twitch.tv%22%2C%22web%22%3A%22https%3A%2F%2Fwww.twitch.tv%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.twitch.tv%2Fp%2Flegal%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fwww.twitch.tv%2Fp%2Flegal%2Fterms-of-service%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F623%22%5D%2C%22request-language%22%3A%22en%22%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
