### ISSUE TITLE
New company suggestion: `DNA`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#624]
The following suggestion was submitted through the website:

```
{
    "slug": "dna",
    "relevant-countries": [
        "fi"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "DNA",
    "address": "DNA Oyj\nLäkkisepäntie 21\n00620 Helsinki",
    "sources": [
        "dna.fi",
        "https://github.com/datenanfragen/data/issues/624"
    ],
    "comments": [
        "A large part of finnish traffic goes through their network. Their routers force you to use DNA's DNS, so almost no one will use anything else.\n\nI couldn't find a customer support email. I think you are supposed to contact them by logging in first, at which point they call you and ask you for your SSN, which is not a good way of authentication and illegal IIRC."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22dna%22%2C%22relevant-countries%22%3A%5B%22fi%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22DNA%22%2C%22address%22%3A%22DNA%20Oyj%5CnL%C3%A4kkisep%C3%A4ntie%2021%5Cn00620%20Helsinki%22%2C%22sources%22%3A%5B%22dna.fi%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F624%22%5D%2C%22comments%22%3A%5B%22A%20large%20part%20of%20finnish%20traffic%20goes%20through%20their%20network.%20Their%20routers%20force%20you%20to%20use%20DNA's%20DNS%2C%20so%20almost%20no%20one%20will%20use%20anything%20else.%5Cn%5CnI%20couldn't%20find%20a%20customer%20support%20email.%20I%20think%20you%20are%20supposed%20to%20contact%20them%20by%20logging%20in%20first%2C%20at%20which%20point%20they%20call%20you%20and%20ask%20you%20for%20your%20SSN%2C%20which%20is%20not%20a%20good%20way%20of%20authentication%20and%20illegal%20IIRC.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!

**Comment by baltpeter** [comment]
The customer support mail seems to be service@dna.fi as per [this](https://corporate.dna.fi/tietosuoja/tietosuojaseloste) btw. :)
