### ISSUE TITLE
New company suggestion: `TARGOBANK AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#627]
The following suggestion was submitted through the website:

```
{
    "slug": "targobank-ag",
    "relevant-countries": [
        null
    ],
    "categories": [
        null
    ],
    "name": "TARGOBANK AG",
    "address": "Kasernenstr. 10\n40213 Düsseldorf",
    "phone": "0211/8984-0",
    "fax": "0211/8984-1222",
    "email": "kontakt@targobank.de",
    "web": "www.targobank.de",
    "sources": [
        "www.targobank.de",
        "https://github.com/datenanfragen/data/issues/627"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22targobank-ag%22%2C%22relevant-countries%22%3A%5Bnull%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22TARGOBANK%20AG%22%2C%22address%22%3A%22Kasernenstr.%2010%5Cn40213%20D%C3%BCsseldorf%22%2C%22phone%22%3A%220211%2F8984-0%22%2C%22fax%22%3A%220211%2F8984-1222%22%2C%22email%22%3A%22kontakt%40targobank.de%22%2C%22web%22%3A%22www.targobank.de%22%2C%22sources%22%3A%5B%22www.targobank.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F627%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks for the suggestion! We do have a record on Targobank already: https://www.datenanfragen.de/company/targobank

However, they seem to have changed their legal form (https://www.northdata.de/?id=4684135071), so I'll update that.
