### ISSUE TITLE
Suggested update for company `gitlab-com`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#628]
The following suggestion was submitted through the website:

```
{
    "slug": "gitlab-com",
    "relevant-countries": [
        "all"
    ],
    "name": "GitLab B.V.",
    "runs": [
        "GitLab Inc."
    ],
    "address": "Ondiep 108\nUtrecht, 3552 EK\nNetherlands",
    "email": "gdpr-request@gitlab.com",
    "sources": [
        "https://about.gitlab.com/privacy/",
        "https://www.bloomberg.com/profiles/companies/1295950D:NA-gitlab-bv",
        "after sending a request, they stated that \"If you have any additional queries, please contact gdpr-request@gitlab.com\"",
        "https://github.com/datenanfragen/data/issues/628"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "E-Mail",
            "type": "input"
        },
        {
            "desc": "Username",
            "type": "input"
        }
    ],
    "request-language": "en",
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gitlab-com%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22GitLab%20B.V.%22%2C%22runs%22%3A%5B%22GitLab%20Inc.%22%5D%2C%22address%22%3A%22Ondiep%20108%5CnUtrecht%2C%203552%20EK%5CnNetherlands%22%2C%22email%22%3A%22gdpr-request%40gitlab.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fabout.gitlab.com%2Fprivacy%2F%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fprofiles%2Fcompanies%2F1295950D%3ANA-gitlab-bv%22%2C%22after%20sending%20a%20request%2C%20they%20stated%20that%20%5C%22If%20you%20have%20any%20additional%20queries%2C%20please%20contact%20gdpr-request%40gitlab.com%5C%22%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F628%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22input%22%7D%2C%7B%22desc%22%3A%22Username%22%2C%22type%22%3A%22input%22%7D%5D%2C%22request-language%22%3A%22en%22%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks, this is confirmed by: https://about.gitlab.com/handbook/support/workflows/gdpr_article-15.html
