### ISSUE TITLE
New company suggestion: `Tipico`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#629]
The following suggestion was submitted through the website:

```
{
    "slug": "tipico",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads"
    ],
    "name": "Tipico",
    "address": "Tipico Tower\nVjal Portomaso\nSt. Julian's STJ 4011\nMalta",
    "sources": [
        "https://sports.tipico.de/legalNotice",
        "https://github.com/datenanfragen/data/issues/629"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22tipico%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Tipico%22%2C%22address%22%3A%22Tipico%20Tower%5CnVjal%20Portomaso%5CnSt.%20Julian's%20STJ%204011%5CnMalta%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fsports.tipico.de%2FlegalNotice%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F629%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
