### ISSUE TITLE
New company suggestion: `SWM Versorgungs GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#630]
The following suggestion was submitted through the website:

```
{
    "slug": "swmde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "utility"
    ],
    "name": "SWM Versorgungs GmbH",
    "address": "SWM Versorgungs GmbH\nDatenschutzbeauftragter\nEmmy-Noether-Straße 2\n80992 München",
    "email": "datenschutz.versorgung@swm.de",
    "web": "https://swm.de",
    "sources": [
        "https://www.swm.de/privatkunden/info/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/630"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22swmde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22SWM%20Versorgungs%20GmbH%22%2C%22address%22%3A%22SWM%20Versorgungs%20GmbH%5CnDatenschutzbeauftragter%5CnEmmy-Noether-Stra%C3%9Fe%202%5Cn80992%20M%C3%BCnchen%22%2C%22email%22%3A%22datenschutz.versorgung%40swm.de%22%2C%22web%22%3A%22https%3A%2F%2Fswm.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.swm.de%2Fprivatkunden%2Finfo%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F630%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
