### ISSUE TITLE
New company suggestion: `SWM Infrastruktur GmbH & Co. KG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#633]
The following suggestion was submitted through the website:

```
{
    "slug": "swm-infrastrukturde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "utility"
    ],
    "name": "SWM Infrastruktur GmbH & Co. KG",
    "address": "SWM Infrastruktur GmbH & Co. KG\nDatenschutzbeauftragter\nEmmy-Noether-Straße 2\n80992 München",
    "email": "infrastruktur@swm-infrastruktur.de",
    "web": "https://www.swm-infrastruktur.de",
    "sources": [
        "https://www.swm-infrastruktur.de/info/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/633"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22swm-infrastrukturde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22SWM%20Infrastruktur%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22SWM%20Infrastruktur%20GmbH%20%26%20Co.%20KG%5CnDatenschutzbeauftragter%5CnEmmy-Noether-Stra%C3%9Fe%202%5Cn80992%20M%C3%BCnchen%22%2C%22email%22%3A%22infrastruktur%40swm-infrastruktur.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.swm-infrastruktur.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.swm-infrastruktur.de%2Finfo%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F633%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
