### ISSUE TITLE
Suggested update for company `creditreform-boniversum`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#634]
The following suggestion was submitted through the website:

```
{
    "slug": "creditreform-boniversum",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "credit agency"
    ],
    "name": "Creditreform Boniversum GmbH",
    "address": "Hellersbergstraße 11\n41460 Neuss\nDeutschland",
    "phone": "+49 2131 109501",
    "fax": "+49 2131 109557",
    "email": "selbstauskunft@boniversum.de",
    "web": "https://www.boniversum.de",
    "sources": [
        "https://www.boniversum.de/selbstauskunft/",
        "https://www.boniversum.de/datenschutzerklaerung/",
        "https://www.boniversum.de/impressum/",
        "https://github.com/datenanfragen/data/issues/634"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Adresse",
            "type": "address"
        },
        {
            "desc": "Geburtsdatum",
            "type": "birthdate"
        }
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22creditreform-boniversum%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22credit%20agency%22%5D%2C%22name%22%3A%22Creditreform%20Boniversum%20GmbH%22%2C%22address%22%3A%22Hellersbergstra%C3%9Fe%2011%5Cn41460%20Neuss%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%202131%20109501%22%2C%22fax%22%3A%22%2B49%202131%20109557%22%2C%22email%22%3A%22selbstauskunft%40boniversum.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.boniversum.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.boniversum.de%2Fselbstauskunft%2F%22%2C%22https%3A%2F%2Fwww.boniversum.de%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fwww.boniversum.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F634%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%2C%7B%22desc%22%3A%22Geburtsdatum%22%2C%22type%22%3A%22birthdate%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
