### ISSUE TITLE
New company suggestion: `Blablacar`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#635]
The following suggestion was submitted through the website:

```
{
    "slug": "blablacarde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "travel"
    ],
    "name": "Blablacar",
    "address": "Comuto SA\n84 av. de la République\n75011 Paris\nFrance",
    "web": "https://www.blablacar.de/",
    "sources": [
        null,
        "https://github.com/datenanfragen/data/issues/635"
    ],
    "required-elements": [
        {
            "type": "input"
        }
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22blablacarde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Blablacar%22%2C%22address%22%3A%22Comuto%20SA%5Cn84%20av.%20de%20la%20R%C3%A9publique%5Cn75011%20Paris%5CnFrance%22%2C%22web%22%3A%22https%3A%2F%2Fwww.blablacar.de%2F%22%2C%22sources%22%3A%5Bnull%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F635%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%7D)**

**Comment by baltpeter** [comment]
Thanks but we already have this record: https://www.datenanfragen.de/company/blablacar/
