### ISSUE TITLE
Suggested update for company `crifbuergel`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#636]
The following suggestion was submitted through the website:

```
{
    "slug": "crifbuergel",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "credit agency",
        "addresses"
    ],
    "name": "CRIF Bürgel GmbH",
    "address": "Team Selbstauskunft\nFriesenweg 4, Haus 12\n22763 Hamburg\nDeutschland",
    "phone": "+49 40 898030",
    "fax": "+49 40 89803309",
    "email": "datenschutz.de@crif.com",
    "web": "https://www.crifbuergel.de",
    "sources": [
        "https://www.crifbuergel.de/de/kontakt/selbstauskunft",
        "https://github.com/datenanfragen/data/issues/636"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Entgegen der Angabe auf der CRIF Bürgel-Webseite sollte eine Personalausweiskopie – wenn überhaupt – nur auf explizite Nachfrage verschickt werden und nicht direkt mit dem ersten Schreiben."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22crifbuergel%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22credit%20agency%22%2C%22addresses%22%5D%2C%22name%22%3A%22CRIF%20B%C3%BCrgel%20GmbH%22%2C%22address%22%3A%22Team%20Selbstauskunft%5CnFriesenweg%204%2C%20Haus%2012%5Cn22763%20Hamburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2040%20898030%22%2C%22fax%22%3A%22%2B49%2040%2089803309%22%2C%22email%22%3A%22datenschutz.de%40crif.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.crifbuergel.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.crifbuergel.de%2Fde%2Fkontakt%2Fselbstauskunft%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F636%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Entgegen%20der%20Angabe%20auf%20der%20CRIF%20B%C3%BCrgel-Webseite%20sollte%20eine%20Personalausweiskopie%20%E2%80%93%20wenn%20%C3%BCberhaupt%20%E2%80%93%20nur%20auf%20explizite%20Nachfrage%20verschickt%20werden%20und%20nicht%20direkt%20mit%20dem%20ersten%20Schreiben.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
