### ISSUE TITLE
Suggested update for company `infoscore`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#637]
The following suggestion was submitted through the website:

```
{
    "slug": "infoscore",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "credit agency"
    ],
    "name": "infoscore Consumer Data GmbH",
    "address": "Rheinstraße 99\n76532 Baden-Baden\nDeutschland",
    "phone": "+49 7221 50403200",
    "fax": "+49 7221 50403201",
    "email": "datenschutz@arvato-infoscore.de",
    "web": "https://finance.arvato.com/de/verbraucher/selbstauskunft/infoscore-consumer-data-gmbh.html",
    "sources": [
        "https://finance.arvato.com/de/verbraucher/selbstauskunft.html",
        "https://www.arvato.com/content/dam/arvato/documents/financial-solutions/Antrag_Selbstauskunft_infoscore_Consumer_Data_GmbH.pdf",
        "https://finance.arvato.com/content/dam/arvato/arvato-financial-solutions/de/documents/service-fuer-verbraucher/informationsblatt_artikel_14_EUDSGVO.pdf",
        "https://github.com/datenanfragen/data/issues/100",
        "https://finance.arvato.com/4a2850/globalassets/02-documents/04-ger/07-icd/antrag_selbstauskunft.pdf",
        "https://github.com/datenanfragen/data/issues/637"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name"
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "Erbitten Anschriften der letzten fünf Jahre für vollständigere Auskunft."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22infoscore%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22credit%20agency%22%5D%2C%22name%22%3A%22infoscore%20Consumer%20Data%20GmbH%22%2C%22address%22%3A%22Rheinstra%C3%9Fe%2099%5Cn76532%20Baden-Baden%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%207221%2050403200%22%2C%22fax%22%3A%22%2B49%207221%2050403201%22%2C%22email%22%3A%22datenschutz%40arvato-infoscore.de%22%2C%22web%22%3A%22https%3A%2F%2Ffinance.arvato.com%2Fde%2Fverbraucher%2Fselbstauskunft%2Finfoscore-consumer-data-gmbh.html%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffinance.arvato.com%2Fde%2Fverbraucher%2Fselbstauskunft.html%22%2C%22https%3A%2F%2Fwww.arvato.com%2Fcontent%2Fdam%2Farvato%2Fdocuments%2Ffinancial-solutions%2FAntrag_Selbstauskunft_infoscore_Consumer_Data_GmbH.pdf%22%2C%22https%3A%2F%2Ffinance.arvato.com%2Fcontent%2Fdam%2Farvato%2Farvato-financial-solutions%2Fde%2Fdocuments%2Fservice-fuer-verbraucher%2Finformationsblatt_artikel_14_EUDSGVO.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F100%22%2C%22https%3A%2F%2Ffinance.arvato.com%2F4a2850%2Fglobalassets%2F02-documents%2F04-ger%2F07-icd%2Fantrag_selbstauskunft.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F637%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Erbitten%20Anschriften%20der%20letzten%20f%C3%BCnf%20Jahre%20f%C3%BCr%20vollst%C3%A4ndigere%20Auskunft.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
