### ISSUE TITLE
New company suggestion: `SoundHound Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#641]
The following suggestion was submitted through the website:

```
{
    "slug": "soundhoundcom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "SoundHound Inc.",
    "runs": [
        "Powered by Houndify"
    ],
    "address": "5400 Betsy Ross Drive\nSanta Clara, CA 95054\nUSA",
    "email": "privacy@soundhound.com",
    "web": "https://www.soundhound.com",
    "sources": [
        "https://www.soundhound.com/en/privacy",
        "https://github.com/datenanfragen/data/issues/641"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22soundhoundcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22SoundHound%20Inc.%22%2C%22runs%22%3A%5B%22Powered%20by%20Houndify%22%5D%2C%22address%22%3A%225400%20Betsy%20Ross%20Drive%5CnSanta%20Clara%2C%20CA%2095054%5CnUSA%22%2C%22email%22%3A%22privacy%40soundhound.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.soundhound.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.soundhound.com%2Fen%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F641%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
