### ISSUE TITLE
New company suggestion: `MTCH Technology Services Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#642]
The following suggestion was submitted through the website:

```
{
    "slug": "accountgotindercom",
    "relevant-countries": [
        "all"
    ],
    "name": "MTCH Technology Services Limited",
    "runs": [
        "Tinder (Europe)"
    ],
    "address": "\n\nPrivacy Officer\nMTCH Technology Services Limited\nTinder\nWeWork Charlemont Exchange\n42 Charlemont Street\nDublin 2, D02 R593\nIreland",
    "web": "https://account.gotinder.com/data",
    "comments": [
        null
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/642"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22accountgotindercom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22MTCH%20Technology%20Services%20Limited%22%2C%22runs%22%3A%5B%22Tinder%20(Europe)%22%5D%2C%22address%22%3A%22%5Cn%5CnPrivacy%20Officer%5CnMTCH%20Technology%20Services%20Limited%5CnTinder%5CnWeWork%20Charlemont%20Exchange%5Cn42%20Charlemont%20Street%5CnDublin%202%2C%20D02%20R593%5CnIreland%22%2C%22web%22%3A%22https%3A%2F%2Faccount.gotinder.com%2Fdata%22%2C%22comments%22%3A%5Bnull%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F642%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks but Tinder is already in our database: https://www.datarequests.org/company/match-group
