### ISSUE TITLE
New company suggestion: `Wissenschaftsstadt Darmstadt, Meldebehörde`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#643]
The following suggestion was submitted through the website:

```
{
    "slug": "rathausdarmstadtde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "public body"
    ],
    "name": "Wissenschaftsstadt Darmstadt, Meldebehörde",
    "address": "Bürger- und Ordnungsamt\nAbt. Einwohnerwesen\nGrafenstr. 30\n\n64283 Darmstadt",
    "phone": "06151 13-3222",
    "fax": "06151 13-3006",
    "email": "meldeamt@darmstadt.de",
    "web": "https://rathaus.darmstadt.de/public/index.php?l=1&mr=20&smr=200&o=92",
    "needs-id-document": false,
    "suggested-transport-medium": "letter",
    "comments": [
        "Bitte beauskunften Sie auch, an wen meine personenbezogenen Daten in der Vergangenheit weitergegeben wurden.",
        null
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/643"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22rathausdarmstadtde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Wissenschaftsstadt%20Darmstadt%2C%20Meldebeh%C3%B6rde%22%2C%22address%22%3A%22B%C3%BCrger-%20und%20Ordnungsamt%5CnAbt.%20Einwohnerwesen%5CnGrafenstr.%2030%5Cn%5Cn64283%20Darmstadt%22%2C%22phone%22%3A%2206151%2013-3222%22%2C%22fax%22%3A%2206151%2013-3006%22%2C%22email%22%3A%22meldeamt%40darmstadt.de%22%2C%22web%22%3A%22https%3A%2F%2Frathaus.darmstadt.de%2Fpublic%2Findex.php%3Fl%3D1%26mr%3D20%26smr%3D200%26o%3D92%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22Bitte%20beauskunften%20Sie%20auch%2C%20an%20wen%20meine%20personenbezogenen%20Daten%20in%20der%20Vergangenheit%20weitergegeben%20wurden.%22%2Cnull%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F643%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
