### ISSUE TITLE
Suggested update for company `netcup`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#644]
The following suggestion was submitted through the website:

```
{
    "slug": "netcup",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "netcup GmbH",
    "address": "Daimlerstraße 25\n76185 Karlsruhe\nDeutschland",
    "phone": "+49 721 75407550",
    "fax": "+49 721 75407559",
    "email": "datenschutz@netcup.de",
    "web": "https://www.netcup.de/",
    "sources": [
        "https://www.netcup.de/kontakt/datenschutzerklaerung.php",
        "https://www.netcup.de/kontakt/impressum.php",
        "https://github.com/datenanfragen/data/issues/644"
    ],
    "comments": [
        "Siehe datenschutzerklaerung.php unter Punkt 3 \"Datenschutzbeauftragter\"."
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22netcup%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22netcup%20GmbH%22%2C%22address%22%3A%22Daimlerstra%C3%9Fe%2025%5Cn76185%20Karlsruhe%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20721%2075407550%22%2C%22fax%22%3A%22%2B49%20721%2075407559%22%2C%22email%22%3A%22datenschutz%40netcup.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.netcup.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.netcup.de%2Fkontakt%2Fdatenschutzerklaerung.php%22%2C%22https%3A%2F%2Fwww.netcup.de%2Fkontakt%2Fimpressum.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F644%22%5D%2C%22comments%22%3A%5B%22Siehe%20datenschutzerklaerung.php%20unter%20Punkt%203%20%5C%22Datenschutzbeauftragter%5C%22.%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
