### ISSUE TITLE
New company suggestion: `bofrost*Dienstleistungs GmbH & Co. KG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#645]
The following suggestion was submitted through the website:

```
{
    "slug": "bofrostde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "commerce",
        "utility"
    ],
    "name": "bofrost*Dienstleistungs GmbH & Co. KG",
    "address": "An der Oelmühle 6\n47638 Straelen",
    "phone": "02834 - 707-0",
    "fax": "02834 - 707-594",
    "email": "datenschutz@bofrost.de",
    "web": "https://www.bofrost.de",
    "sources": [
        "https://www.bofrost.de/datenschutz.html",
        "https://github.com/datenanfragen/data/issues/645"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bofrostde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22utility%22%5D%2C%22name%22%3A%22bofrost*Dienstleistungs%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22An%20der%20Oelm%C3%BChle%206%5Cn47638%20Straelen%22%2C%22phone%22%3A%2202834%20-%20707-0%22%2C%22fax%22%3A%2202834%20-%20707-594%22%2C%22email%22%3A%22datenschutz%40bofrost.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bofrost.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bofrost.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F645%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
