### ISSUE TITLE
New company suggestion: `top itservices AG`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#646]
The following suggestion was submitted through the website:

```
{
    "slug": "top-itservicescom",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        null
    ],
    "name": "top itservices AG",
    "address": "top itservices AG\nInselkammerstraße 1\nD-82008 Unterhaching",
    "phone": "+49 89 95468135",
    "fax": "+49 89 95468199",
    "email": "service@top-itservices.com",
    "web": "https://www.top-itservices.com",
    "sources": [
        "https://www.top-itservices.com",
        "https://github.com/datenanfragen/data/issues/646"
    ],
    "comments": [
        "https://www.top-itservices.com/datenschutz/\n\nDatenschutzbeauftragter\n\nDen Datenschutzbeauftragten der top itservices AG erreichen Sie so:\n\nPostalisch:\n\nDatenschutzbeauftragter der top itservices AG\n\nc/o activeMind AG\n\nPotsdamer Str. 3\n\n80802 München\n\n \n\nTelefonisch: +49 89 919294-900\n\nE-Mail:datenschutz@top-itservices.com"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22top-itservicescom%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22top%20itservices%20AG%22%2C%22address%22%3A%22top%20itservices%20AG%5CnInselkammerstra%C3%9Fe%201%5CnD-82008%20Unterhaching%22%2C%22phone%22%3A%22%2B49%2089%2095468135%22%2C%22fax%22%3A%22%2B49%2089%2095468199%22%2C%22email%22%3A%22service%40top-itservices.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.top-itservices.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.top-itservices.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F646%22%5D%2C%22comments%22%3A%5B%22https%3A%2F%2Fwww.top-itservices.com%2Fdatenschutz%2F%5Cn%5CnDatenschutzbeauftragter%5Cn%5CnDen%20Datenschutzbeauftragten%20der%20top%20itservices%20AG%20erreichen%20Sie%20so%3A%5Cn%5CnPostalisch%3A%5Cn%5CnDatenschutzbeauftragter%20der%20top%20itservices%20AG%5Cn%5Cnc%2Fo%20activeMind%20AG%5Cn%5CnPotsdamer%20Str.%203%5Cn%5Cn80802%20M%C3%BCnchen%5Cn%5Cn%20%5Cn%5CnTelefonisch%3A%20%2B49%2089%20919294-900%5Cn%5CnE-Mail%3Adatenschutz%40top-itservices.com%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
