### ISSUE TITLE
New company suggestion: `Smash Online GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#647]
The following suggestion was submitted through the website:

```
{
    "slug": "smash-online-gmbh",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "ads"
    ],
    "name": "Smash Online GmbH",
    "runs": [
        "Agentur Smash"
    ],
    "address": "Landsberger Straße 155, 80687 München",
    "web": "www.agentur-smash.de",
    "sources": [
        "Homepage/ Newsletter",
        "https://github.com/datenanfragen/data/issues/647"
    ],
    "required-elements": [
        {
            "desc": "Mail@agentur-smash.de",
            "type": "email",
            "optional": false
        }
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22smash-online-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Smash%20Online%20GmbH%22%2C%22runs%22%3A%5B%22Agentur%20Smash%22%5D%2C%22address%22%3A%22Landsberger%20Stra%C3%9Fe%20155%2C%2080687%20M%C3%BCnchen%22%2C%22web%22%3A%22www.agentur-smash.de%22%2C%22sources%22%3A%5B%22Homepage%2F%20Newsletter%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F647%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Mail%40agentur-smash.de%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
