### ISSUE TITLE
New company suggestion: `Lottoland`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#648]
The following suggestion was submitted through the website:

```
{
    "slug": "lottoland",
    "relevant-countries": [
        "all"
    ],
    "name": "Lottoland",
    "address": "Deutsche Lotto- und Sportwetten Ltd.\nValley Towers, Suite 5\nValley Road, Birkirkara\nBKR 9022, Malta ",
    "phone": "040 - 82 21 69 31",
    "email": "dpo@lottoland.com",
    "sources": [
        "https://www.lottoland.com/datenschutz",
        "https://www.lottoland.com/impressum",
        "https://github.com/datenanfragen/data/issues/648"
    ],
    "needs-id-document": true,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22lottoland%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Lottoland%22%2C%22address%22%3A%22Deutsche%20Lotto-%20und%20Sportwetten%20Ltd.%5CnValley%20Towers%2C%20Suite%205%5CnValley%20Road%2C%20Birkirkara%5CnBKR%209022%2C%20Malta%20%22%2C%22phone%22%3A%22040%20-%2082%2021%2069%2031%22%2C%22email%22%3A%22dpo%40lottoland.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lottoland.com%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.lottoland.com%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F648%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
