### ISSUE TITLE
New company suggestion: `Sony Interactive Entertainment Europe Limited`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#649]
The following suggestion was submitted through the website:

```
{
    "slug": "playstationcom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "Sony Interactive Entertainment Europe Limited",
    "runs": [
        null
    ],
    "address": "10 Great Marlborough Street\nLondon\nW1F 7LP\nUnited Kingdom",
    "email": "dpo@scee.net",
    "web": "https://www.playstation.com/de-at/footer/about-us/",
    "sources": [
        "https://www.playstation.com/de-at/legal/privacy-policy/",
        "https://github.com/datenanfragen/data/issues/649"
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "letter"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22playstationcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Sony%20Interactive%20Entertainment%20Europe%20Limited%22%2C%22runs%22%3A%5Bnull%5D%2C%22address%22%3A%2210%20Great%20Marlborough%20Street%5CnLondon%5CnW1F%207LP%5CnUnited%20Kingdom%22%2C%22email%22%3A%22dpo%40scee.net%22%2C%22web%22%3A%22https%3A%2F%2Fwww.playstation.com%2Fde-at%2Ffooter%2Fabout-us%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.playstation.com%2Fde-at%2Flegal%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F649%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
