### ISSUE TITLE
Suggested update for company `soundcloud`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#652]
The following suggestion was submitted through the website:

```
{
    "slug": "soundcloud",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "SoundCloud Limited",
    "runs": [
        "SoundCloud Go+",
        "SoundCloud Inc."
    ],
    "address": "Rheinsberger Straße 76 – 77\n10115 Berlin\nDeutschland",
    "phone": "+49 30 467247600",
    "email": "dataprotection@soundcloud.com",
    "web": "https://soundcloud.com/",
    "sources": [
        "https://soundcloud.com/pages/privacy",
        "https://soundcloud.com/imprint",
        "https://github.com/datenanfragen/data/issues/652"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22soundcloud%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22SoundCloud%20Limited%22%2C%22runs%22%3A%5B%22SoundCloud%20Go%2B%22%2C%22SoundCloud%20Inc.%22%5D%2C%22address%22%3A%22Rheinsberger%20Stra%C3%9Fe%2076%20%E2%80%93%C2%A077%5Cn10115%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20467247600%22%2C%22email%22%3A%22dataprotection%40soundcloud.com%22%2C%22web%22%3A%22https%3A%2F%2Fsoundcloud.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fsoundcloud.com%2Fpages%2Fprivacy%22%2C%22https%3A%2F%2Fsoundcloud.com%2Fimprint%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F652%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
