### ISSUE TITLE
Suggested update for company `mailchimp`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#653]
The following suggestion was submitted through the website:

```
{
    "slug": "mailchimp",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "ads",
        "telecommunication"
    ],
    "name": "The Rocket Science Group LLC",
    "runs": [
        "MailChimp (mailchimp.com)"
    ],
    "address": "675 Ponce de Leon Ave NE\nSuite 5000\nAtlanta\nGA 30308\nUnited States of America",
    "email": "personaldatarequests@mailchimp.com",
    "web": "https://mailchimp.com",
    "sources": [
        "https://mailchimp.com/legal/privacy/",
        "https://github.com/datenanfragen/data/issues/653"
    ],
    "request-language": "en",
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mailchimp%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22The%20Rocket%20Science%20Group%20LLC%22%2C%22runs%22%3A%5B%22MailChimp%20(mailchimp.com)%22%5D%2C%22address%22%3A%22675%20Ponce%20de%20Leon%20Ave%20NE%5CnSuite%205000%5CnAtlanta%5CnGA%2030308%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22personaldatarequests%40mailchimp.com%22%2C%22web%22%3A%22https%3A%2F%2Fmailchimp.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmailchimp.com%2Flegal%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F653%22%5D%2C%22request-language%22%3A%22en%22%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
