### ISSUE TITLE
New company suggestion: `SameTunes LLC`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#654]
The following suggestion was submitted through the website:

```
{
    "slug": "sametunes-llc",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment"
    ],
    "name": "SameTunes LLC",
    "address": "300 Colonial Center Parkway STE 100N,\nRoswell 30076 - Georgia,\nUnited States of America",
    "email": "support@sametunes.com",
    "web": "sametunes.com",
    "sources": [
        "https://sametunes.com/privacy.php",
        "https://github.com/datenanfragen/data/issues/654"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Email",
            "type": "email",
            "optional": false
        }
    ],
    "needs-id-document": false,
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sametunes-llc%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22SameTunes%20LLC%22%2C%22address%22%3A%22300%20Colonial%20Center%20Parkway%20STE%20100N%2C%5CnRoswell%2030076%20-%20Georgia%2C%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22support%40sametunes.com%22%2C%22web%22%3A%22sametunes.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fsametunes.com%2Fprivacy.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F654%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks.
