### ISSUE TITLE
New company suggestion: `JartexNetwork`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#655]
The following suggestion was submitted through the website:

```
{
    "slug": "jartexnetworkcom",
    "relevant-countries": [
        "all"
    ],
    "name": "JartexNetwork",
    "email": "info@jartexnetwork.com",
    "web": "https://jartexnetwork.com",
    "suggested-transport-medium": "email",
    "comments": [
        "they dont have most of the info in this form so im leaving them empty"
    ],
    "sources": [
        "https://github.com/datenanfragen/data/issues/655"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22jartexnetworkcom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22JartexNetwork%22%2C%22email%22%3A%22info%40jartexnetwork.com%22%2C%22web%22%3A%22https%3A%2F%2Fjartexnetwork.com%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22they%20dont%20have%20most%20of%20the%20info%20in%20this%20form%20so%20im%20leaving%20them%20empty%22%5D%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F655%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
