### ISSUE TITLE
Suggested update for company `travix`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#656]
The following suggestion was submitted through the website:

```
{
    "slug": "travix",
    "relevant-countries": [
        "de",
        "nl"
    ],
    "categories": [
        "travel"
    ],
    "name": "Travix Nederland B.V.",
    "runs": [
        "Flugladen.de (www.flugladen.de)",
        "BudgetAir.com (www.budgetair.com)",
        "CheapTickets.nl (www.cheaptickets.nl)",
        "Vliegwinkel.nl (www.vliegwinkel.nl)"
    ],
    "address": "Piet Heinkade 55\n1019 GM Amsterdam\nNetherlands",
    "phone": "+49 30 22409372",
    "email": "info@flugladen.de",
    "web": "https://www.travix.com/",
    "sources": [
        "https://s1.travix.com/flugladen/DE/flde-privacy-de.pdf",
        "https://www.flugladen.de/impressum",
        "https://s1.travix.com/budgetair/UK/buauk-privacy-en.pdf",
        "https://s1.travix.com/cheaptickets/NL/assets/pdf/ctnl-privacy-nl.pdf",
        "https://s1.travix.com/vliegwinkel/NL/assets/pdf/vwnl-privacy-nl.pdf",
        "https://github.com/datenanfragen/data/issues/656"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22travix%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22nl%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Travix%20Nederland%20B.V.%22%2C%22runs%22%3A%5B%22Flugladen.de%20(www.flugladen.de)%22%2C%22BudgetAir.com%20(www.budgetair.com)%22%2C%22CheapTickets.nl%20(www.cheaptickets.nl)%22%2C%22Vliegwinkel.nl%20(www.vliegwinkel.nl)%22%5D%2C%22address%22%3A%22Piet%20Heinkade%2055%5Cn1019%20GM%20Amsterdam%5CnNetherlands%22%2C%22phone%22%3A%22%2B49%2030%2022409372%22%2C%22email%22%3A%22info%40flugladen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.travix.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fs1.travix.com%2Fflugladen%2FDE%2Fflde-privacy-de.pdf%22%2C%22https%3A%2F%2Fwww.flugladen.de%2Fimpressum%22%2C%22https%3A%2F%2Fs1.travix.com%2Fbudgetair%2FUK%2Fbuauk-privacy-en.pdf%22%2C%22https%3A%2F%2Fs1.travix.com%2Fcheaptickets%2FNL%2Fassets%2Fpdf%2Fctnl-privacy-nl.pdf%22%2C%22https%3A%2F%2Fs1.travix.com%2Fvliegwinkel%2FNL%2Fassets%2Fpdf%2Fvwnl-privacy-nl.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F656%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks but there doesn't seem to be any changes.
