### ISSUE TITLE
New company suggestion: ` mebis`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#658]
The following suggestion was submitted through the website:

```
{
    "slug": "mebisbayernde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "school"
    ],
    "name": " mebis",
    "address": "Schellingstr. 155\n80797 München\nDeutschland",
    "email": " datenschutz@isb.bayern.de",
    "web": "https://www.mebis.bayern.de",
    "sources": [
        "https://www.mebis.bayern.de/datenschutzerklaerung/",
        "https://github.com/datenanfragen/data/issues/658"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "E-Mail",
            "type": "email",
            "optional": false
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": true
        }
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mebisbayernde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22%20mebis%22%2C%22address%22%3A%22Schellingstr.%20155%5Cn80797%20M%C3%BCnchen%5CnDeutschland%22%2C%22email%22%3A%22%20datenschutz%40isb.bayern.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mebis.bayern.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mebis.bayern.de%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F658%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Atrue%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
