### ISSUE TITLE
New company suggestion: `Fitness First Germany GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#663]
The following suggestion was submitted through the website:

```
{
    "slug": "fitness-first-germany-gmbh",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health"
    ],
    "name": "Fitness First Germany GmbH",
    "address": "Hanauer Landstr. 148a\n\n60314 Frankfurt am Main",
    "phone": "069 4080 160 00",
    "fax": "069 4080 160 19",
    "email": "datenschutz@fitnessfirst.de",
    "web": "www.fitnessfirst.de",
    "sources": [
        "https://www.fitnessfirst.de/rechtliches/datenschutz",
        "https://github.com/datenanfragen/data/issues/663"
    ],
    "needs-id-document": false
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fitness-first-germany-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Fitness%20First%20Germany%20GmbH%22%2C%22address%22%3A%22Hanauer%20Landstr.%20148a%5Cn%5Cn60314%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22069%204080%20160%2000%22%2C%22fax%22%3A%22069%204080%20160%2019%22%2C%22email%22%3A%22datenschutz%40fitnessfirst.de%22%2C%22web%22%3A%22www.fitnessfirst.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fitnessfirst.de%2Frechtliches%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F663%22%5D%2C%22needs-id-document%22%3Afalse%7D)**

**Comment by baltpeter** [comment]
Thanks!
