### ISSUE TITLE
New company suggestion: `SHL Telemedizin GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#664]
The following suggestion was submitted through the website:

```
{
    "slug": "shl-telemedizin-gmbh",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health"
    ],
    "name": "SHL Telemedizin GmbH",
    "runs": [
        "almeda GmbH",
        "SHL Telemedizin GmbH"
    ],
    "address": "Balanstraße 69b\n81541 München\nDeutschland",
    "phone": "+49 89 480590",
    "email": "<redacted>",
    "web": "shl-telemedizin.de",
    "sources": [
        "https://www.shl-telemedizin.de/datenschutz/datenschutz-shl/",
        "https://www.shl-telemedizin.de/datenschutz/datenschutz-almeda/",
        "https://www.shl-telemedizin.de/datenschutz/datenschutz-dgp/",
        "https://github.com/datenanfragen/data/issues/664"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": false
        },
        {
            "type": "input"
        }
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22shl-telemedizin-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22SHL%20Telemedizin%20GmbH%22%2C%22runs%22%3A%5B%22almeda%20GmbH%22%2C%22SHL%20Telemedizin%20GmbH%22%5D%2C%22address%22%3A%22Balanstra%C3%9Fe%2069b%5Cn81541%20M%C3%BCnchen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2089%20480590%22%2C%22email%22%3A%22redacted%22%2C%22web%22%3A%22shl-telemedizin.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.shl-telemedizin.de%2Fdatenschutz%2Fdatenschutz-shl%2F%22%2C%22https%3A%2F%2Fwww.shl-telemedizin.de%2Fdatenschutz%2Fdatenschutz-almeda%2F%22%2C%22https%3A%2F%2Fwww.shl-telemedizin.de%2Fdatenschutz%2Fdatenschutz-dgp%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F664%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Afalse%7D%2C%7B%22type%22%3A%22input%22%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
