### ISSUE TITLE
New company suggestion: `compass private pflegeberatung GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#665]
The following suggestion was submitted through the website:

```
{
    "slug": "compass-pflegeberatungde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health"
    ],
    "name": "compass private pflegeberatung GmbH",
    "address": "KINAST Rechtsanwaltsgesellschaft mbH\nHohenzollernring 54\n50672 Köln\nDeutschland",
    "phone": "0221-222 183 0",
    "email": "mail@kinast.eu",
    "web": "https://www.compass-pflegeberatung.de/",
    "sources": [
        "https://www.compass-pflegeberatung.de/datenschutz",
        "https://github.com/datenanfragen/data/issues/665"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": false
        }
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22compass-pflegeberatungde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22compass%20private%20pflegeberatung%20GmbH%22%2C%22address%22%3A%22KINAST%20Rechtsanwaltsgesellschaft%20mbH%5CnHohenzollernring%2054%5Cn50672%20K%C3%B6ln%5CnDeutschland%22%2C%22phone%22%3A%220221-222%20183%200%22%2C%22email%22%3A%22mail%40kinast.eu%22%2C%22web%22%3A%22https%3A%2F%2Fwww.compass-pflegeberatung.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.compass-pflegeberatung.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F665%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Afalse%7D%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
