### ISSUE TITLE
New company suggestion: `Deutsches Rotes Kreuz Nordrhein gGmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#666]
The following suggestion was submitted through the website:

```
{
    "slug": "drk-nordrhein-ggmbhde",
    "relevant-countries": [
        "de"
    ],
    "categories": [
        "health"
    ],
    "name": "Deutsches Rotes Kreuz Nordrhein gGmbH",
    "runs": [
        "Deutsches Rotes Kreuz Assistance GmbH"
    ],
    "address": "Auf´m Hennekamp 71\n40225 Düsseldorf\nDeutschland",
    "phone": "+49 211 31040",
    "email": "datenschutz@drk-nordrhein.de",
    "web": "https://www.drk-nordrhein-ggmbh.de/datenschutzerklaerung/",
    "sources": [
        "https://www.drk-nordrhein-ggmbh.de",
        "https://github.com/datenanfragen/data/issues/666"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": false
        }
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22drk-nordrhein-ggmbhde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Deutsches%20Rotes%20Kreuz%20Nordrhein%20gGmbH%22%2C%22runs%22%3A%5B%22Deutsches%20Rotes%20Kreuz%20Assistance%20GmbH%22%5D%2C%22address%22%3A%22Auf%C2%B4m%20Hennekamp%2071%5Cn40225%20D%C3%BCsseldorf%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20211%2031040%22%2C%22email%22%3A%22datenschutz%40drk-nordrhein.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.drk-nordrhein-ggmbh.de%2Fdatenschutzerklaerung%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.drk-nordrhein-ggmbh.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F666%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thank you!
