### ISSUE TITLE
New company suggestion: `GMMI, Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#667]
The following suggestion was submitted through the website:

```
{
    "slug": "gmmicom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "health"
    ],
    "name": "GMMI, Inc.",
    "address": "880 SW 145th Avenue, Suite 400\nPembroke Pines, Florida 33027\nUSA",
    "phone": " 1-954-370-6404",
    "email": " legal@gmmi.com",
    "web": "https://www.gmmi.com",
    "sources": [
        "https://www.gmmi.com/-/media/partner-portal/gmmi/files/gdpr/gdpr_privacypolicy_pdf.pdf",
        "https://github.com/datenanfragen/data/issues/667"
    ],
    "required-elements": [
        {
            "desc": "Name",
            "type": "name",
            "optional": false
        },
        {
            "desc": "Adresse",
            "type": "address",
            "optional": false
        }
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gmmicom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22GMMI%2C%20Inc.%22%2C%22address%22%3A%22880%20SW%20145th%20Avenue%2C%20Suite%20400%5CnPembroke%20Pines%2C%20Florida%2033027%5CnUSA%22%2C%22phone%22%3A%22%201-954-370-6404%22%2C%22email%22%3A%22%20legal%40gmmi.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gmmi.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gmmi.com%2F-%2Fmedia%2Fpartner-portal%2Fgmmi%2Ffiles%2Fgdpr%2Fgdpr_privacypolicy_pdf.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F667%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Afalse%7D%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
