### ISSUE TITLE
Suggested update for company `reddit`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#669]
The following suggestion was submitted through the website:

```diff
 {
+  comments: [
+    "\"requests [...] should be sent via email [...] from the email address that you have verified with your Reddit account.\""
+  ]
-  email: "legal@reddit.com"
+  email: "redditdatarequests@reddit.com"
   sources: [
     "https://www.redditinc.com/policies/privacy-policy"
     "https://www.bloomberg.com/profiles/companies/0893288D:US-reddit-inc"
+    "https://github.com/datenanfragen/data/issues/669"
   ]
 }

```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22reddit%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Reddit%2C%20Inc.%22%2C%22address%22%3A%22520%203rd%20Street%5CnSan%20Francisco%5CnCA%2094107%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22redditdatarequests%40reddit.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.reddit.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.redditinc.com%2Fpolicies%2Fprivacy-policy%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fprofiles%2Fcompanies%2F0893288D%3AUS-reddit-inc%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F669%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Username%22%2C%22type%22%3A%22input%22%7D%5D%2C%22request-language%22%3A%22en%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22%5C%22requests%20%5B...%5D%20should%20be%20sent%20via%20email%20%5B...%5D%20from%20the%20email%20address%20that%20you%20have%20verified%20with%20your%20Reddit%20account.%5C%22%22%5D%7D)**

**Comment by baltpeter** [comment]
Thank you!
