### ISSUE TITLE
New company suggestion: `Riot Games, Inc.`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#670]
The following suggestion was submitted through the website:

```
{
    "slug": "riotgamescom",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "entertainment",
        "social media",
        null
    ],
    "name": "Riot Games, Inc.",
    "runs": [
        "League of Legends",
        "Valorant"
    ],
    "address": "Riot Games Ltd.\nAttn: Legal Department\nPO Box 11989\nDublin 2\nIreland ",
    "email": "privacy@riotgames.com ",
    "web": "https://www.riotgames.com",
    "sources": [
        "https://www.riotgames.com/en/privacy-notice",
        "https://github.com/datenanfragen/data/issues/670"
    ],
    "suggested-transport-medium": "email",
    "comments": [
        "there are several adresses provided, see https://www.riotgames.com/en/privacy-notice#contact-us"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22riotgamescom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%2Cnull%5D%2C%22name%22%3A%22Riot%20Games%2C%20Inc.%22%2C%22runs%22%3A%5B%22League%20of%20Legends%22%2C%22Valorant%22%5D%2C%22address%22%3A%22Riot%20Games%20Ltd.%5CnAttn%3A%20Legal%20Department%5CnPO%20Box%2011989%5CnDublin%202%5CnIreland%20%22%2C%22email%22%3A%22privacy%40riotgames.com%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.riotgames.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.riotgames.com%2Fen%2Fprivacy-notice%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F670%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22there%20are%20several%20adresses%20provided%2C%20see%20https%3A%2F%2Fwww.riotgames.com%2Fen%2Fprivacy-notice%23contact-us%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
