### ISSUE TITLE
New company suggestion: `Twilio`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#671]
The following suggestion was submitted through the website:

```
{
    "slug": "twilio",
    "relevant-countries": [
        "all"
    ],
    "categories": [
        "telecommunication"
    ],
    "name": "Twilio",
    "runs": [
        "Authy",
        "Sendgrid"
    ],
    "address": "25 N Wall Quay\nNorth Wall\nDublin 1\nD01 H104\nIreland",
    "email": "privacy@twilio.com",
    "sources": [
        "https://www.twilio.com/legal/privacy",
        "https://github.com/datenanfragen/data/issues/671"
    ],
    "suggested-transport-medium": "email"
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22twilio%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Twilio%22%2C%22runs%22%3A%5B%22Authy%22%2C%22Sendgrid%22%5D%2C%22address%22%3A%2225%20N%20Wall%20Quay%5CnNorth%20Wall%5CnDublin%201%5CnD01%20H104%5CnIreland%22%2C%22email%22%3A%22privacy%40twilio.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.twilio.com%2Flegal%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F671%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

**Comment by baltpeter** [comment]
Thanks!
