### ISSUE TITLE
New company suggestion: `Salford Council`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#672]
The following suggestion was submitted through the website:

```
{
    "slug": "salfordgovuk",
    "relevant-countries": [
        "gb"
    ],
    "categories": [
        "public body"
    ],
    "name": "Salford Council",
    "address": "Information Governance Team\nLegal and Governance\nSalford City Council\nCivic Centre\nChorley Road\nSwinton\nM27 5DA",
    "phone": "0161 793 2500",
    "email": "infogovernance@salford.gov.uk",
    "web": "https://salford.gov.uk",
    "needs-id-document": false,
    "suggested-transport-medium": "email",
    "sources": [
        "https://github.com/datenanfragen/data/issues/672"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22salfordgovuk%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Salford%20Council%22%2C%22address%22%3A%22Information%20Governance%20Team%5CnLegal%20and%20Governance%5CnSalford%20City%20Council%5CnCivic%20Centre%5CnChorley%20Road%5CnSwinton%5CnM27%205DA%22%2C%22phone%22%3A%220161%20793%202500%22%2C%22email%22%3A%22infogovernance%40salford.gov.uk%22%2C%22web%22%3A%22https%3A%2F%2Fsalford.gov.uk%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F672%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks!
