### ISSUE TITLE
New company suggestion: `Lebe Gesund-Versand GmbH`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#682]
The following suggestion was submitted through the website:

```
{
    "slug": "lebe-gesund-versand-gmbh",
    "relevant-countries": [
        "de",
        "at"
    ],
    "categories": [
        "commerce"
    ],
    "name": "Lebe Gesund-Versand GmbH",
    "address": "Max-Braun-Str. 4\n97828 Marktheidenfeld",
    "phone": "0800/122 4000",
    "fax": "0800/122 4009",
    "email": "info@lebegesund.de",
    "web": "lebegesund.de",
    "sources": [
        "https://www.lebegesund.de/impressum-bildnachweis",
        "https://github.com/datenanfragen/data/issues/682"
    ]
}
```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22lebe-gesund-versand-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Lebe%20Gesund-Versand%20GmbH%22%2C%22address%22%3A%22Max-Braun-Str.%204%5Cn97828%20Marktheidenfeld%22%2C%22phone%22%3A%220800%2F122%204000%22%2C%22fax%22%3A%220800%2F122%204009%22%2C%22email%22%3A%22info%40lebegesund.de%22%2C%22web%22%3A%22lebegesund.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lebegesund.de%2Fimpressum-bildnachweis%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F682%22%5D%7D)**

**Comment by baltpeter** [comment]
Thanks.
