### ISSUE TITLE
Suggested update for company `bitly`

### ISSUE THREAD

**Issue by datenanfragen-community-edits** [datenanfragen/data#683]
The following suggestion was submitted through the website:

```diff
 {
-  email: "support@bitly.com"
+  email: "privacy@bitly.com"
   sources: [
     "https://bitly.com/pages/privacy"
     "https://www.bloomberg.com/profiles/companies/8167727Z:US-bitly-inc"
+    "https://github.com/datenanfragen/data/issues/683"
   ]
 }

```

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bitly%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Bitly%2C%20Inc.%22%2C%22address%22%3A%2285%205th%20Avenue%5CnNew%20York%5CnNY%2010003%5CnUnited%20States%20of%20America%22%2C%22phone%22%3A%22%2B1%20646%20678%205610%22%2C%22email%22%3A%22privacy%40bitly.com%22%2C%22web%22%3A%22https%3A%2F%2Fbitly.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbitly.com%2Fpages%2Fprivacy%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fprofiles%2Fcompanies%2F8167727Z%3AUS-bitly-inc%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F683%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22input%22%7D%5D%2C%22request-language%22%3A%22en%22%7D)**

**Comment by baltpeter** [comment]
That is a lot better, thank you!
