### ISSUE TITLE
Only allow GDPR countries in the schema

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#764]
Our schema currently allows all countries to be set as `relevant-countries`:

https://github.com/datenanfragen/data/blob/baf04307c6d152da3c561a99eef6c49810f42a35/schema.json#L20

However, this doesn't really make sense as we only care about the GDPR. We should change the schema to only accept countries where the GDPR is applicable. This of course includes all EU countries but also some others.

[This post](https://beasleydirect.com/gdpr-countries/) might be a good starting point, although I am not sure if it is complete.

**Comment by sudiptog81** [comment]
Can I work on this?

**Comment by baltpeter** [comment]
@sudiptog81 Sure, thanks!

**Comment by sudiptog81** [comment]
Should we remove modify the company data or add the countries which result in test failure?

**Comment by baltpeter** [comment]
Please remove the countries that have been removed from the schema from the company records.

But please re-add Switzerland, while the GDPR doesn't technically apply there, we want to keep supporting it.

**Comment by sudiptog81** [comment]
Sure, I am doing my bit of research in that case.
