### ISSUE TITLE
Check Match Group's services

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/data#825]
As discussed in #748: There are many services run by the [Match Group](https://github.com/datenanfragen/data/blob/master/companies/match-group.json) (thanks @rugk :D). We want to create new records for those that have their own privacy-related email address and bundle these that share an email.

- [x] "Plenty Of Fish (pof.com)",
- [x] "OkCupid (okcupid.com)",
- [x] "Meetic (meetic.fr)",
- [x] "Matchaffinity",
- [x] "LoveScout24",
- [x] "Twoo (twoo.com)",
- [x] "Neu.de",
- [x] "Partner.de",
- [x] "Amoureux (amoureux.com)",
- [x] "Lexamore.nl",
- [x] "DisonsDemain.fr",
- [x] "BlackPeopleMeet.com",
- [x] "OurTime",
- [x] "Pairs",
- [x] "ParPerfeito",
- [x] "LDSPlanet.com",
- [x] "PetPeopleMeet.com",
- [x] "BBPeople (bbpeoplemeet.com)",
- [x] "InterracialPeopleMeet.com",
- [x] "Chemistry.com",
- [x] "MarriageMindedPeopleMeet.com",
- [x] "LatinoPeopleMeet.com",
- [x] "DemocraticPeopleMeet.com",
- [x] "RepublicanPeopleMeet.com",
- [x] "BabyBoomerPeopleMeet.com",
- [x] "singleparentmeet.com",

**Comment by baltpeter** [comment]
See also: https://uk.match.com/pages/map/

**Comment by baltpeter** [comment]
The following are only available in the US and Canada:

* chemistry.com
* bbpeoplemeet.com
* singleparentmeet.com
* loveandseek.com
* blackpeoplemeet.com
* ldsplanet.com
* PetPeopleMeet.com
* InterracialPeopleMeet.com
* MarriageMindedPeopleMeet.com
* LatinoPeopleMeet.com
* DemocraticPeopleMeet.com
* RepublicanPeopleMeet.com
* BabyBoomerPeopleMeet.com

ParPerfeito is only available in Brazil.

**Comment by baltpeter** [comment]
I have opened #1107 for this.
